### ISSUE TITLE
[1.7.10] Unable to load singleplayer world

### ISSUE THREAD

**Issue by Zsashas** [jaredlll08/CraftTweaker#100]
https://gist.github.com/Zsashas/1407952808bfddcf38f7ce7e1a004387

I updated both CraftTweaker and ModTweaker to the latest 1.7.10 versions. Why is this still happening?

It just goes immediately back to the menu.

**Comment by jaredlll08** [comment]
no idea, how many scripts do you have? also 1.7.10 is no longer supported, so I'm closing this.

**Comment by Zsashas** [comment]
15 or so, I think.

**Comment by jaredlll08** [comment]
show a picture of the scripts?

**Comment by jaredlll08** [comment]
I mean the folder of the scripts, like the scripts folder
