### ISSUE TITLE
removeShapeless not working v3.0.15

### ISSUE THREAD

**Issue by MindlessPuppetz** [jaredlll08/CraftTweaker#101]
recipe.removeShaped works just fine, but recipe.removeShapeless does not seem to actually remove the recipe (although everything appears to load fine script-wise.

minetweaker.log: http://beta.pastee.com/aychd
script: http://beta.pastee.com/crrcu
MC Log: http://paste.ee/p/EFTBd

Yes, I have tried specifying the removal amount. And yes I tried a single removeShapeless recipe instead of an array. Neither the array nor single removal work.

MC: 1.10.2
Forge: 12.18.2.2123
Java: 1.8.0_111

**Comment by jaredlll08** [comment]
can you try downgrading crafttweaker? to like 3.0.13

**Comment by MindlessPuppetz** [comment]
3.0.13 is working! :+1:

**Comment by the-creamster** [comment]
Seeing as this is still open and i encountered this today too. Is it now essential to specify a Shaped/Shapeless recipe removal?? or does the original "recipes.remove" still work??

**Comment by MindlessPuppetz** [comment]
In 3.0.15 the removeShapeless is not working at all, in an array or out. So you cannot use it. Version 3.0.13 is working, though. With the array and as a single instance. @the-creamster

**Comment by jaredlll08** [comment]
Yea, I'll revert the changes I made, or test more and fix this, I'll see, either way, when I release 3.0.16, it will be fixed.

**Comment by jaredlll08** [comment]
fixed in the latest commit
