### ISSUE TITLE
Cannot resolve when removing recipe with wildcard

### ISSUE THREAD

**Issue by Hiatel** [jaredlll08/CraftTweaker#102]
Input/output : http://i.imgur.com/TTwk2FY.png
Tweaker log : http://beta.pastee.com/b3rtz
tested without wildcard syntax because I thought that may work for some reason
non-wildcard recipe removals work fine

**Comment by jaredlll08** [comment]
You can't use a wildcard to get any item from a mod.

**Comment by Hiatel** [comment]
Dang, how should i go about removing crafting recipes from all items in a mod then?

**Comment by jaredlll08** [comment]
Add all the items to an array, loop through array.
