### ISSUE TITLE
[1.7.10 possible 1.10.2] Scripts are not synced to client if the files have the same name.

### ISSUE THREAD

**Issue by MaDmaxwell311** [jaredlll08/CraftTweaker#103]
Description: If a client and server have a script with the same name, the server does not send the script to the client, even if the server's or client's files have different contents/file sizes. If the recipes are added to a separate file that the client does not have, the recipes will sync.

Steps I did to reproduce the bug: I am playing Project Ozone 2 and the server decided to add recipes for various items. So I added some recipes into the titanCrafting.zs file. I got reports that the items had no recipes and I told them that they had been added and to just relog. Upon relogging I noticed as well that the recipes were no longer there on my client. If the command "/mt reload" is done, the recipes appear, this is true upon server restart. 

Forge version: 10.14.4.1614
Modpack: Project Ozone 2 3.1.9
CraftTweaker version: 3.0.11

**Comment by jaredlll08** [comment]
uh yea, kinda intended, we checking the whole contents of each script would come with a huge performance overhead. I have seen scripts with thousands of lines, it would take a while to check, by using the names, it is a much quicker check.
