### ISSUE TITLE
The command: /mt loot

### ISSUE THREAD

**Issue by belathus** [jaredlll08/CraftTweaker#104]
While I believe that the help command doesn't list /mt loot, but it'd be nice to be able to get a log of all of the loot containers. Right now, this command simply returns an error.

**Comment by jaredlll08** [comment]
Mc version?

**Comment by belathus** [comment]
1.10.2, CraftTweaker version 3.0.15

**Comment by jaredlll08** [comment]
Loot isn't supported in 1.10+

**Comment by belathus** [comment]
Any chance it will be?

**Comment by jaredlll08** [comment]
Hopefully soon, not sure when, but by the end of the year

**Comment by belathus** [comment]
Awesome; we have too many mods that add too much loot. Thanks, Jared.

**Comment by Leviathan143** [comment]
@jaredlll08 
I've made a CT addon that allows loot tables to be tweaked. Would you like to take a look at the code?

**Comment by jaredlll08** [comment]
Please!

**Comment by Leviathan143** [comment]
@jaredlll08 
Here's the repo : https://github.com/Leviathan143/LootTweaker  
The important classes are [LootTableTweaker](https://github.com/Leviathan143/LootTweaker/blob/master/src/main/java/leviathan143/loottweaker/common/tweakers/loot/LootTableTweaker.java), [ZenLootTableWrapper](https://github.com/Leviathan143/LootTweaker/blob/master/src/main/java/leviathan143/loottweaker/common/zenscript/ZenLootTableWrapper.java), and [ZenLootPoolWrapper](https://github.com/Leviathan143/LootTweaker/blob/master/src/main/java/leviathan143/loottweaker/common/zenscript/ZenLootPoolWrapper.java)  
Docs for the ZenScript functions can be found on the repo wiki

**Comment by vpontin** [comment]
Thanks @Leviathan143 ! I hope your patches get added to the main release!

**Comment by Leviathan143** [comment]
@vpontin Thank you!
LootTweaker is actually available right now if you want to use it.
You can get it [here](https://minecraft.curseforge.com/projects/loottweaker)

**Comment by jaredlll08** [comment]
At this point, there are too many other options for this, LootTweaker and LootTableTweaker, so it would be unfair for me to implement this and kill off 2 mods.
