### ISSUE TITLE
Error loading script: No such member

### ISSUE THREAD

**Issue by Malkierian** [jaredlll08/CraftTweaker#105]
So, according to your wiki, things that applied to MT3 applied to CT.  Imagine my surprise when I try to add Mekanism recipes ([existed in MT3](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Mekanism_Support)), and I get the "No such member: mekanism" error.  You guys really need to update your own wiki with all of the mods you actually do support, if you don't even support everything that MT3 did.  Or, perhaps, there are now differences in the way the scripts are handled that need to be documented.  I followed the recipe format on there for the Enrichement Chamber, and the first line of those is what failed:
`mods.mekanism.Enrichment.addRecipe(<substratum:nugget:0> * 4, <railcraft:ore:5>);`

Am I missing something here?

**Comment by jaredlll08** [comment]
MC version?

**Comment by Malkierian** [comment]
1.10.2

**Comment by jaredlll08** [comment]
Imagine my surprise when I'm enjoying my Wednesday night and then I get this email. Now here comes the problem...
A) Crafttweaker never added the support for Mekanism, ModTweaker did.
B) The wiki is actually updated if you actually look harder you will see that there is no Mekanism support for 1.10.2
C) There is currently no plans to support mekanism as it is no longer developed.

**Comment by Malkierian** [comment]
What's no longer developed?  Mekanism's code base is active as recently as 5 days ago.

**Comment by Lanse505** [comment]
That was 2 pull requests and a Build.properties update.
And a branch merger.

Last proper commit was 23 days ago.

Also Mekanism as it currently stands has ALOT of unfinished issues that needs resolving.
It's our stance that Modtweaker support will get added once the mod is back on a more frequent updating scheduel and in a more stable state.
