### ISSUE TITLE
Unable to load SSP world

### ISSUE THREAD

**Issue by topher2010** [jaredlll08/CraftTweaker#106]
using latest version of CraftTweaker, getting an issue trying to load up an SSP world.  

http://pastebin.com/sX9ATU8D

As stated by one of my players, "I go to log into a ssp world (creative, flat), it goes to the loading screen and nothing happens, the console log is in the pastebin. The c/p's stuff happens just before it."

The world never loads, and there is no crash to desktop, it just hangs.

**Comment by jaredlll08** [comment]
Like I said in discord, I need more information! you have given me nothing to work on.
Minetweaker.log.
Scripts.
Game Log (I know it didn't crash, give the whole log)

**Comment by UnNinja** [comment]
https://dl.dropboxusercontent.com/u/67965036/fml-client-latest.log

scripts http://pastebin.com/UVDkuQGy

**Comment by jaredlll08** [comment]
Send me a picture of your scripts directory please

**Comment by UnNinja** [comment]
only thing in there is recipe.zs

**Comment by jaredlll08** [comment]
Do me a favour and create a new empty .zs file in the directory, name it anything, and try again

**Comment by jaredlll08** [comment]
This should be fixed in the latest release
