### ISSUE TITLE
Invalid Item when creating a Botania flower recipe with NBT

### ISSUE THREAD

**Issue by Eufranio** [jaredlll08/CraftTweaker#108]
That's my script:
```
recipes.addShaped(<BuildCraft|Builders:machineBlock>, [[<BuildCraft|Robotics:robot>, <Botania:specialFlower>.onlyWithTag({type: "orechid"}), <BuildCraft|Robotics:robot>],
	[<ImmersiveEngineering:metalDevice:14>, <BuildCraft|Factory:miningWellBlock>, <ImmersiveEngineering:metalDevice:14>],
	[<IC2:blockMachine:12>, <ThermalDynamics:ThermalDynamics_0:4>, <IC2:blockMachine:12>]]);
```
When using this, I get a flower with invalid NBT in the recipe:
![flower_3](http://image.prntscr.com/image/dd28818f07ed4f318b6df2c370367779.png)

If I use the `withTag` instead `onlyWithTag`, I get the right recipe:

![flower_3](http://image.prntscr.com/image/2f26e4e0241e4d1f8f7da7253b65ee22.png)
```
recipes.addShaped(<BuildCraft|Builders:machineBlock>, [[<BuildCraft|Robotics:robot>, <Botania:specialFlower>.withTag({type: "orechid"}), <BuildCraft|Robotics:robot>],
	[<ImmersiveEngineering:metalDevice:14>, <BuildCraft|Factory:miningWellBlock>, <ImmersiveEngineering:metalDevice:14>],
	[<IC2:blockMachine:12>, <ThermalDynamics:ThermalDynamics_0:4>, <IC2:blockMachine:12>]]);
```
![flower_3](http://image.prntscr.com/image/6cf1efec35cd4a83918bdd1517f1dc2f.png)

**Comment by jaredlll08** [comment]
uh yea. ".withTag" is for inputs, "withOnlyTag" is for outputs

**Comment by Eufranio** [comment]
But, when using `.withTag` in a input, I can use **any** flower with **any** NBT in the recipe, not the one that I specified.

**Comment by Eufranio** [comment]
Sorry by the mistake. Yes, you're right, It's working, but NEI won't display the right flower in the recipe, kinda ignoring all NBT... Do you know how to fix?

**Comment by jaredlll08** [comment]
no idea.
