### ISSUE TITLE
TileEntitySign not supported

### ISSUE THREAD

**Issue by LemADEC** [jaredlll08/CraftTweaker#110]
As explained here https://github.com/SpongePowered/SpongeForge/issues/1035 there's a few issues in the mod that leads to signs being unable to run commands.

**Comment by jaredlll08** [comment]
The issue was using an outdated crafttweaker, so I'm not sure if I fixed this correctly, just try it out and get back to me please: http://blamejared.com:8080/job/CraftTweaker/65/
