### ISSUE TITLE
Suggestion: Adding Items like ContentTweaker or Quadrum

### ISSUE THREAD

**Issue by DaNeo61** [jaredlll08/CraftTweaker#112]
It would be a awesome feature to add items via CraftTweaker 
and load the required resource maybe over the Mod "Resource Loader"
with Commands like in Quadrum or ContentTweaker just in Minecraft 1.10.2 ?

**Comment by darkhax** [comment]
This is a good idea, however due to the load order of this mod, and the priority on reloading it is not a good candidate for a feature in the main mod. An addon may be released which provides this functionality in the future.
