### ISSUE TITLE
Server crash on connect

### ISSUE THREAD

**Issue by Cuppycake** [jaredlll08/CraftTweaker#113]
It seems randomly on connect, usually after a restart, the server crashes with the following report:

http://pastebin.com/y9RT99jQ

**Comment by Cuppycake** [comment]
And again http://pastebin.com/rbyzxsiy

We're noticing its not actually on a player connect. Just on server start. The thing is its not always happening. Randomly it will just refuse to start and we get this crash. Then the auto check I have will attempt to restart. Sometimes it works sometimes it doesnt.

**Comment by jaredlll08** [comment]
Can you reproduce without sponge?

**Comment by jaredlll08** [comment]
Can you reproduce without sponge?

**Comment by Cuppycake** [comment]
I'll setup another server and let it run on the same automation as the other and see if I can't reproduce over the next day or so.

**Comment by Cuppycake** [comment]
Found out in the ATLauncher pack dev channel that another developer has the same issues and they do not run sponge, but they do use https://github.com/gsand/mark2

**Comment by jaredlll08** [comment]
Yea... Unless you could get me a log from "vanilla forge", there is not much I can do to fix this, since this error is giving me very little info :/

**Comment by jaredlll08** [comment]
Any news on this?

**Comment by Cuppycake** [comment]
Doesn't seem to be happening anymore.  Thinking it was an issue with sponge that they have corrected.

**Comment by jaredlll08** [comment]
ah ok.
