### ISSUE TITLE
[3.0.15] Furnace recipes that point to non-existent items causes a permanent hang on world load

### ISSUE THREAD

**Issue by belathus** [jaredlll08/CraftTweaker#114]
Server log: https://gist.github.com/belathus/226d939e7bb729011e7430102475de2b

No crash report since it technically isn't a crash.

I had three lines in the furnace.zs file that, when removed, stopped this from happening. To explain further, TAIGA removed the slagiron and slaggold ingots in the latest release. The lines were as follows:

```
furnace.addRecipe(<taiga:slagiron_ingot>, <ore:oreIron>, 0.5);
furnace.addRecipe(<taiga:slagiron_ingot>, <ore:oreGoethite>, 0.5);
furnace.addRecipe(<taiga:slagiron_ingot>, <ore:oreLimonite>, 0.5);
```

Not an urgent issue to fix since it was caused by adding a script pointing to a non-existent item, but it did take some time to track down and figure out why I couldn't start the world.

**Comment by jaredlll08** [comment]
Can you give me the minetweaker.log file?

**Comment by belathus** [comment]
Erm. I'll have to recreate it. I'll do so tonight.

**Comment by jaredlll08** [comment]
I can't really fix this without more info :/
