### ISSUE TITLE
[Bug] Trying to restart JEI from the wrong thread

### ISSUE THREAD

**Issue by MysticAura** [jaredlll08/CraftTweaker#115]
MC: 1.10.2
Forge: 2185
Mods: jei_1.10.2-3.13.6.387, CraftTweaker-1.10.2-3.0.15

Issue: same as title

[Log Entries](https://paste.ee/p/Znx3f#)

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/CraftTweaker/commit/7f4e59d9df8b8f70702904d80ee72a179f107a22
