### ISSUE TITLE
[1.7.10] CraftTweaker + ModTweaker Problems

### ISSUE THREAD

**Issue by Wealthyturtle** [jaredlll08/CraftTweaker#117]
**Note: This is Not a Crash, but Somehow CraftTweaker and ModTweaker are being Errored, Causing the Game to...**

On Servers - Terminate
On Singleplayer - Return back to Main Menu

Log for Server: [http://pastebin.com/ajAbwWVA](http://pastebin.com/ajAbwWVA), Picture as well: [https://cdn.discordapp.com/attachments/251186294410051604/259338755251503104/Capture2.PNG](https://cdn.discordapp.com/attachments/251186294410051604/259338755251503104/Capture2.PNG)
**(Log for Server and Picture - GamersSynergy)**

Log for Singleplayer: [http://pastebin.com/2fjxgmQ1](http://pastebin.com/2fjxgmQ1) **(latest.log - intelic76)** & [http://pastebin.com/cfzhh5YP]( http://pastebin.com/cfzhh5YP) **(latest.log - PaleAntiquarian)**

(P.S. I'm the Creator of the Modpack, [Universal: Interdimensional Escape](https://minecraft.curseforge.com/projects/universal-interdimensional-escape))

**A LOT of People** have been Complaining to me about this Issue, When All I did in the Latest Update was Adding this Ex Nihilo Script, as well as some Mod Changes.

I **Personally am Not able to Reproduce this Issue**. **However**, a lot of People have Informed me of this Issue.

Mod Changes:
- Removed MineTweaker 3 - StanH (Version: 3.0.10B)
- Added CraftTweaker - jaredlll08 (Version: 3.0.13)
- Added ModTweaker2 - jaredlll08 (Version: 0.9.6)
- Updated Better Builder's Wands - Portablejim (Version: 0.6.1, Rev 80 --To--> Version: 0.8.0, Rev 89)
- Updated DecoCraft2 - RazzleberryFox (Version: 2.3.5 --To--> Version: 2.3.6.1)
- Updated Inventory Pets - Purplicious_Cow (Version: 1.4.8.1 --To--> Version: 1.4.9)
- Updated Storage Drawers - jaquadro (Version: 1.10.7 --To--> Version: 1.10.8)

Ex Nihilo Script:
[http://pastebin.com/04eYz0Y6](http://pastebin.com/04eYz0Y6)

(Full Changelog: [https://minecraft.curseforge.com/projects/universal-interdimensional-escape/files/2356123](https://minecraft.curseforge.com/projects/universal-interdimensional-escape/files/2356123))

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported, and stop using MTRM, their folder structure causes crafttweaker  to crash.

**Comment by Wealthyturtle** [comment]
Got it.
