### ISSUE TITLE
The mod wont work!!!

### ISSUE THREAD

**Issue by bob-and-susan** [jaredlll08/CraftTweaker#118]
I decided to start making a mod pack but first I wanted to play with CraftTweaker so I would know how to use it but the only problem is no mater what I do whether I hard code the recipes in myself or use the recipe helper mod it never seems to work. I've tried reloading the scripts or restarting the entire game but it does nothing I would be amazing if you could help me figure out what is going wrong as I am trying to remove the log to plank recipe so I can make my own.

**Comment by jaredlll08** [comment]
The bug report won't work!!!

Mc version?
Crafttweaker version?
Any thing that I can use to identify what versions you are using.
Minetweaker.log file
Scripts file.


On Dec 17, 2016 00:37, "bob-and-susan" <notifications@github.com> wrote:

I decided to start making a mod pack but first I wanted to play with
CraftTweaker so I would know how to use it but the only problem is no mater
what I do whether I hard code the recipes in myself or use the recipe
helper mod it never seems to work. I've tried reloading the scripts or
restarting the entire game but it does nothing I would be amazing if you
could help me figure out what is going wrong as I am trying to remove the
log to plank recipe so I can make my own.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jaredlll08/CraftTweaker/issues/118>, or mute the thread

**Comment by bob-and-susan** [comment]
Minecraft is 1.10
CraftTweaker is latest

Minetweaker.Log
INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO: 
INFO: 
INFO: 
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: minetweaker failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Restoring 0 recipes
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Restoring 0 recipes
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Removing 0 recipes
INFO: Restoring 0 recipes
INFO: Restoring 0 recipes
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Removing 0 recipes
INFO: Restoring 0 recipes
INFO: Restoring 0 recipes
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Removing 0 recipes
INFO: Restoring 0 recipes
INFO: Restoring 0 recipes
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Removing 0 recipes
INFO: Restoring 0 recipes
INFO: Restoring 0 recipes
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Removing 0 recipes
INFO: Restoring 0 recipes
INFO: Restoring 0 recipes
INFO: tried to remove command: entities failed. THIS IS NOT AN ERROR!
INFO: tried to remove command: tooltips failed. THIS IS NOT AN ERROR!
INFO: 
INFO: 
INFO: Removing 0 recipes
INFO: Removing 0 recipes
INFO: Removing 0 recipes
INFO: Removing 0 recipes


Script
// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<minecraft:crafting_table>, [<minecraft:planks:*>, <minecraft:planks:*>, <minecraft:planks:*>, <minecraft:planks:*>]);
recipes.removeShapeless(<minecraft:planks> * 4, [<ore:logWood>]);

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED

**Comment by jaredlll08** [comment]
Dont just tell me latest, never tell me latest, give me the version number.

Also do not use MTRM! Their package structure messed with crafttweaker.

And your scripts are wrong for what you want to do.

**Comment by bob-and-susan** [comment]
im using CraftTweaker-1.10.2-3.0.15

and also I did say I tried it without mtrm and removing mtrm completely from the pack

**Comment by jaredlll08** [comment]
Then your scripts are messed, firstly, the crafting table isn't a shapeless
recipe...
Just out of interest, have you read the wiki?

**Comment by bob-and-susan** [comment]
yes i followed it when I did it without mtrm but only on the planks recipe and it didn't work.

**Comment by jaredlll08** [comment]
Put your scripts on pastebin and the minetweaker.log file please, reading
them here is a huge mission

**Comment by jaredlll08** [comment]
ok so look, there is obviously something wrong with your scripts, if there was a problem with the mod, trust me, I would know about it, I'm closing this as I don't help people fix their scripts, I can't spend my time doing that.
