### ISSUE TITLE
Not hiding JEI items

### ISSUE THREAD

**Issue by BrizzleMFD** [jaredlll08/CraftTweaker#120]
#### Issue Description:
Crafttweaker refuses to hide items from JEI

#### What happens:
Nothing 

#### What you expected to happen:
Gold and diamond armor/tools hidden

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/LgrpTxdG

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/kZXMZbg8

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2185
- Crafttweaker: 1.10.2-3.0.15

#### Your most recent log file where the issue was present: 

fml latest http://pastebin.com/KsHuU4bY

**Comment by belathus** [comment]
As an alternative, you can use JEI's own blacklist config, located at ./minecraft/config/JEI/itemBlacklist.cfg

**Comment by BrizzleMFD** [comment]
Shoot man, thanks completely forgot about that option.

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/CraftTweaker/commit/7f4e59d9df8b8f70702904d80ee72a179f107a22
