### ISSUE TITLE
crash with code 32767

### ISSUE THREAD

**Issue by yggdrasil75** [jaredlll08/CraftTweaker#124]
#### Issue Description:
When I attempt to reload scripts I get Error executing unifying.zs: 32767. I do not know what this means though I think that it means that a mod is trying to override minetweaker.

#### What happens:
oredict entries that I attempt to add do not add.

#### What you expected to happen:
a list of modded stones and woods being added to oredict entries for later usage.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/jCtu4EJ4
http://pastebin.com/63MPgYi8

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/LSicxSPW

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2185
- Crafttweaker: 3.0.16

#### Your most recent log file where the issue was present: 

https://gist.github.com/yggdrasil75/a577742fdd82cbf2a4a9b0a480ee8387

**Comment by drakray** [comment]
have you tried using
oreDict.stoneGranite.add(<undergroundbiomes:igneous_stone:0>);
instead of 
<ore:stoneGranite>.add(<undergroundbiomes:igneous_stone:0>);

repeat for all line

**Comment by jaredlll08** [comment]
@yggdrasil75 could I get a link to MineWorld please

**Comment by yggdrasil75** [comment]
https://minecraft.curseforge.com/projects/mine-world-mod

**Comment by jaredlll08** [comment]
This is an issue with the mine world mod. Nothing that I can do about it.
