### ISSUE TITLE
Recipe removing via /CTGUI 1 is NOT POSSIBLE 

### ISSUE THREAD

**Issue by JAWSAWN** [jaredlll08/CraftTweaker#125]
#### Issue Description:
When doing GUI recipes, I open the gui with /CTGUI 1 then put the item i want to remove recipes of. Then uncheck the "Shaped" button. Then I press the "remove" button. And it doesn't work because it outputs:

recipes.removeShaped(<projecte:item.pe_philosophers_stone>);

thus not working at all. Also remove doesn't even work with Shapeless button.

#### What you expected to happen:
Remove button, when pressed should output this:

recipes.remove(<projecte:item.pe_philosophers_stone>);

instead of "removeShaped" I had to manually correct all of my scripts, please fix this asap.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://pastebin.com/dkw0Lhqu

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.2.2097
- Crafttweaker: CraftTweaker-1.10.2-3.0.16

**Comment by jaredlll08** [comment]
show me a picture of the gui as you had it please

**Comment by JAWSAWN** [comment]
@jaredlll08 
https://gyazo.com/5b2afec422f2048d766d231b52b83205

**Comment by jaredlll08** [comment]
Hmm, no idea, I'll check it out

**Comment by JAWSAWN** [comment]
Maybe you should not have "removeShaped" at all. Make the remove button only output "remove" no matter what. Let the remove button ignore the selection.

**Comment by darkhax** [comment]
Jared could not reproduce this issue. I will try to reproduce it, and if I can confirm we will fix this.
