### ISSUE TITLE
Non-vanilla Recipe Changes Not Displaying

### ISSUE THREAD

**Issue by Ommina** [jaredlll08/CraftTweaker#127]
I just took the opportunity to update CraftTweaker to 3.0.17, and JEI to 3.14.2.401, to take advantage of the recent "let's not reload JEI" changes.

The reduction in the startup time is dramatic.  However, recipes added to mod-based mechanics no longer display.  It does not matter if the mod is supported directly by CraftTweaker, or by the ModTweaker add-on.

So far, I've checked Tinker's Construct, Botania, Immersive Engineering, and AbyssalCraft.

Furnace changes DO display.

The recipes themselves DO work.

/mt reload does not help.

The scripts were working fine this afternoon, so I don't believe they are at fault.  There are no indications of problems in minetweaker.log.  Nor is there anything in the client log, save for "Loading stuff.zs" (seven .zs files, one 'intermod').

I appreciate this could also been a JEI issue, but I can't rollback one without the other, so I'm starting here.  (Edit: reverted to 398 of JEI with no change.)

Many thanks.
____

- Minecraft: 1.10.2
- Forge:  12.18.1.2095
- Crafttweaker: 3.0.17

**Comment by jaredlll08** [comment]
Yea it needs to be fixed both sides. Do me a favour and try this version of MTLib: http://ci.blamejared.com/job/MTLib/7/

**Comment by Ommina** [comment]
It certainly made a difference.

Botania is back.  Tinker's Construct is back.  Blood Magic and Immersive Engineering remain resolute in their awayness.

Environmental Tech is working, although I can't promise that it was not working before too.

**Comment by jaredlll08** [comment]
Yea, here is where the problem lies, I don't add support for those 2,ill
speak to Blu and Way, telling him how to fix it

**Comment by Ommina** [comment]
[AbyssalCraft](https://github.com/Shinoow/AbyssalCraft) is another that is affected.  Shall I create an issue there and point him here?

**Comment by jaredlll08** [comment]
Yea, if you could make an issue on all the bug trackers and point them
here, that would be perfect.

I'll tell then what to do when I get on my laptop

**Comment by Ommina** [comment]
And done, via the magic of some creative copy/paste.

Thank you again to all involved.

**Comment by jaredlll08** [comment]
ok so, for the mod devs coming here, you guys need to implement this line of code in your actions:
https://github.com/jaredlll08/MTLib/blob/master/src/main/java/com/blamejared/mtlib/utils/BaseListAddition.java#L32
without it, jei won't update it's stuff.

**Comment by Ommina** [comment]
I have one "not us!" report back from Blood Magic.

Blood Magic does seem to be part of ModTweaker, which in turn has a "Moved to MTLib" commit comment, so I'm not sure where to go (or what to conclude) from there.

**Comment by jaredlll08** [comment]
Hhm interesting, you sure it doesn't work with the latest Mt lib? If so,
I'll take a look tomorrow

**Comment by Ommina** [comment]
Totally convinced!  I just tried the 1.0.1 (instead of 1.0.0.7) version of MTLib, just in case.  Still no luck.  Tried sneaking up on it in JEI by displaying all altar recipes, but it wasn't having anything to do with that either.

**Comment by jaredlll08** [comment]
Mind passing the minetweaker log for Blood magic?

**Comment by Ommina** [comment]
> INFO: Adding 1 Blood Magic Altar Recipe(s) for <mysticalagriculture:tier1_crafting_seed>
> INFO: Adding 1 Blood Magic Altar Recipe(s) for <mysticalagriculture:tier2_crafting_seed>
> INFO: Adding 1 Blood Magic Altar Recipe(s) for <mysticalagriculture:tier3_crafting_seed>
> INFO: Adding 1 Blood Magic Altar Recipe(s) for <mysticalagriculture:tier4_crafting_seed>
> INFO: Adding 1 Blood Magic Altar Recipe(s) for <mysticalagriculture:tier5_crafting_seed>

I can experiment with some other Blood Magic mechanics if you feel that would be useful.

**Comment by jaredlll08** [comment]
Yea please, also gist me the game log please

**Comment by jaredlll08** [comment]
Fixed the blood magic stuff, will be in next modtweaker release
