### ISSUE TITLE
CraftTweaker-1.10.2-3.0.16 / 17  .reuse() function

### ISSUE THREAD

**Issue by lordchubz** [jaredlll08/CraftTweaker#129]
#### Issue Description:
This is happening in my custom modpack.
I'm using forge-12.18.3.2185
minecraft version 1.10.2

#### What happens:
I had a lot of recipes tweaked to use tools with the .reuse() function so they would not be consumed on the craft.  Which worked in 3.0.15, when I updated to 3.0.17, those recipes started consuming the tools.  I downgraded to 3.0.16 and the same thing kept happening as well.  Once I got back down to 3.0.15 everything worked like normal.

-kingchubz

**Comment by drakray** [comment]
I can confirm, and also, if "reusing" stackable thing, like dye, the whole stack is consumed.
`.anyDamage().transformDamage(1)` do the same, consume whole tool at craft
(3.0.17)

**Comment by davqvist** [comment]
I just found about this as well, reuse(), giveBack() and transformDamage() all don't work. I also found out that using a Tinker's Crafting Station it consumes the item specified to give back and give back every other crafting ingredient item while in a normal crafting table all those items still appear but have a red 0 amount attached to them.

Script to test: http://pastebin.com/QKAsNfi4 and its minetweaker.log http://pastebin.com/UBEiZ9QK

Minecraft 1.10.2
Forge 12.18.3.2202
CraftTweaker 3.0.17
