### ISSUE TITLE
JDK folder

### ISSUE THREAD

**Issue by Techlone** [jaredlll08/CraftTweaker#13]
Can you replace [javaToolsJar](https://github.com/jaredlll08/CraftTweaker/blob/master/configuration.gradle#L8) with value from [original](https://github.com/stanhebben/MineTweaker3/blob/master/configuration.gradle#L9) (also see import)?
Or it a bad idea?

**Comment by jaredlll08** [comment]
Unfortunately, that would crash for me, so it is not possible.

**Comment by Techlone** [comment]
What crash? Maybe I can help with it.

**Comment by jaredlll08** [comment]
I can't remember the crash, it was about me not having something, but
considering I was the only one working on it at the time, I just hard-coded
my jdk into it

**Comment by Techlone** [comment]
> it was about me not having something

Looks like you forgot write `import javax.tools.ToolProvider` in the begin of the cfg file.
Can you test it again please? When you will have time. Thanx.

**Comment by jaredlll08** [comment]
Nope, I remember it had the import, it was on a fresh copy from original
repo

**Comment by Techlone** [comment]
Sadly, especially without a crash report...
So, do you test it again to get the report?

**Comment by Gideonseymour** [comment]
THIS IS NOT A VALID CRasH REPORT @jaredlll08

**Comment by jaredlll08** [comment]
```
Working Directory: C:\Users\Jared\Documents\Github\MineTweaker3\MineTweaker3-MC19-Main
Gradle User Home: C:\Users\Jared\.gradle
Gradle Distribution: Local installation at C:\Program Files\gradle-2.10
Gradle Version: 2.10
Java Home: C:\Program Files\Java\jre1.8.0_74
JVM Arguments: None
Program Arguments: None
Gradle Tasks: runClient

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Jared\Documents\Github\MineTweaker3\configuration.gradle' line: 9

* What went wrong:
A problem occurred evaluating script.
> Cannot invoke method getURLs() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.343 secs

```

I have the import and everything else.

**Comment by jaredlll08** [comment]
So @Techlone got anything?

**Comment by Techlone** [comment]
Oops I forget about this issue... I googled something.
1. Your JDK has not been properly/completely installed and you have not `javax.tools` package.
2. Need to check JAVA_HOME env. variable. Maybe gradle can't find the package.

**Comment by jaredlll08** [comment]
1. I can manually find the tools.jar file, by using the manual path, it works perfectly
2. Gradle would give issues if my JAVA_HOME was messed
