### ISSUE TITLE
Game is in a Frozen Data State (There are NO FOLDERS in scripts\)

### ISSUE THREAD

**Issue by Wealthyturtle** [jaredlll08/CraftTweaker#131]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

Game is in a Frozen Data State, Causing Worlds to Not Load.
NOTE: There are NO FOLDERS in scripts\.

#### What happens:

Game is in a Frozen Data State, Causing Worlds to Not Load.

#### What you expected to happen:

The Game Not to be in a Frozen Data State.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

Partial fml-client-latest.log: [https://gist.githubusercontent.com/Wealthyturtle/7aaef6cf94dd44dfc7fea5ece82a2ddc/raw/13e1869b5d4c66ac795290089d58ea867964e40c/Partial%2520fml-client-latest.log](https://gist.githubusercontent.com/Wealthyturtle/7aaef6cf94dd44dfc7fea5ece82a2ddc/raw/13e1869b5d4c66ac795290089d58ea867964e40c/Partial%20fml-client-latest.log
)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

Minetweaker.log: [https://gist.githubusercontent.com/Wealthyturtle/a387074368895ea27d094b3c1aa501fb/raw/eb9de7191277ab2cae13aa34645a1776257023c0/Minetweaker.log](https://gist.githubusercontent.com/Wealthyturtle/a387074368895ea27d094b3c1aa501fb/raw/eb9de7191277ab2cae13aa34645a1776257023c0/Minetweaker.log
)

#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Crafttweaker: 1.7.10-3.0.13

#### Your most recent log file where the issue was present:

latest.log:
[https://gist.githubusercontent.com/Wealthyturtle/c0ba8b209e331a2c5f6cc9713974cef3/raw/852dd49d0e352efd818e62760c2406f7be1731a2/latest.log](https://gist.githubusercontent.com/Wealthyturtle/c0ba8b209e331a2c5f6cc9713974cef3/raw/852dd49d0e352efd818e62760c2406f7be1731a2/latest.log)

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.
