### ISSUE TITLE
[1.10.2] Getting Disconnected from Servers

### ISSUE THREAD

**Issue by MrAmericanMike** [jaredlll08/CraftTweaker#133]
#### Issue Description:
So yes, this does happens on a ModPack, but I'm one of the creators of the ModPack and we don't know what to do. As it is random and we tried a lot of different scripts combinations.

#### What happens:
Players get kicked from server on logging, randomly (Some of them all the time, some of them in random occasions)

#### What you expected to happen:
Players should be able to log normally

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/xB46uXK4
(We have also tried different combinations, on separate files, putting all in one, removing all projecte stuff. Still same issues

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
Server: https://gist.githubusercontent.com/MrAmericanMike/08520ac4900ff72b019e252bec929b35/raw/0ea0db627b13153592036d2848a93fb1d1502c3d/Server

Client: https://gist.githubusercontent.com/MrAmericanMike/08520ac4900ff72b019e252bec929b35/raw/0ea0db627b13153592036d2848a93fb1d1502c3d/Client

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 1.10.2-3.0.17

#### Your most recent log file where the issue was present: 

I believe that's the Client I posted above?

**Comment by MrAmericanMike** [comment]
Let me add, the player having issues can connect over and over on the server we have without the projecte recipes, but only after restarting the whole minecraft, if he disconnects and try to log again, he gets kicked.

**Comment by jaredlll08** [comment]
Pastebin or gist. Nothing else please. (those are the best on mobile imho)

**Comment by MrAmericanMike** [comment]
Ok moved the Client and Server to a Gist:
https://gist.github.com/MrAmericanMike/08520ac4900ff72b019e252bec929b35

(PS: Apparently it say that the Server one has to be shown raw for it been too large, but its there) https://gist.githubusercontent.com/MrAmericanMike/08520ac4900ff72b019e252bec929b35/raw/0ea0db627b13153592036d2848a93fb1d1502c3d/Server

**Comment by jaredlll08** [comment]
Either those are truncated or there I can't see a single thing wrong with it :/

**Comment by MrAmericanMike** [comment]
On Single player they all load with no problem at all, same on the server, but when certain players log they get kicked.

I don't know if redoing the scripts would help, as any error on them should cause the script to fail at load even when trying on Single Player.
Will wait till next release of the pack and if the problem persists I will post again.
Most weird thing is that when closing the client and launching the whole pack again, you can log, but if you log out to main screen, and try to get back in, most the time you get kicked.

**Comment by jaredlll08** [comment]
You don't happen to have extra scripts on the server? Like are the scripts
on the client exactly the same?

**Comment by MrAmericanMike** [comment]
I believe in one of the servers they added a script to remove the chunk loaders recipes.
But I did some test logging into the server with my script folder empty and I was able to log.

**Comment by jaredlll08** [comment]
Well I just want to make sure they are the same, also is it all the users?
Or just people with a bad connection? Have you actually tried this without
crafttweaker?

**Comment by MrAmericanMike** [comment]
Yes we tried all combinations. No CraftTweaker/ModTweaker/MtLib and he can connect no problem.
We add the mods back, he can connect no problem.
We add the 16 Scripts files, he gets kicked.
We randomly remove some of the scripts file and as soon as we go over 6 or 7 files, he gets kicked.
I made all the scripts into 1 file, he gets kicked.
Then we tried all scripts in 1 file, but removing all the projectE recipes and he can connect and doesnt get kicked (He does get kicked if he logs out and logs again not restarting the whole client)
At that point I give up and we stopped testing :P 
But all the same scripts back in the previous version with older version of CT and MT we had no issues. For some reason when we did this update people had problems, first we spotted a mod and removed it, and then we were recommended to update JEI, CraftTweaker, ModTweaker and to include MTLib.

**Comment by jaredlll08** [comment]
Hhm, interesting, I'll take another looks at the logs then, did you happen
to find which script line exactly is the problem? Also what is the error
message when he connects again?

**Comment by MrAmericanMike** [comment]
He gets the "A fatal error has occurred, this connection is terminated"
It did that even to me on some of the test, that's why I say it's totally random.

Related to the scripts, dunno as they all load fine on Single Player. I dont want to blame the Projecte scripts, as I believe that's not the problem, but maybe the amount of scripts in total, not sure.

PS: If you want to take a look at the scripts in the pack itself, it's the Nameless Pack on the ATLauncher. Version 0.0.3.2 ;)

Thanks a lot for your patience and dedication.

**Comment by MrAmericanMike** [comment]
On this old post, they report similar issues and the solution is kinda similar to what we have been experiencing, having to close the client in order to connect (Even when it works for only one of the servers where we doing the tests and only after removing some scripts)

https://minecraft.curseforge.com/forums/modpack-discussions/official-modpack-threads/jadedcats-packs/agrarian-skies-2/questions/server-questions/947-a-fatal-error-has-occured-this-connection-is

**Comment by jaredlll08** [comment]
Pass me the Minetweaker.log file please

**Comment by MrAmericanMike** [comment]
Gonna see if the player getting kick has it and post it here ;)

**Comment by MrAmericanMike** [comment]
This is the file:

http://pastebin.com/JJ7X5hvM

Now looking at this, 1 idea comes to my mind, I'm adding recipes to tinkers smeltery, without removing them first, because old Tinkers don't have those. Maybe newer Tinkers added it and that's an issue?

Gonna investigate that, but let me know if you find anything ;)

Thanks

**Comment by jaredlll08** [comment]
Adding recipes without removing them first *should* work fine...
I'm going to take another look at this, honestly not even sure why I closed it in the first place.

**Comment by jaredlll08** [comment]
hhm, any chance I could get a fresh game log with the "A fatal error has occurred, this connection is terminated" error please, and upload it wherever this time, not on mobile and I have a feeling that gist may not be getting all of it

**Comment by MrAmericanMike** [comment]
I removed the Tinkers recipes from the .zs files as the newer versions of Tinkers already smelt armor into liquid metals on the smeltery.
I don't think the message a fatal error.... was shown on the console it was just the message showing on the game window when the player gets disconnected.
Next week we going public with this update with the recipes removed I will have more news about this problem by then. Hopefully the changes I made fixes the issue. Will keep you informed ;)

**Comment by jaredlll08** [comment]
So it works fine without the tinkers recipes?

**Comment by MrAmericanMike** [comment]
Not sure yet, we haven't had the opportunity to check on a server yet.

**Comment by MrAmericanMike** [comment]
A new player is trying now, here is the console on when he gets kicked.
https://gyazo.com/8da7e86e7e9e0abc1f9d7e2992131922
and the ingame message
https://gyazo.com/cad65cdf83c8852c9241599798bc0cea

He will do some more tests. Like removing Craft Tweaker and see how it goes.

**Comment by MrAmericanMike** [comment]
So, I didnt though my PC was going to be able to handle it, but I just created a server and connected to it using the newer version of the pack that will go public SOON™
I will close the issue as for now, if when we go public people have connection issues we will investigate deeper and open the issue again if necessary ;)

**Comment by jaredlll08** [comment]
hhm, so 2 things.

1) Can you reproduce the error on a remote server?
2) Can you reproduce the error on a local server?

**Comment by MrAmericanMike** [comment]
I sent the new version to the person that was crashing on the previous version. He ran the server and logged with the old build of the pack on his PC and got kicked.
He did the same test with the new version where we updated some mods and other stuff, he isn't getting kicked now.
Honestly not sure what the issue was and how we fixed it, because I asked him to add again the tinkers.zs to see if that was the issue, and when he adds it on the newer version he isn't getting kicked.
Hopefully we wont have this problem anymore, but I'm intrigued about not been able to discover what exactly the cause of this problem was.

**Comment by jaredlll08** [comment]
I honestly think that this is a connection error, or that your server isn't strong enough to handle it (I noticed a lot of tick skipping in your log)

**Comment by MrAmericanMike** [comment]
Well on my logs I noticed that also, but I'm not getting kicked. I runned server and client on same PC just for the tests. Final result will come when we go public with this version and we run the pack on the sub-server. I have my fingers crossed :D
