### ISSUE TITLE
Calculator JEI Recipes not working

### ISSUE THREAD

**Issue by davqvist** [jaredlll08/CraftTweaker#136]
#### Issue Description:
So, I noticed that after recent updates, JEI doesn't show changed Calculator recipes anymore even though the recipes work. I tested around a little bit and noticed that the latest CraftTweaker update breaks it, with 3.0.16 everything seems to work fine, but with 3.0.17 JEI doesn't show the recipes anymore. I already let the Calculator dev know as he did the CraftTweaker integration himself as I can see, but as the CraftTweaker update broke it (as I just found out), I want to you let know. Maybe you can figure out what's wrong and if necessary contact Ollie Landsdell if he has to change something to make it work again.

#### What happens:
Calculator recipe changes don't show up in JEI anymore, neither removed recipes are removed, nor added recipes are added even though the recipe changes work.

#### What you expected to happen:
That JEI reflects those changes

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/yzVdHrLj
(for adding the recipe you need Immersive Engineering)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/QcWu0exh

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Crafttweaker: 3.0.17
- Calculator: 3.1.5
- SonarCore: 3.2.0
- JEI: 3.14.2.401

#### Your most recent log file where the issue was present: 

https://gist.github.com/davqvist/0b70ef21c4a43769692e459047411747

**Comment by jaredlll08** [comment]
Post to Calculator github. The Minetweaker API changed and now mods need to update.
