### ISSUE TITLE
Crash with Simple Upgrades and Tooltips

### ISSUE THREAD

**Issue by Renari** [jaredlll08/CraftTweaker#138]
#### What happens:
Attempting to take Rotten Leather from the crafting table crashes the client.
![Rotten Leather](https://vgy.me/AYFINt.png)

This only happens when connected to the server, where other strange occurrences also happen with this mod. 

![Tooltip Error](https://vgy.me/0TKdVY.png)

This also only happens on a server and I assume it is related.

#### What you expected to happen:
Being able to take the crafted item from the table without any issues.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
N/A

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
N/A

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Crafttweaker: 3.0.17

#### Your most recent log file where the issue was present: 
From crafting table:
https://openeye.openmods.info/crashes/dffb8f1fda9bc3a7d5e1d914b60aff45
From JEI tooltip:
https://gist.github.com/Renari/51f6b08951c9bf0abf46639f9fbf9f3f

**Comment by jaredlll08** [comment]
Does it still mess up JEI if Crafttweaker is not installed?

**Comment by Renari** [comment]
Yes, removing CraftTweaker fixes the issue.

**Comment by jaredlll08** [comment]
do me a favour and run /mt hand when holding the rotten flesh

also do you have any scripts and could I get the minetweaker.log please

**Comment by Renari** [comment]
/mt hand outputs:
    <minecraft:rotten_flesh>

mintweaker.log:
https://gist.github.com/Renari/0023b83428e5ef776d4c3ec443320339

scripts:
https://gist.github.com/Renari/e4892446d61926c134ce88921b63452c

The second script requires [ExtraTweaker](https://minecraft.curseforge.com/projects/extratweaker).

**Comment by jaredlll08** [comment]
and you are holding the rotten flesh from Simple Upgrades correct?

**Comment by Renari** [comment]
The recipe uses vanilla rotten flesh. Are you referring to the rotten leather that is made by the recipe?

**Comment by jaredlll08** [comment]
yes.

**Comment by Renari** [comment]
I was unable to get this item on the server without crashing, upon further investigation I missed installing the Simple Upgrades mod on the server. Sorry for wasting your time.
