### ISSUE TITLE
Bug Report: JEI recipes not loading up with ModTweaker Scripts

### ISSUE THREAD

**Issue by EmoKiba** [jaredlll08/CraftTweaker#140]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
JEI recipes arent showing up for my custom modtweaker (version 2.0.9) recipes. However when reverting back oen version down (3.0.1.6) shows the recipes back when on version(1.0.0) of MTlib but then the Extra Util 2 version (1.1.2) recipes dont show up in JEI. Noted though the recipes from latest version do work on EXU2 except for the ones that involve XP to craft ie (lasso, magical wood) 

#### What you expected to happen:
For the ModTweaker Recipes to Show up in JEI and for the EXU2 recipes to show up as well.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/d0vmqykc

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 3.0.17

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Update to latest version of Modtweaker, Mt lib AND JEI, JEI has to be on
version 398 or above.

**Comment by EmoKiba** [comment]
when updated the error still occurs

**Comment by jaredlll08** [comment]
Mind giving me the game log please.

**Comment by EmoKiba** [comment]
FML Latest Log : https://www.dropbox.com/s/f2c92y611ca2ss5/fml-client-latest.log?dl=0
Pastebin says its too large

**Comment by jaredlll08** [comment]
wait a minute, on the latest version, what doesn't show exactly?

**Comment by jaredlll08** [comment]
Could you please answer my question.

**Comment by EPIICTHUNDERCAT** [comment]
Hello Jared sorry for the delayed response, what's not showing up is the tinker recipes that we added.

**Comment by jaredlll08** [comment]
ok yea, that is an issue for Modtweaker and has been fixed by the latest modtweaker commit.

**Comment by EPIICTHUNDERCAT** [comment]
So this is not released yet right? its just on github?

**Comment by EPIICTHUNDERCAT** [comment]
thank you
