### ISSUE TITLE
Can't remove something from OreDictionary in 1.10

### ISSUE THREAD

**Issue by Eufranio** [jaredlll08/CraftTweaker#141]
I'm trying to remove the Uranium dust and ingots from Immersive Engineering from the ore dictionary, since people are using it instead the IC2 uranium in craftings. That's what I did in my script:
```
<ore:dustUranium>.remove(<immersiveengineering:metal:14>);
<ore:ingotUranium>.remove(<immersiveengineering:metal:5>);
recipes.remove(<immersiveengineering:metal:5>);
recipes.remove(<immersiveengineering:metal:14>);
```
And it is still usable in craftings using the dustUranium and ingotUranium oredict entries. Also, in-game pressing shift and looking for the ingot, it shows that it is in the oredict "ingotUranium". 

- Minecraft  1.10.2
- Forge 12.18.3.2202
- Crafttweaker: 1.10.2-3.0.17

Modpack: http://www.technicpack.net/modpack/magibeta-pack.940049

**Comment by jaredlll08** [comment]
You are meant to follow the template fully! I am not downloading your pack just to test this.

**Comment by Eufranio** [comment]
so?
Simply try to remove something from oredictionary, that's the issue. I just said what I was trying to do with this...

**Comment by jaredlll08** [comment]
If you look at the updated ISSUE_TEMPLATE.md you will see why I both closed and locked this.
https://github.com/jaredlll08/CraftTweaker/blob/master/ISSUE_TEMPLATE.md

You are free to open up a new issue using the Template and I will be happy to help you then.
