### ISSUE TITLE
CraftTweaker not working with new MC launcher beta?

### ISSUE THREAD

**Issue by mightydanp** [jaredlll08/CraftTweaker#143]
#### Intro:
when i use a script or even reload it ingame nothing changes and it doesnt load any of my scripts. Is there something new?

#### Issue Description:
I am trying to get some of my older scripts to work. after updating to the latest version non of the scripts seem to load at all

#### What happens:
when i look at the minetweaker log it is blank, and when i look into the console i dont see any of my files loaded.
all i can see is this

4:14:40 PM	STDOUT	Server thread	info	[minetweaker.runtime.MTTweaker:load:106]: Loading scripts
4:14:41 PM	STDOUT	Server thread	info	[minetweaker.runtime.MTTweaker:load:153]: MineTweaker: Loading intermod

#### What you expected to happen:
It to load my scripts. my scripts are in the scripts folder.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/xNRRY0PH

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

the minetweaker file is blank even though the mod is loaded:/ and even if i reload with /mt reload it wont reload anything or print anything in the log file
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2185
- Crafttweaker: 3.0.17

#### Your most recent log file where the issue was present: 
had to upload it to my dropbox because it was to big for pastebin
https://www.dropbox.com/s/0cp0hc0qlq4lwca/launcher_log.txt?dl=0
[pastebin/gist/etc link here]

**Comment by mightydanp** [comment]
Update. After switching from minecrafts new launcher to the old it started to work >.>

**Comment by jaredlll08** [comment]
Which new launcher?

How are you launching the game?

**Comment by mightydanp** [comment]
The new launcher thats going to replace the one we use right now
https://www.reddit.com/r/Minecraft/comments/59b7m0/help_us_test_the_new_minecraft_launcher_check_the/

**Comment by darkhax** [comment]
Further testing is needed. Once I have access to the launcher I will be able to do some tests. It's very possible this could be a much larger issue than just CrT.

**Comment by jaredlll08** [comment]
I can't reproduce
