### ISSUE TITLE
Old scripts that worked for Minetweaker 3 on 1.7.10 do not work on CraftTweaker for 1.10.2.

### ISSUE THREAD

**Issue by noswanson1982** [jaredlll08/CraftTweaker#144]
Scripts that used to work for Minetweaker 3 with 1.7.10 do not work for Craft Tweaker.

#### WHAT HAPPENS IS THIS:
I get error messages, and nothing works.

#### What is supposed to happen

If working properly, a player is supposed to be able to take items in inventory (in the above example, iron horse armor, and be able to put it in the furnace and "recycle" it down to 1 iron ingot.  

My script file:
https://gist.github.com/noswanson1982/0ec77eae491d501ad4d48746efdfa221.js

My minetweaker log file:
https://gist.github.com/noswanson1982/ac92dd447bca19ce54580c31da3680f8.js

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: forge 1.10.2-12.18.3.2185
- Crafttweaker: CraftTweaker-1.10.2-3.0.17

#### Your most recent log file where the issue was present: 
https://gist.github.com/noswanson1982/13d4ea5a20febcff1120e74d98d46b73.js

**Comment by jaredlll08** [comment]
Please don't upload the files like you did. 

Also update JEI.
