### ISSUE TITLE
Crafttweaker crashes world on start up

### ISSUE THREAD

**Issue by Cazadorsniper** [jaredlll08/CraftTweaker#148]
#### Intro:
When generating a world the pack I'm working crashes.
Tried new and old worlds.
I have not made any scripts manipulating mob drops.

#### Issue Description:
The pack errors as soon as I join the world and outputting something about mob drops. Maybe either too many entities or Epic Siege Mod's chaos mode (which causes mobs to attack each other). 
Versions: 3.0.18 and 3.0.19 does this.
#### What happens:
Crash as soon as I joined the world

#### What you expected to happen:
I expected to join the world fine as i done in the past.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/dz7rgyD0 

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://pastebin.com/hJsuWdXh

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Crafttweaker: 3.0.19

#### Your most recent log file where the issue was present: 

http://pastebin.com/x1t569ku (crash report)

**Comment by jaredlll08** [comment]
Update to 3.0.20.
https://minecraft.curseforge.com/projects/crafttweaker/files/2373863
