### ISSUE TITLE
Console Warnings; A lot of em. 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [jaredlll08/CraftTweaker#149]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the minetweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

https://gist.github.com/P3rf3ctXZer0/e2a0bbee5affeba2d88faf53dca0814f

#### What happens:

Console warnings; many of them.

#### What you expected to happen:
No console spam.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
None. I don't have any active scripts at this time.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/P3rf3ctXZer0/c9b5e81541e1fdde8c12aa17bcaa92f7
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 221
- Crafttweaker: U-CraftTweaker-1.10.2-3.0.20 

#### Your most recent log file where the issue was present: 
https://gist.github.com/P3rf3ctXZer0/d8a871d99f7de6bba9a93ad24df38dac

**Comment by jaredlll08** [comment]
I need the scripts you are using please
