### ISSUE TITLE
Recipe removal fails, incorrect behavior on reuse(), others

### ISSUE THREAD

**Issue by RiverC** [jaredlll08/CraftTweaker#150]
#### Issue Description:
1. Removing recipes does not function.
2. Items which are part of a recipe and have .reuse() may be consumed.

#### What happens:

1. When I add a line to a script in the scripts folder such as

`recipes.removeShaped(<minecraft:planks:0>);`

Minetweaker log says

INFO: Removing 0 recipes

2. The recipe 

```
val flint_axe = <tconstruct:axe_head>.withTag({Material: "flint"}).onlyWithTag({Material: "flint"});
recipes.addShapeless(<minecraft:planks:0>*2,[<minecraft:log:0>,flint_axe.reuse()]);
```

Consumes the axe_head item with each use. This affects both Tinker's Crafting Stations AND Minecraft Crafting tables.

#### What you expected to happen:

1. INFO: Removing 1 recipes 

2. Axe head remains in crafting grid.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
1. https://gist.github.com/RiverC/1551f5aadeb801744e9b09ecd2eca576
2. https://gist.github.com/RiverC/8818993509de576dd81e65bf116ec09a

#### Minetweaker.log file 

https://gist.github.com/RiverC/a26ca0b67f920dc11efea2323b31f2e0
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 110.2
- Forge: 12.18.3.2185
- Crafttweaker: 3.0.20

#### Your most recent log file where the issue was present: 

https://gist.github.com/RiverC/d32c190ae4a5fd99433e05b0086882eb

Here is an error that forge produced on load, which may or may not be directly relevant:

https://gist.github.com/RiverC/c25300e17f0b0f7d41ada0c2719c7937

Note, I've just dumped the files as you asked. There's a lot of extra stuff in there, but since you've threatened to close the issue if I don't, you'll have to deal with it. Cheers!

**Comment by RiverC** [comment]
Update: I can confirm that you can remove recipes IF you specify them exactly 

recipes.removeShaped(<minecraft:planks:0>*4,[[<minecraft:log:0>]]);

Works.

But the wiki you cite states that removing "any" recipe for that item should work. I tried downgrading to 3.0.16 and got the same result, so I stripped off every mod but Crafttweaker, and all of my scripts except for one line. The result was that the recipe would not disappear until I specified it exactly.

Rolling back to 3.0.13 solves the problem, and I can again remove a recipe without specifying the exact recipe.

**Comment by jaredlll08** [comment]
Do not put more than 1 bag report in a single issue.

**Comment by RiverC** [comment]
I'm going to fork it then, thanks for nothing.
