### ISSUE TITLE
Removing recipes by result does not function.

### ISSUE THREAD

**Issue by RiverC** [jaredlll08/CraftTweaker#151]
Issue Description:

Removing recipes does not function.

When I add a line to a script in the scripts folder such as
recipes.removeShaped(<minecraft:planks:0>);

Minetweaker log says

INFO: Removing 0 recipes

What you expected to happen:

INFO: Removing 1 recipes

Script used

https://gist.github.com/RiverC/1551f5aadeb801744e9b09ecd2eca576

Minetweaker.log file

https://gist.github.com/RiverC/a26ca0b67f920dc11efea2323b31f2e0

Affected Versions 

Minecraft: 110.2
Forge: 12.18.3.2185
Crafttweaker: 3.0.14-3.0.20
Your most recent log file where the issue was present:

https://gist.github.com/RiverC/d32c190ae4a5fd99433e05b0086882eb

Here is an error that forge produced on load, which may or may not be directly relevant:

https://gist.github.com/RiverC/c25300e17f0b0f7d41ada0c2719c7937

Note that this works fine in 3.0.13.

**Comment by jaredlll08** [comment]
So this is not actually a bug, the output you were getting on 3.0.13 was actually a bugged output, it was removing a recipe when it shouldn't have.

Planks don't have a "shaped" recipe, the only recipe for planks is a single log, and that recipe is shapeless, so if you change the recipe to:
```
recipes.remove(<minecraft:planks>);
```
You will notice that the recipe will be removed

**Comment by RiverC** [comment]
Incorrect. The recipe for Minecraft's planks IS shaped. Biomes o'plenty is shapeless.

I tried this with BOTH shaped and shapeless and neither worked. The recipe removal that works is specifying a shaped recipe WITH ingredients. According to the minetweaker 3 wiki, you should not need to specify the ingredients of a recipe to remove it, only the outputs, and it will automatically drop any recipe that is (shaped, shapeless, mirrored) with that output, regardless of the number of resulting items.
