### ISSUE TITLE
Removing shaped and shapeless recipes not functioning since 3.0.13

### ISSUE THREAD

**Issue by RiverC** [jaredlll08/CraftTweaker#153]
# Issue Description:

Removing recipes does not function.

# What happens:

When I add a line to a script in the scripts folder such as
recipes.removeShaped(<minecraft:planks:0>);
recipes.removeShapeless(<minecraft:planks:0>);

Minetweaker log says

INFO: Removing 0 recipes
INFO: Removing 0 recipes

Neither the shaped nor shapeless recipe is removed.

# What you expected to happen:

INFO: Removing 1 recipes
INFO: Removing 0 recipes

OR

INFO: Removing 0 recipes
INFO: Removing 1 recipes

(the recipe for planks to be removed, whether it is shaped or shapeless.)

# Script used

https://gist.github.com/RiverC/d8fa7453eaac7294bd65b0476e4b3b91

# Minetweaker.log file

https://gist.github.com/RiverC/5d3d8dfead4ee381854244aaad2989cb

# Affected Versions

Minecraft: 110.2
Forge: 12.18.3.2185
Crafttweaker: 3.0.14-3.0.20

# Your most recent log file where the issue was present:

https://gist.github.com/RiverC/a42651b5dd056b1413b833b5c1df3e0b

Note that this works fine in 3.0.13.

**Comment by belathus** [comment]
I'm getting this same issue. No recipes are removed from any of my scripts, which breaks the whole progression system that we setup in this pack. Yay.

**Comment by jaredlll08** [comment]
Its weird since not many people have reported the issue :/ I'll  take a look at it later today and just revert the changes

**Comment by RiverC** [comment]
I did some further inspection later, and it seems that you did fix _something_ from 13 to 14; when I removed one glass pane recipe it removed all even though I specified the specific recipe (in 13.) But after, I can only get it to remove recipes by specifying them exactly, and... I discovered I can't remove the recipes for Biomes O' Plenty planks no matter how I express the recipe. 

So something is up with how it's identifying recipes to remove...

**Comment by jaredlll08** [comment]
I could have sworn that I reverted the commit from Release 14, anyway, this one *should* work, mind testing it for me? http://ci.blamejared.com/job/CraftTweaker-Dev/16/

**Comment by RiverC** [comment]
I'll give it a whirl tonight.

**Comment by RiverC** [comment]
It looks good. I can remove BoP planks and this gives a good result

`recipes.removeShaped(<minecraft:planks:*>);`

`[SERVER_STARTED][SERVER][INFO] Removing 12 recipes`

**Comment by sab0tic** [comment]
I've been on v3.0.20.17 and have been experiencing the same issue. Just wanted to drop in and say that updating to the build linked above (http://ci.blamejared.com/job/CraftTweaker-Dev/16/) completely resolved the problem for me as well.

i am new to using CraftTweaker so i automatically thought it was something i was doing wrong. i would've wasted a ton of time! huge thank you to RiverC for opening this issue, and to jaredlll08 for fixing it :)

**Comment by jaredlll08** [comment]
Ok cool! I'm going to close it, this will be in the next release, until then, please do not distribute that test version
