### ISSUE TITLE
Add support for JEI descriptions

### ISSUE THREAD

**Issue by Eufranio** [jaredlll08/CraftTweaker#154]
I would like that a "Description" option be implemented. JEI has the feature of show text in the GUI, so adding text there via Script may be usefull...

**Comment by al132** [comment]
I could be misunderstanding you, but I think the feature you're looking for already exists http://minetweaker3.powerofbytes.com/wiki/Tutorial:Tooltips

**Comment by jaredlll08** [comment]
Nope, he would like JEI pages with just text, like ExtraUtilities had in 1.7.

I have other stuff I need to work on, but I am hoping that I can implement this at some point

**Comment by darkhax** [comment]
Can do :)

**Comment by Tylian** [comment]
Any update on this? I was thinking about how I'd love to hook into JEI's Descriptions recently to explain some of the less intuitive item uses in a modpack, and did a quick search and found this.
