### ISSUE TITLE
Suggestion: Adding block properties editing to ZenScript

### ISSUE THREAD

**Issue by grundyboy34** [jaredlll08/CraftTweaker#155]
#### Intro:
Something that doesn't easily exist currently is a way for users to edit the properties of blocks, especially in 1.10.2   

#### Issue Description:
Ideally, ZenScript could be extended to allow us to do something like Block.setHarvestLevel(<minecraft:log>, 2)  or even use ore dictionaries so that every block under that entry would get the function ran as well. Ex: Block.setHarvestLevel(<ore:logWood>, 2).
This could be used to edit all properties of blocks, from harvestLevel to flammability

**Comment by darkhax** [comment]
Once I familiarize myself with the current API I will look into what is possible. Due to the way MineTweaker scripts are processed, some block properties may not be feesable. Others are though.

**Comment by kindlich** [comment]
Even though this issue is a bit old, if you really need something to change block properties, you could use [ExtraTweaker](https://minecraft.curseforge.com/projects/extratweaker) a minetweaker/crafttweaker addon

**Comment by jaredlll08** [comment]
Flammability isn't easily settable.
