### ISSUE TITLE
IC2 Compressor Support

### ISSUE THREAD

**Issue by Lgk2** [jaredlll08/CraftTweaker#157]
#### Issue Description:
Adding recipe to ic2 compressor doesn't work.

#### What happens:
No recipe is added.

#### What you expected to happen:
Recipe to be added.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/Lgk2/a08fff5fee4865dc786606d6c14903f3

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/Lgk2/6cfccb8929e761f0ba13768b3eced01c
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Crafttweaker: 1.10.2-3.0.20

#### Your most recent log file where the issue was present: 

https://gist.github.com/Lgk2/65b1cc7119d4adf8b16eba7a20f7bad4

**Comment by MasterGeneral156** [comment]
I've found that it IS added, but not showing in JEI. I don't know who'd be at fault here, JEI or CT.

**Comment by Saereth** [comment]
Can confirm, same version number of CT and MT, 
running forge 1.10.2 - 12.18.3.2234 
JEI version 3.14.6.412

ic2 recipes in the compressor and plate bending machine arent showing for me, rockhounding as well. The recipes do work however.

**Comment by bookerthegeek** [comment]
Just saying, until this gets fixed, you know ic2 has a built in way to modify almost all of the recipes used in machines right? Extract the recipes from the jar, and put it in config/ic2/*.cfg

**Comment by Lgk2** [comment]
Can you guys post your scripts in which you compress gold into gold blocks or lapis into lapis blocks because IC2 doesn't allow me to even put the materials in the compressor so it doesn't work for me at all. Is there's something wrong with my script maybe?

**Comment by MasterGeneral156** [comment]
http://pastebin.com/7x8FpUVH

**Comment by darkhax** [comment]
This is likely an issue with IC2's JEI support, and the way CrT handles the loading of scripts. I will do further testing to see if that is the case, and make sure reports get to the right place.

**Comment by MechanosG** [comment]
This sounds like the same issue I'm having.  Unless I'm doing something wrong.
This is what I'm attempting to do.

`
import mods.ic2.Compressor;

val cobble1 = <extrautils2:compressedcobblestone>;
val cobble2 = <extrautils2:compressedcobblestone:1>;
recipes.remove(cobble1);
recipes.remove(cobble2);
Compressor.addRecipe(cobble1, <ore:cobblestone> * 9);
Compressor.addRecipe(cobble2, cobble1 * 9);
`
I have similar code for the rest of the compressed blocks in extra utilities, trying to make them use the ic2 compressor in a GT modpack (which I assume GT in turn loads, kinda wish I would have found that pastebin link before I made all this lol).  The recipes remove correctly, and I can't find any errors.  But the new compressor recipes don't show up in in JEI.  I haven't tested to see if they actually work or not, but after reading this page I bet they do and just aren't visible.

@bookerthegeek Can you use that method to add recipes using items from other mods?  And if yes, would you mind posting an example for us to use as a workaround 'till this is fixed?

**Comment by bookerthegeek** [comment]
Yes you can, it is a bit of a pain. 

- Use 8zip to open the ic2 jar
- taje the machine.ini folders and place them in `.../config/ic2/`
- Edit configs in that folder.
- You have to create the icw folder.

I can post an example for you tonight.

**Comment by MechanosG** [comment]
Cool.  Thank you, much appreciated.  I'll take a stab at it in the meantime.

**Comment by Lgk2** [comment]
Ah thanks for the guides @bookerthegeek and @MechanosG I doubt I'll go back to editing ic2 machines with minetweaker even if they fix this issue.

**Comment by bookerthegeek** [comment]
While i love minetweaker and its derivatives / addons, i always prefer to use built in methods. It can be a pain sometimes to find out how to do so.

Would love to see your machine configs. Pastebin them and link them please?

**Comment by jaredlll08** [comment]
I also have to agree on this, IC2 was grandfathered in, I always recommend
that you use built in methods, this is why EIO doesn't have support, it
already has build in methods for recipes

**Comment by Lgk2** [comment]
@bookerthegeek Well it's not especially interesting as of right now but it's a small step towards making a very difficult mod-pack, the step involves forcing players to compress blocks in the compressor instead of in a shaped crafting recipe. I'm probably going to add these recipes to other compressors like the new TE compressor. This is the only ic2 machine recipe I've changed since I'm not sure in what order machines will be acquired and what they'll be used to unlock.

https://gist.github.com/Lgk2/f743df6045ae055b48f5f4d6f8fd0b97

**Comment by bookerthegeek** [comment]
No worries, i juat like having examples to look over. I'll ping you when I get mine done.

And thank you.

**Comment by MechanosG** [comment]
@bookerthegeek 
I didn't bother copying the entire file but here ya go.  To anyone wanting to use this, just paste this at the end of your compressor.ini to add all of the compressed blocks (dirt/cobble/sand/netherrack/gravel) from Extra Utilities 2 to IC2/Gregtech compressors (with working JEI recipes of course)
https://pastebin.com/TuGCBCkf

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore and since IC2 has it's own recipe configs, neither is IC2
