### ISSUE TITLE
World transmute suddenly not working

### ISSUE THREAD

**Issue by Natey214** [jaredlll08/CraftTweaker#158]
#### Issue Description:
Hello, I am having an issue with the transmute from projecte. Everything was working great and then suddenly I loaded a game and I can no longer transmute anything from the script. I have a recipes script that works perfectly just not the transmute.

#### What happens:
For example: it's set to transmute ice from glass, when aiming philosophers stone at glass nothing happens.

#### What you expected to happen:
Right clicking should transmute glass into ice

#### Script used 
http://pastebin.com/dZfGwvtQ

#### Minetweaker.log file 

http://pastebin.com/g039Wf5i

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2221
- Crafttweaker: 1.10-2.3.0.20

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
http://pastebin.com/93dZkCGv

**Comment by jaredlll08** [comment]
We don't add support for ProjectE go speak to them directly.
