### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by Tsyklop** [jaredlll08/CraftTweaker#16]
I try build CraftTweaker for 1.7.10:
![crafttweakererror](https://cloud.githubusercontent.com/assets/6783568/14760927/b7d490a2-0959-11e6-9248-567ed836bbda.png)

**Comment by jaredlll08** [comment]
Send a pic of your folder?  Like the Minetweaker3 folder

**Comment by Tsyklop** [comment]
@jaredlll08 
![untitled](https://cloud.githubusercontent.com/assets/6783568/14760937/1406b346-095a-11e6-899d-8342c0d1e9bd.png)

**Comment by jaredlll08** [comment]
Oh, my fault then, seems I forgot to add the folder to the project, I'll add it when I get home (will probably only be tomorrow)

**Comment by Tsyklop** [comment]
@jaredlll08 Okey. Thanks. I wait.

**Comment by Tsyklop** [comment]
@jaredlll08 any news?

**Comment by Tsyklop** [comment]
Error...

![untitled](https://cloud.githubusercontent.com/assets/6783568/14808039/ae05b97e-0b8a-11e6-8669-b7a395528386.png)

**Comment by jaredlll08** [comment]
Try now.

**Comment by Tsyklop** [comment]
@jaredlll08 And again:
![untitled](https://cloud.githubusercontent.com/assets/6783568/14840104/7c79299a-0c39-11e6-8764-e7c00596e4c7.png)

**Comment by jaredlll08** [comment]
That one is on you, nothing to do with us, has to do with you not being
able to access the Forge maven

**Comment by Tsyklop** [comment]
@jaredlll08 I can not fix it.
You can publish Craft Tweaker, with the latest changes?

**Comment by Techlone** [comment]
@jaredlll08 
Why there is no compatibility for NEI (1.7.10) in last commit and other mods? Or is it there?

**Comment by jaredlll08** [comment]
Because 1.7 is dead/dying out, by having all of those projects, it delays
the build time, because it has to loop through all of them. So I removed
them to speed up the build time of 1.9 builds

**Comment by jaredlll08** [comment]
This was fixed, the problem was not being able to download resources, which is a gradle / forgegradle issue
