### ISSUE TITLE
[1.10.2] New update crashes on startup

### ISSUE THREAD

**Issue by Kiyaku** [jaredlll08/CraftTweaker#163]
Heya,

just updated to the latest verison of CraftTweaker and when i start it up, following crash happens: http://pastebin.com/BM3XfCnB 

I double checked to see if the old file was in the mods folder as well, but nope, only one of them is present. (as seen here: http://i.imgur.com/euj6h3N.png)

Using latest forge as well. 

Let me know if you need any other info! 

Thanks,
SC

**Comment by InjuredWolf** [comment]
Also got this error. Not just a one-off.
Will try with ModTweaker disabled to see if that helps...

**Comment by DeadSix27** [comment]
Can confirm. same issue, same stacktrace.

**Comment by Ash70** [comment]
I also have this issue, [log is here](https://paste.ee/p/n2K81).

**Comment by Morpheus1101** [comment]
For some reason Forge seems to think its got 2 versions of this mod *.20 and *.21 .... For now everyone will just need to downgrade back 1 version an all will work fine

**Comment by jaredlll08** [comment]
I'm fixing this now, the problem is the way that CrT builds is a bit weird, so it combined the 1.11 and 1.10 source into the same jar file for 1.10.2

**Comment by Morpheus1101** [comment]
lol, goto luv that
