### ISSUE TITLE
Mekanism in 1.10.2

### ISSUE THREAD

**Issue by tjsd** [jaredlll08/CraftTweaker#164]
Issue Description:
Added following mods:
CraftTweaker-1.10.2-3.0.22
ModTweaker2-2.0.9
Mekanism-1.10.2-9.2.1.298

Trying to add custom recipes for enrichment chamber and combiner.

#### What happens:
Error saying no such member mekanism

#### What you expected to happen:
That it would work like described on the wiki
http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Mekanism_Support

#### Script used:
http://pastebin.ubuntu.com/24090159/

#### Minetweaker.log file:
http://pastebin.ubuntu.com/24090164/

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 2239
- Crafttweaker:  3.0.22

**Comment by jaredlll08** [comment]
1) This is the wrong repo.
2) There is no mekanism support in 1.10.
