### ISSUE TITLE
Recipes command fails when encountering a recipe with a null output

### ISSUE THREAD

**Issue by nyanlathotep** [jaredlll08/CraftTweaker#166]
#### Issue Description:
When using /mt recipes, if a recipe exists with a null output, the command fails and doesn't finish dumping recipes. I encountered this problem with Davinci's Vessels 1.10.2-0006, which has an improperly registered recipe.

#### What happens:
/mt recipes fails with the message "An unknown error occurred while attempting to perform this command", and minetweaker.log stops in the middle of the Davinci's Vessels recipes. 

#### What you expected to happen:
For the recipe to be skipped and /mt recipes's output to continue.

#### Script used:
No script involved, only /mt recipes

#### Minetweaker.log file:
[minetweaker.log](https://gist.github.com/nyanlathotep/63f74b68d92e36dc5f77b553f50f7ad2#file-minetweaker-log)

____
#### Affected Versions:

- Minecraft: 10.2
- Forge: 12.18.3.2.2185
- Crafttweaker: 1.10.2-3.0.20

#### Your most recent log file where the issue was present: 

[latest.log](https://gist.github.com/nyanlathotep/63f74b68d92e36dc5f77b553f50f7ad2#file-latest-log)
[direct link to the exception](https://gist.github.com/nyanlathotep/544311fb695a021a59f9385d54b2f010#file-latest-log-L367)

**Comment by darkhax** [comment]
Thanks for the report, we will look into this issue.
