### ISSUE TITLE
crash on server crafting (1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [jaredlll08/CraftTweaker#167]
#### Intro:
i had tweaked a mod to use the actual recipe and the recipe works perfectly single player and local server,but when on dedicated server it does not work

#### Issue Description:
i added the missing recipes,because the mod dev never had time to get a update out so i thought id add the recipe to test further with the mod sparks hammers

#### What happens:
tried to craft hammer head and wooden hammer with recipe i made, thats works as desribed above but then on the dedicated server it says ERROR: modid : item and then after i tried crafting the head it crashed me back to desktop

#### What you expected to happen:
for my tweaks to work no problems and i can continue to test further with mods 

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 1.11.2-2252
- Crafttweaker: CraftTweaker-1.10.2-3.0.20

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
server latest log:
[fml-server-latestlog.txt](https://github.com/jaredlll08/CraftTweaker/files/818109/fml-server-latestlog.txt)

scripts used:
[myrecipeszs.txt](https://github.com/jaredlll08/CraftTweaker/files/818112/myrecipeszs.txt)

minetweaker log: 
[minetweakerlog.txt](https://github.com/jaredlll08/CraftTweaker/files/818113/minetweakerlog.txt)

**Comment by jaredlll08** [comment]
You sure you have the right item names?

**Comment by SDUBZ** [comment]
yes all the names i double checked and everything, but when it was on my server it just didnt wanna work :/

**Comment by Rosethorns** [comment]
I cannot replicate your crash using custom crafting recipes or replaced recipes SDUBZ, are you certain that the scripts folder is on both the client AND the server?

**Comment by SDUBZ** [comment]
yes they are @Rosethorns i  even had my friend try it and it works for him on single and virtual lan server but when it comes to my dedicated server it doesnt wanna play nice at all.

**Comment by Rosethorns** [comment]
I should clarify, I tested it on a dedicated server. You might have a mod interaction elsewhere

**Comment by SDUBZ** [comment]
it is mod interaction because i also tested with customstuff and he clarified its some kind of mod interaction going on now just to debug it i guess :D ,thanks for your help guys :)

**Comment by SDUBZ** [comment]
so far got the list of mods they may have affected the recipe down to http://puu.sh/uAl32/5ccbb09bbf.txt

**Comment by SDUBZ** [comment]
okay after all my testing on a new world it works so i thought after all my testing to test again on the old server world save and now its working but the only file that wasnt needed anymore was [1.11.2] CTD Core-1.0.2.jar not sure if conflicted or not, will test later and get back to you

**Comment by jaredlll08** [comment]
Is this still an issue?

**Comment by jaredlll08** [comment]
no communication for nearly 2 months now, I'm closing it
