### ISSUE TITLE
(1.10.2-3.0.22) Crafting recipe slots that are NULL are not enforced

### ISSUE THREAD

**Issue by ShicKla** [jaredlll08/CraftTweaker#168]
#### Issue Description:
Crafting recipe slots that are NULL are not enforced. What I mean by this is that even if a slot is 'null' in a recipe, any item can be placed in that slot in game and the recipe is still valid.

#### What happens:
Unfortunately if you do go ahead and craft the output, with an item in the 'null' appointed slot, the item in the 'null' slot gets consumed along with the items that are part of the recipe. Kinda sucks if you accidentally leave a valuable item in that slot.

#### What you expected to happen:
The crafting recipe should not be considered valid if extra item's are in 'null' slots. Items that are in 'null' slots should not be consumed when crafting.

#### Script used:
https://gist.github.com/ShicKla/5ccf373786ad4825fa90d1389ea1e5e1

#### Minetweaker.log file:
https://gist.github.com/ShicKla/d13359564e3c36f74b693d8b797b2ded

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2221
- Crafttweaker: 3.0.22

#### Your most recent log file where the issue was present: 
https://gist.github.com/ShicKla/90c808f34157d8b0cd8b1751ce7d08db

**Comment by jaredlll08** [comment]
Any chance you could give me a vanilla script that causes this bug?

**Comment by ShicKla** [comment]
I take it you found and solved the issue and no longer need a vanilla script?

**Comment by jaredlll08** [comment]
Yip, seems to be fixed
