### ISSUE TITLE
CraftTweaker-Customized-1.8.9-3.0.5 IllegalArgumentException

### ISSUE THREAD

**Issue by KurikAmudnil** [jaredlll08/CraftTweaker#17]
java.lang.IllegalArgumentException: Multiple entries with same key: MineTweaker3=FMLMod:MineTweaker3{3.0.4} and MineTweaker3=FMLMod:MineTweaker3{3.0.5}

Reproduced without other mods.  MC 1.8.9, forge-1.8.9-11.15.1.1808

Crash report:
http://pastebin.com/inQT8QY6

**Comment by jaredlll08** [comment]
Yea I'm aware, trying to figure out what is going on, same is for 1.9
version

**Comment by KurikAmudnil** [comment]
The jar file contains folders for MC18 and MC19
/minetweaker/mc18
/minetweaker/mc19

if I delete the mc19 folder from the jar, then it loads.  I imagine deleting mc18 from the 1.9 version would allow that one to work too.  I don't know why the build is putting both versions in the jar file.

**Comment by KurikAmudnil** [comment]
Resolved as of 3.0.6
