### ISSUE TITLE
Incompatibility with CookingForBlockheads

### ISSUE THREAD

**Issue by Gunner76th** [jaredlll08/CraftTweaker#170]
#### Issue Description:
When running CraftTweaker (latest version 3.0.20) and CookingForBlockheads (latest version 4.2.35), CFB causes CT to crash out and shut down the server
This has also been posted to Cooking For Blockheads github here: https://github.com/blay09/CookingForBlockheads/issues/200

#### What happens:
Server fails to start and closes down. No crash report is generated, however a crash report is posted in the fml-server-latest.log file
[fml-server-latest.log.txt](https://github.com/jaredlll08/CraftTweaker/files/823283/fml-server-latest.log.txt)

#### What you expected to happen:
Server to load and run like normal

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[scripts.zip](https://github.com/jaredlll08/CraftTweaker/files/823291/scripts.zip)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[minetweaker.log.txt](https://github.com/jaredlll08/CraftTweaker/files/823287/minetweaker.log.txt)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 2239
- Crafttweaker: 3.0.20

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
[fml-server-latest.log.txt](https://github.com/jaredlll08/CraftTweaker/files/823284/fml-server-latest.log.txt)

**Comment by darkhax** [comment]
I've isolated the relevant info and pasted it [here](https://gist.github.com/darkhax/e51011af44de002554b401615ff18b8f). Looking at your minetweaker.log file it seems that one of the scripts you have (shapelessrecipes.zs) is adding an invalid recipe. Either way, this is fixed in the next episode of Cooking For Blockheads, and is not an issue with this mod.
