### ISSUE TITLE
IC2 machine recipe removal

### ISSUE THREAD

**Issue by erindalc** [jaredlll08/CraftTweaker#171]
#### Issue Description:
I can't remove IC2 metal former recipes. I looked at the source code and such a method doesn't exist. This is a request for one to be created (all the other IC2 machines would be nice too). I don't know if this is possible or not.

#### What happens:
It gives an error.

#### What you expected to happen:
The recipe to be removed.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/erindalc/a09b190b3d537a094b37e0a15bc1a767

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
The whole thing (4000 lines): https://gist.github.com/erindalc/31318a169742cbff2426c0b5051a6173
Relevant part: https://gist.github.com/erindalc/042ee029a0782e5ed3e024a06fdaf999

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.20

#### Your most recent log file where the issue was present: 

The last thousand lines or so is what was in the launcher:
https://gist.github.com/erindalc/e9076bc60812bc78e2df702dc65899bc

**Comment by Lgk2** [comment]
Open Industrialcraft.jar with an archive manager that can handle jar files. Go to assets/ic2/config and copy the whole ic2 folder to your modpacks config location. Now you can edit the ini files called metal_former_rolling/extruding/cutting.ini to add/remove/change recipes. Since IC2 has a builtin method for changing recipes we don't need crafttweaker for it.

**Comment by bookerthegeek** [comment]
While I love the fact that IC2 has a built in way to modify recipes, I would love a way to do that through. Also, this is the CraftTweaker Github, this issue should be posted either over at:
- [Modtweaker](https://github.com/jaredlll08/ModTweaker/issues)
- [IC2 Suggestion Forums](https://forum.industrial-craft.net/board/6-suggestions/)

**Comment by jaredlll08** [comment]
IC2 doesn't support recipes removal

**Comment by CombatZAK** [comment]
@jaredlll08 I know this is awful necroposting, but I discovered a way to remove recipes from IC2 machines for my own pack-custom recipe fixing mod and I just confirmed that it at least works with the Macerator, at least in 1.12.2, and I thought I'd share it in case you wanted to incorporate. You can grab the Iterator object for a machine's recipe list using, for example `Recipes.macerator.getRecipes().iterator()`. From there you can traverse the machine's recipe list manually (`while (iterator.hasNext()) { ... iterator.next(); }`) and when you find a recipe you don't like, you can call `iterator.remove()` and it slices that one out. I just confirmed with an ad-hoc test that it works, at least in ic2 2.8.75-ex112-dev. That's definitely not supported through their API; it's a bit of a hack for sure. Just sharing some findings :)
