### ISSUE TITLE
[1.11.2-3.0.23] Crafting output dupe bug

### ISSUE THREAD

**Issue by Rosethorns** [jaredlll08/CraftTweaker#172]
#### Issue Description:
It appears the craft tweaker crafting dupe bug remains in 1.11.2-3.0.23.
Any craft tweaker crafting table recipe leaves a second result in the output slot after the second is taken.
The example I used is a Quark <-> Chisel basalt conversion recipe in this instance but it appears to happen with all recipes generated by Crafttweaker

#### What happens:
When taking the result of the basalt conversion recipe from the output slot of a crafting interface (in this case a vanilla crafting table) a second result is left behind. The input is cleared in the first retrieval.

(Taking a result of a craft tweaker recipe from a table leaves a second real result in the output slot)
In pictures:
recipe prepared http://i.imgur.com/LsOHiP1.png
After taking output http://i.imgur.com/zBjnSEN.png

#### What you expected to happen:
1 Basalt from quark to convert to 1 Basalt from Chisel

#### Script used :
http://pastebin.com/5DL6KmQs

#### Minetweaker.log file:
http://pastebin.com/y8ZaknVP

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.0.2252
- Crafttweaker: 1.11.2-3.0.23

#### Your most recent log file where the issue was present: 
http://pastebin.com/ZJUp4xX7 server
http://pastebin.com/GaMLAA7u client

**Comment by drakray** [comment]
Same problem as mine #165

**Comment by drakray** [comment]
May I ask your mod list please? I want to compare it to [mine](http://pastebin.com/C71gKFHP), see if I can find something

**Comment by raspopov** [comment]
I can confirm this too, any recipes.addShapeless() or recipes.addShaped() recipes are duplicated.

**Comment by jaredlll08** [comment]
Fixed in latest CrT (.24)
