### ISSUE TITLE
Better With Mods compatabillity error?

### ISSUE THREAD

**Issue by G-Stav** [jaredlll08/CraftTweaker#173]
#### Intro:

Hello, I'm a newbie to scripting, so it is very possible I'm just doing it wrong. If that is the case, then I am very sorry for wasting your time.

I'm attempting to work on some scripts with Better With Mods, and it's not working. I'm not sure if it's because of CraftTweaker or because of Better With Mods.

#### Issue Description:

Mods installed are;
Forge-13.20.0.2255
Better With Mods-1.0.5-1.11.2-hotfix1.jar
CraftTweaker-1.11.2-3.0.23.jar
jei_1.11.2-4.2.8.243.jar

#### What happens:

The script doesn't load, in chat the following error message appears.
ERROR: Error executing hello.zs: com/blamejared/mtlib/helpers/InputHelper

#### What you expected to happen:

I expect the script to add the the recipe to the BWM Millstone.
The bug appears to affect all of the crafting machines from BWM.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

http://pastebin.com/PK8ECLhF

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://pastebin.com/D0ZEUD5m
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.0.2255
- Crafttweaker: 1.11.2-3.0.23

#### Your most recent log file where the issue was present: 

http://pastebin.com/YBFQLanH

**Comment by WesCook** [comment]
It looks like you're missing [MTLib](https://minecraft.curseforge.com/projects/mtlib), which is a dependency for CraftTweaker addons.

**Comment by jaredlll08** [comment]
Yip, this is missing MTLib and even if you had it, I don't add support for BWM so wrong repo.
