### ISSUE TITLE
furnace.setFuel problem

### ISSUE THREAD

**Issue by drakray** [jaredlll08/CraftTweaker#176]
#### Issue Description:
In Forge2233/CT.23(and .23.74), custom setFuel do not show in JEI, but work.
In Forge2255/CT.23(and .23.74), custom setFuel do not work at all.

#### What happens:
using `furnace.setFuel(<minecraft:torch>,500);` no longer make Torch burn 2.5 item

#### What you expected to happen:
for setFuel to work as intended and show in JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

http://pastebin.com/VVD0vU0f
see line 54

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

http://pastebin.com/TNuPjYss
see line 136

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 2255
- Crafttweaker: CraftTweaker-1.11.2-3.0.23.74.jar (link from #165 )
- JEI: 4.2.8.244

#### Your most recent log file where the issue was present: 

https://www.dropbox.com/s/wpr9g4jn2kwwiey/fml-client-latest.log?dl=0

**Comment by jaredlll08** [comment]
This was fixed for Forge 2232
No idea if forge changed something that would have changed this in later versions
