### ISSUE TITLE
[1.10.2] .transformDamage(x) x>0 does not return the tool with the tag.

### ISSUE THREAD

**Issue by JAWSAWN** [jaredlll08/CraftTweaker#177]
#### Intro:
So I have 
recipes.addShapeless(<minecraft:nether_star>, [<biomesoplenty:diamond_scythe>.anyDamage().transformDamage(20), <minecraft:skull:1>]);
And instead of damaging the tool moreit just consumes the item.

#### Issue Description:

.transformDamage(x) does not work as it intended.

#### What happens:

Tool is totally consumed

#### What you expected to happen:

Tool loses 20 durability

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/JAWSAWN/d415bf72bcc0ca392ff7320f428ec8d6

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/JAWSAWN/7e2120605feb503540ed744b8b191b55

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.10.2-3.0.23

#### Your most recent log file where the issue was present: 
https://gist.github.com/JAWSAWN/8ec1e59d22c5e4410ccf466a648f0d24

**Comment by Dune-Jumper** [comment]
I have this issue too. It even happens with the recipe example from the wiki: recipes.addShapeless(<minecraft:stick> * 3, [<minecraft:stone_axe>.transformDamage(4), <ore:plankWood>]);
Surely the devs know about it?

**Comment by bookerthegeek** [comment]
Go read https://github.com/jaredlll08/CraftTweaker/issues/156

**Comment by jaredlll08** [comment]
Fixed in later versions (aka 1.12)
