### ISSUE TITLE
[Suggestion]  Adding xp crafting to other handlers 

### ISSUE THREAD

**Issue by TokkenGmr** [jaredlll08/CraftTweaker#178]
Would it be possible to add the xp requirement to craft something to other crafting handlers such as the extreme/dire crafting table?

**Comment by jaredlll08** [comment]
Yes. But I don't support the mod.

**Comment by TokkenGmr** [comment]
Ok thank you, I was also thinking things from forestry and actually additions. I was just using that first one as an example

**Comment by darkhax** [comment]
We are currently in the process of some major internal refactors to the mod. Said refactors are going to improve the stability and performance of the mod and also make it easier to add new features moving forward. Part of these refactors include expanding our mod support. We will revisit this once we get around to the mod content parts of these refactors, however that will likely be split off into ModTweaker.
