### ISSUE TITLE
1.8.9 - 3.0.6 Interacting crashes client

### ISSUE THREAD

**Issue by hunter688** [jaredlll08/CraftTweaker#18]
http://pastebin.com/xwFK6we3

**Comment by Zhaulus** [comment]
https://pastebin.com/R63BCLUK

**Comment by jaredlll08** [comment]
Just fixed it, any other bugs before I release a new version? I have been spamming curse with versions, so I would like to keep it minimal from now on

**Comment by KurikAmudnil** [comment]
The only other thing I am aware of at this time is that these new versions changed the modid from crafttweaker to MineTweaker3, which breaks ModTweaker.  However, that might be an issue for ModTweaker instead.
