### ISSUE TITLE
Furnace from Extra Utilities 2 ignoring furnace recipe changes

### ISSUE THREAD

**Issue by starg09** [jaredlll08/CraftTweaker#180]
#### Issue Description:

The electric furnace added by Extra Utilities 2 bases its recipes on the registered ones for the vanilla furnace. However, it seems to be ignoring changes made through CraftTweaker. [There's a report on ExU's repo](https://github.com/rwtema/extrautilities/issues/1372), but doesn't seem to have been answered at the time of making this one over here.

#### What happens:

Removed a smelting recipe from a mod, readding it with a different output. Vanilla furnace changed accordingly, but the one from ExU2 didn't.

#### What you expected to happen: 

The ExU2 furnace taking the recipe change automatically.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://gist.github.com/starg09/3633a9fa72264c0faab19bb09c51562a

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://gist.github.com/starg09/71d74abecdd9bb955892c25fad8a1521

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 2259
- Crafttweaker: 3.0.24
- Extra Utilities: 1.3.3

**Comment by bookerthegeek** [comment]
http://teamcofh.com/docs/thermal-expansion/other/inter-mod-communication/

As of 04/04/2017 you must use IMC to change COFH stuff. See also https://github.com/jaredlll08/ModTweaker/issues/459

**Comment by starg09** [comment]
@bookerthegeek Hmm, Extra Utilities is not a CoFH mod though? Unless you mean its recipes are also provided through IMC, which I have no idea since the mod is closed source... I know you can decompile it and check, but still.

**Comment by jaredlll08** [comment]
I have looked before, furnace support for ExU2 isn't possible, sorry.

**Comment by bookerthegeek** [comment]
@starg09 i mis read, sorry. But i think exu2 is intrgrating their own mechanic on their side.
