### ISSUE TITLE
Viewing Furnace Recipies Crashes

### ISSUE THREAD

**Issue by WenXin20** [jaredlll08/CraftTweaker#181]
#### Issue Description:
Viewing furnace recipies crashes the game if the mod is missing Instead of disabling the recipe.

#### What happens:
A crash occurs if the recipe for cooked fish (anything using the furnace) is viewed using JEI.

#### What you expected to happen:
To be able to view Recipies without crashing if the mod is missing.

#### Script used:

http://pastebin.com/inruVFpK

#### Minetweaker.log file:
http://pastebin.com/9BTBfXsg

____
#### Affected Versions:

- Minecraft: 1.10.2
- Forge: 2221
- Crafttweaker: 3.0.24

#### Your most recent log file where the issue was present: 

[Crash Report](http://pastebin.com/i2tT4yxb)
[Latest.log](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/files/852221/latest.txt)

**Comment by jaredlll08** [comment]
You should fix the script rather then let it error, if it tells you an item can't be found, fix that before doing anything else.
