### ISSUE TITLE
Questions about compatibility

### ISSUE THREAD

**Issue by lllMohandarlll** [jaredlll08/CraftTweaker#182]
**Is it possible to make Immersive Engineering Assembler recipe unique? I mean.. is possible to make custom recipes that works only in IE automatic Assembler?**

This was the first question,

the other one is one that I've already posted on minetweaker 3 forum thread;

Are the Magneticraft electric tools supported?
I noticed that Magneticraft in general is supported (mainly for machinery), but I was wondering if I can use Magneticraft electric tools (such as chainsaw) for craftings and make them discharge as much as you can do for IC2 electric items

Crafting with electric items
You can use and discharge IC2 tools in crafting recipes. For example:
val chainsaw = <IC2:itemToolChainsaw>.anyDamage();

recipes.addShapeless(<minecraft:stick> * 3, [<ore:plankWood>, chainsaw.onlyIC2ChargeAtLeast(100).transformIC2Discharge(100)]);

the Magneticraft chainsaw has these infos:
<Magneticraft:item.chainsaw:1>.withTag({Charge: 500000})

the charge tag is not needed in this case, I guess...

if the answer is yes, the question is "how?"
I've tryed some pattern like that one above but I still wasn't able to adapt it and make it work

All of this using the latest version of Forge (1614)  and latest of CraftTweaker  (for 1.7.10)

**Comment by jaredlll08** [comment]
1) I don't add support for IE.
2) nope

**Comment by lllMohandarlll** [comment]
You mean that you don't add **further** support to IE, since IE is already mostly supported from base minetweaker.
Btw, there is no need to be so rude :/
(idk, probably this is your normal way to reply when you're in hurry... it just gave me that impression..)

**Comment by jaredlll08** [comment]
I don't know what you want to do with IE, what I'm saying is that I don't add support for it, the support is added through IE itself, so if it is for an IE machine, you need to speak to them

**Comment by lllMohandarlll** [comment]
Yeah, you're right in effect.. but well, wrote in this was your phrase is more likely friendly and comprehensive :)

Just a last thing, since idk if it would be worth to open another issue for this;

In the minetweaker wiki, when you look on the better storage compatibility it says that both the two fuctions:
"mods.betterstorage.CraftingStation.addShaped"
and
"mods.betterstorage.CraftingStation.addShapeless"
can be used to remove recipes too:
"Each of these handlers can have recipes added or removed"

But it does make any example about the remove version of the function..

I've tryed
mods.betterstorage.CraftingStation.remove
and
mods.betterstorage.CraftingStation.removeShapeless
and so on but minetweaker still says that are not valid functions (so it's not a correct syntax)

What should I try? 
I'm tryng to get rid of the dupe glitch in the crafting station by removing the glitched recipes, but I've not figured out if there really is a remove function for that as the wiki states..

**Comment by jaredlll08** [comment]
That is another one that we don't add support for, it would be better to make an issue on the better storage issue tracker

**Comment by lllMohandarlll** [comment]
I will :)
Thanks

**Comment by lllMohandarlll** [comment]
I will :)
Thanks
Btw, almost forgot, so in the end, is the wiki wrong?
there is no remove function even if it says that those functions works in both cases?

**Comment by jaredlll08** [comment]
I'm not sure, I have never looked into the mod
