### ISSUE TITLE
MineTweakerAPI.ijeiRecipeRegistry.removeRecipe not updating JEI

### ISSUE THREAD

**Issue by Matryoshika** [jaredlll08/CraftTweaker#183]
#### Issue Description:
I'm working on adding native CraftTweaker support to my mod, [Underworld](https://github.com/Matryoshika/Underworld), which has a rather simple trading-block. Give X, get Y.
When using _MineTweakerAPI.ijeiRecipeRegistry.removeRecipe()_, CraftTweaker does not update JEI as it should.
Where I am calling said method: [MTMetamorphicTableRecipes L82](https://github.com/Matryoshika/Underworld/blob/master/src/main/java/se/Matryoshika/Underworld/Integration/CraftTweaker/MTMetamorphicTableRecipes.java#L82)

#### What happens:
_MineTweakerAPI.ijeiRecipeRegistry.removeRecipe_ does not cause JEI to remove the recipe.

#### What you expected to happen:
That said method call would update JEI to remove the recipe.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
http://pastebin.com/2XsSP75e

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
http://pastebin.com/yKuQ0dFX

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 3.0.23
- JEI: 3.14.7.416

**Comment by jaredlll08** [comment]
The line should be in the action, also if you use a JEIRecipeWrapper you need to remove the wrapper

**Comment by Matryoshika** [comment]
That is odd.
_removeRecipe(object)_ refers to the private _removeRecipe(object, object.class)_
which refers to the private _removeRecipeUnchecked(T , IRecipeCategory)_, which calls _wrapperMap.remove_ ö.Ö
Gonna have to step through and see why the wrapper isn't being removed.

**Comment by Matryoshika** [comment]
All good now.
Thanks for the help :+1:
