### ISSUE TITLE
Script file iregularities

### ISSUE THREAD

**Issue by the-creamster** [jaredlll08/CraftTweaker#184]
I'm getting some weirdness with a select few of my script files but it's not affecting all the other ones.
mc version: 1.10.2
forge version: build 2254
craft tweaker version: 3.0.24

draconic evolution script file: https://gist.github.com/the-creamster/22fde31ce5780b274d2939da06bad42a
pic of "broken' recipe: https://gyazo.com/ed4b3b10807fd037f566df82e8319677
- same for the other 3 recipes in this file
plate stuff script file: https://gist.github.com/the-creamster/25d6d2c1a8afb053a48e21aa5b623ab5
- This script file is using the 'craft planks with an axe' format example on the wiki, just using the IE hammer and metal ingots instead of an axe & wood logs
log file: https://gist.github.com/the-creamster/6e2103cb8b4517f1fd98c84a7a702010
- ignore line 680-748 atm(TR added MT integration in one of their latest versions so it could be their side; i have reported it and am awaiting there response)

As you can see it strange why it's only affecting those 2 files atm; haven't gone through a lot of the other mods in the modpack yet.

**Comment by jaredlll08** [comment]
Please follow the issue format.
