### ISSUE TITLE
Script file irregularities

### ISSUE THREAD

**Issue by the-creamster** [jaredlll08/CraftTweaker#185]
#### Issue Description:
I'm getting some weirdness with a select few of my script files but it's not affecting all the other ones. The particular script file in question is that of Draconic Evolution. The recipe has been tweaked, isn't erroring out yet it's not taking effect at all. The same thing is happening with another script file not included here but that mod recently added MT ingetration to its vast array of machines so it could be there side.

i have 6+ more script files to fill out so want to kinda know what's wrong before i get it across a larger number of them.

#### Scripts used:
draconic evolution script file: https://gist.github.com/the-creamster/22fde31ce5780b274d2939da06bad42a
pic of "broken' recipe: https://gyazo.com/ed4b3b10807fd037f566df82e8319677
plate stuff script file: https://gist.github.com/the-creamster/25d6d2c1a8afb053a48e21aa5b623ab5
- this file is using the same format as the 'crafting planks with an axe' example on the wiki, just replaced the axe with the IE hammer and the log with a 2 metal ingots

#### Minetweaker.log file:
https://gist.github.com/the-creamster/6e2103cb8b4517f1fd98c84a7a702010
- ignore line 680-748 atm

____
#### Affected Versions:
mc version: 1.10.2
forge version: build 2254
craft tweaker version: 3.0.24

**Comment by jaredlll08** [comment]
Uh, what is actually wrong with your stuff? I don't see anything wrong...

**Comment by Ommina** [comment]
Perhaps I'm confused, but, are script commands to the effect of 

`recipes.remove(<ore:plateIron>);`
`recipes.addShapeless(<ore:plateIron>, ...`

at all valid?  Assuming my understanding that `ore:` means 'an ore dictionary list' is correct, I don't get how a recipe can have such a list as an output.  I would expect the recipe would have to create an actual item, which, in turn, would be added to the ore dict.  Or is zen script more magical than I previously thought?

**Comment by the-creamster** [comment]
The first tweaked recipe is refusing to show as i changed it too and in the last little bit of time have been working on another script file to get an almost crash log type error output for a recipe and only that recipe. I'll update the original log to show you.

**Comment by jaredlll08** [comment]
The tconstruct stuff should just be
```
<tconstruct:pick_head>.withTag({Material:"electrum"})
```
I recommend that you use mt hand on it to get the proper name and copy it to your clipboard.

Then for your plate issue, you are trying to output an oredictionary, which isn't possible, you need to output an ItemStack, like
```
<minecraft:stick>
```

**Comment by the-creamster** [comment]
The 'plate stuff.zs' is still refusing to work for me.
https://gist.github.com/the-creamster/c4bdd51c07a678e006cd06c859acb227

**Comment by jaredlll08** [comment]
@the-creamster Have you read the wiki? since you are doing some VERY weird stuff...
You can't use 
```
<ore:ingotIron>*2
```
in an input, inputs are single item only.

**Comment by the-creamster** [comment]
This is the example on the wiki, about halfway down;
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes
"
Great! We can reuse the axe. Now what if we also wanted the axe to be damaged when you use it?
recipes.addShapeless(<minecraft:stick> * 3,
    [<minecraft:stone_axe>.transformDamage(), <ore:plankWood>]);
"
whereas mine is
"
recipes.addShapeless(<techreborn:plates>,
    [<immersiveengineering:tool>.transformDamage(2), <ore:ingotIron>*2]);
"

The only difference between mine and the example one is a single output & double item input. If it's the case of a multiple input item then that specific portion isn't covered or mentioned anywhere at all and thus should be which would have avoided all of this.

So if i were to use 2 seperate following on references would that work??

**Comment by darkhax** [comment]
From the vanilla level, shapeless recipes, and recipes in general, only accept singular items for inputs. That's just part of how the base game works. So if you want your shapeless recipe to have two iron ingots, you would need to include the same item entry multiple times.

**Comment by the-creamster** [comment]
Ok, the log isn't erroring out on that script file now but surprisingly only a small amount of them are working.
script file: https://gist.github.com/the-creamster/eb10cdbbd93155516925a8db1f355a64
updated log file: https://gist.github.com/the-creamster/211266f24ce577fdb749ed04c3c2aed8(line 209-266)
example pics:
https://gyazo.com/9011fc4d3255cafe7b7499349ea5e787
https://gyazo.com/ddf78291d07938e4504b5e768af2fcab
https://gyazo.com/f0970a4065b75e1a43f63b2cae8d5e54

Is this a genuine bug now???

**Comment by jaredlll08** [comment]
I still have no idea what is even wrong with this.
Please upload ALL of your scripts, and the log file from a fresh client restart (not a reload)

**Comment by the-creamster** [comment]
All is in good order for now; with the most recent observation being that an execution of the reload command doesn't always seem to properly register the changed/added recipe so a world and /or modpack reload does the trick.
