### ISSUE TITLE
Removing all recipes from a specific mod: <minecraft:*>

### ISSUE THREAD

**Issue by bluefutureMC** [jaredlll08/CraftTweaker#188]
#### Intro:
Please note, you will be treated exactly like any other person who submits a bug report, saying this, if you decide to delete this template entirely, your issue will be closed. If you do not provide relevant information when reporting an issue (for example having a script issue and not providing the scripts or the minetweaker.log file) this issue will be closed. you may now delete this section and continue on with the report.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
I try to use the function "{mod name}:*" and it doesn't work
It give an error message. I really don't even know if the feature is added but I seen alot of people talking about it.

#### What you expected to happen:
I expected that to be counted as all recipes from the mod specified.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/rjurx2iv

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/baxPCk3p

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 3.0.24

#### Your most recent log file where the issue was present: 
https://gist.github.com/bluefutureMC/965f3f42106707a231cf38c35fa16cd7
[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
The command doesn't and won't exist.
