### ISSUE TITLE
tooltips command in client/server environment

### ISSUE THREAD

**Issue by KurikAmudnil** [jaredlll08/CraftTweaker#19]
I have noticed that the /minetweaker tooltips command doesn't actually show tooltips when in the client/server environment.  It works in the single player environment.  I have found that I have to jump through hoops to get the item:meta references to use in scripts on my private server.

Is this intended behavior? Limited by OP level (currently using OP level 2)?
MC 1.8.9; forge-1.8.9-11.15.1.1808

**Comment by jaredlll08** [comment]
We don't add a tooltip command, this is a modtweaker issue.
