### ISSUE TITLE
Blood Magic, Blood altar recipes.

### ISSUE THREAD

**Issue by Lgk2** [jaredlll08/CraftTweaker#190]
#### Issue Description:

The bloodmagic compatibility doesn't seem to work in 1.10.2, maybe it's not implemented yet. 

#### What happens:

The recipe is removed but still shows up in JEI. Adding a new recipe for the blood altar didn't work.

#### What you expected to happen:

The recipe to be removed and to not show up in JEI. The new recipe works and you can see it in JEI.

#### Script used
https://gist.github.com/Lgk2/435e657d92c0a169ec1f50dd279e5e05

#### Minetweaker.log file
https://gist.github.com/Lgk2/7fd71c5138ead181fd7cd4a4bdc2c99d

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.10.2-3.0.24
- ModTweaker: 2-2.0.11
- BloodMagic: 1.10.2-2.1.9-78

**Comment by jaredlll08** [comment]
Wrong repo.
