### ISSUE TITLE
CraftTweaker and JEI Problem long load time

### ISSUE THREAD

**Issue by cyberpunkbln** [jaredlll08/CraftTweaker#191]
#### Issue Description:
When i use Crafttweaker and JEI (jei_1.11.2-4.2.10.248) minecraft/forge have a long long long load time about a few minutes. The difference is when JEI loaded 5 seconds to a few minutes with CF.

Deactivate i JEI then he loads very quickly with Crafttweaker
Deactivate i CF the he loads very quickly with JEI

#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2279
- Crafttweaker: CraftTweaker-1.11.2-3.0.24

thx

**Comment by jaredlll08** [comment]
what do you mean by "CF"?

**Comment by cyberpunkbln** [comment]
Hello,
i mean CraftTweaker :).

With CraftTweaker and JEI i wait 20 Minutes and the close i the Forge-Loader. Forge show that JEI has loaded and then he stucks. When i only deactivate one of them he stucks for a few seconds (its normal).

thx

**Comment by cyberpunkbln** [comment]
Hello,
in the jei-issues the other user discuss allready about this problem. Shows like a order-loader problem and affect many other mods.

[https://github.com/mezz/JustEnoughItems/issues/551](url)

Its a JEI-Bug/Problem and JEI is on the way to fix this and the need for other mod-coders is not necessary. Sorry and thx.
