### ISSUE TITLE
Suguestion: Thermal Expansion integration

### ISSUE THREAD

**Issue by darkshadow543** [jaredlll08/CraftTweaker#192]
Went to create a new Thermal Expansion Recipe to turn sand into clay, but Thermal Expansion is not in craft tweaker like it was in mine tweaker.

**Comment by bookerthegeek** [comment]
Wrong repo. Also
https://github.com/jaredlll08/ModTweaker/issues/459

**Comment by MarshTheBacca** [comment]
I would also like to see support for TE if you have some spare time :P

**Comment by jaredlll08** [comment]
Already  in modtweaker

**Comment by MarshTheBacca** [comment]
Thanks I didn't know that. I don't see why the two should be separate mods though :?

**Comment by jaredlll08** [comment]
Because the way that Crafttweaker works doesn't allow for throwing 33 mods
into the dev environment, and I want crafttweaker to be stable, which
modtweaker is not.

**Comment by MarshTheBacca** [comment]
That's undersrandable keep up the good work
