### ISSUE TITLE
JEI not showing added Recipes.

### ISSUE THREAD

**Issue by bookerthegeek** [jaredlll08/CraftTweaker#193]
#### Issue Description:
Hello Jared! So when I add a chopping recipe from the [Survivalist][1] mod, while it still works it does not show up in JEI. [This][2] is an issue where he talks about it a little, and [here][3] is the integration with craft tweaker code.

#### What happens:
The recipe is added, and it works but does not show up in JEI

#### What you expected to happen:
For it to show up

#### Script used (Small script, so inline code ok?)
```
import gigaherz.survivalist.Choppable;
Choppable.addRecipe(<natura:redwood_logs>, <natura:overworld_planks:8>);
```
Suprisingly enough, he goes ```(inputStack, outputStack)``` instead of ```(outputStack, inputStack)```. Took a hot minute to figure out how that actually worked.
#### Minetweaker.log file 
[Here][4] you go, although it is rather large. It is not showing any errors for this though.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.10.2-3.0.24

#### Your most recent log file where the issue was present: 

No log. :)

[1]:https://minecraft.curseforge.com/projects/survivalist
[2]:https://github.com/gigaherz/Survivalist/issues/32
[3]:https://github.com/gigaherz/Survivalist/blob/1.10.2/src/main/java/gigaherz/survivalist/integration/MineTweakerPlugin.java
[4]:https://gist.github.com/bookerthegeek/3cbe7c89e37680e7908af29636e7cd2d

**Comment by jaredlll08** [comment]
Replied to the issue on his side.

**Comment by bookerthegeek** [comment]
Thank you good Sire, I will ignore all the bad things people say about you.

**Comment by jaredlll08** [comment]
Bad things? What bad things?! *acts all innocent*
