### ISSUE TITLE
Crash with Malisis Mods on 1.11.2

### ISSUE THREAD

**Issue by NovaViper** [jaredlll08/CraftTweaker#194]
#### Issue Description:
Whenever I hover my mouse over a custom door I created with MalisisDoors, the game crashes immediately.,

#### What happens:
The game just crashes whenever I hover my mouse over a custom door I made with MalisisDoors

#### What you expected to happen:
The game shouldn't crash

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
None

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/ikmCvWmt

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.0.2228
- Crafttweaker: 3.0.24
- MalisisBlock: 5.1.0
- MalisisCore: 5.1.1
- MalisisSwitches: 4.1.0

#### Your most recent log file where the issue was present: 

https://gist.github.com/NovaViper/bf83517c4586866b815c302deb5cc7ab

**Comment by NovaViper** [comment]
I have already reported this to the developers of the MalisisMods at Ordinastie/MalisisCore/issues/91

**Comment by jaredlll08** [comment]
can you show me a picture of what the tooltip usually says? (remove crafttweaker for this)
Also can I get the log of when it works please (without CrT)

**Comment by NovaViper** [comment]
Here's a log without CraftingTweaks and the door info

https://gist.github.com/NovaViper/c7a205c3eb09e4b8d9c9fcfb62e088b8
![doorinfo](https://cloud.githubusercontent.com/assets/7191115/25140514/3dc9ffc0-2426-11e7-9e27-76e5185e161a.png)

**Comment by jaredlll08** [comment]
Can you make an item with no air blocks? (not sure if it is possible, I have never used malasisdoors)

**Comment by NovaViper** [comment]
I don't think you can.. As it needs something in each slot (though I haven't confirm this)

**Comment by jaredlll08** [comment]
exactly, if it needs something in each slot, how do you have 2 slots being air?

**Comment by NovaViper** [comment]
I'm not sure.. I put in two water buckets for the blocks and wood for the frame

**Comment by jaredlll08** [comment]
Well you put items in it... Try blocks

**Comment by NovaViper** [comment]
The wood I used wasn't an item, it was a block. Hm, when I do use blocks for the other parts, it does display the block type.

**Comment by jaredlll08** [comment]
I meant the buckets, those are items

**Comment by NovaViper** [comment]
Yeah, I put blocks instead of the buckets this time, and I got the block information instead of air
![untitled](https://cloud.githubusercontent.com/assets/7191115/25282352/d2e484da-2675-11e7-8547-a48b09dc2092.png)

**Comment by jaredlll08** [comment]
Does it still crash?

**Comment by NovaViper** [comment]
Let me try with the mod in

**Comment by NovaViper** [comment]
Hm, so far, no crash
