### ISSUE TITLE
Impossible to access member of DataMap that has a space symbol in its name.

### ISSUE THREAD

**Issue by kimitsu** [jaredlll08/CraftTweaker#197]
#### Issue Description:
It seems to be impossible to access members of DataMap via dot notation, if the member name has a space symbol in it.

#### What happens:
The tag name is "Processing Tag"
tag.Processing Tag doesn't work for obvious reasons.
There is code in zenscript/parser/expression/ParsedExpression.java @ 260 that suggests that you could use tag."Processing Tag", but it seems to be bugged: it tries to parse T_STRING instead of T_STRINGVALUE.
As a result, tag."Processing Tag" gives an error

#### What you expected to happen:
tag."Processing Tag" to be parsed into ParsedExpressionMember
The fix seems to be as simple as correcting T_STRING to T_STRINGVALUE in ParsedExpression.java @ 260

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/gPQWPKYL

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/8jjC3Z5C

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1614-1.7.10
- Crafttweaker: CraftTweaker-1.7.10-3.0.13.jar

#### Your most recent log file where the issue was present: 

https://pastebin.com/z5b33xz0

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.

NBT tags should be single words, the mod that adds the items has messed up.
