### ISSUE TITLE
Crash when switching to another single player world

### ISSUE THREAD

**Issue by Alan19** [jaredlll08/CraftTweaker#198]
#### Issue Description:
When I try to go from one single player world to another, the game crashes

#### What happens:
The game stops loading and the log reports that multiple mods (Modtweaker, CTGUI) stopped because of an issue with Minetweaker3

#### What you expected to happen:
The world to load

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/e87zX9vE
OR
https://github.com/belathus/Wanderlust-Renewed/tree/master/scripts

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/Alan19/cd6cc910bc39d064a98e1c42200a7ffe
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.10.2
- Forge:12.18.3.2254
- Crafttweaker:3.0.24 

#### Your most recent log file where the issue was present: 
https://gist.github.com/Alan19/cd6cc910bc39d064a98e1c42200a7ffe

**Comment by bookerthegeek** [comment]
Crash report?

**Comment by Alan19** [comment]
There's no crash report as the client stopped loading

**Comment by Alan19** [comment]
Check the end of the first file

**Comment by bookerthegeek** [comment]
Yeah, about that.

1) restart computer
2) Open Instance, and join world.
3) Exit said world WITHOUT DOING ANYTHING
4) Join new world.
5) Post that log please.

**Comment by jaredlll08** [comment]
I believe this is actually a chisel issue, please report to them.
