### ISSUE TITLE
Recipes don't work like I wanted

### ISSUE THREAD

**Issue by deni500** [jaredlll08/CraftTweaker#199]
#### Issue Description:
I created new recipes for Portable Tanks from ThermalExpansion on 1.10.2 because I don't like upgrade kits - I need it for my modpack.

#### What happens:

Everything is good but when I try craft it with some fluid inside tank, it remove that fluid from tank 

#### What you expected to happen:

It will keep that fluid in tank.

#### Script:

https://pastebin.com/3iEy1zNB

#### Minetweaker.log file:

https://pastebin.com/xwzzxZpn
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.10.2-3.0.24

#### Your most recent log file where the issue was present: 

https://pastebin.com/SKA7q7sj

If I can guess, I doing someting wrong, any help is appreciated.

**Comment by jaredlll08** [comment]
Uh, I'm sorry, but can you explain that a but better? What tank losses it's
fluid? The tank being crafted or the tank used in crafting?

**Comment by deni500** [comment]
When you put tank with any fluid into crafting table and use it to craft better tank it will lose fluid.

**Comment by jaredlll08** [comment]
Which tank loses the fluid? The new tank or old tank?

**Comment by deni500** [comment]
The new tank which you crafted from the old one.

**Comment by jaredlll08** [comment]
Well you aren't specifying which liquid to use, so that would be a problem...

**Comment by deni500** [comment]
So, can you help me what I should add to make it work please ?

**Comment by jaredlll08** [comment]
not much you can do, Crafttweaker can't do what TE is doing unfortunately
