### ISSUE TITLE
1.8.9-3.0.6 error using /mt reload 

### ISSUE THREAD

**Issue by KurikAmudnil** [jaredlll08/CraftTweaker#20]
ArrayIndexOutOfBoundsException

extract from latest.log (no crash)
http://pastebin.com/Eiz7fXLd

looking at the minetweaker.log it looks like it is getting stuck trying to undo  an ore dictionary entry.

**Comment by jaredlll08** [comment]
Scripts please

**Comment by KurikAmudnil** [comment]
In trying to narrow down the problem, I found that the stuck modifications issue was being caused by the presence of ModTweaker and thus it has been removed.  The IndexOutOfBoundsException still occurs when I try to reload after loading a script that creates an ore dictionary.


* [aroma.zs](http://pastebin.com/9Lr9fGey) ; fix missing recipes from aroma mining dimension
* [basics.zs](http://pastebin.com/ax5S5TcM)
* [experiment.zs](http://pastebin.com/bdvXHcvv) ; a place to build/test new recipes
* [fix-etc.zs](http://pastebin.com/Vbyw2nmq) ; various fixes, mostly fixing the use of 3x3 for 2x2 and 1x3 recipes
* [gears.zs](http://pastebin.com/XDZQRSSj) ; WIP, haven't settled on a recipe
* [improving-mc.zs](http://pastebin.com/TrPqWr7p) ; recipes related to mod improving-mc
* [melon.zs](http://pastebin.com/nHBLVu6j)
* thaumcraft-research.zs ; removed due to ModTweaker issues

These 4 scripts create a new ore dictionary and the created ore dictionaries seem to be where the undo problem happens
* [arrows.zs](http://pastebin.com/yY0VnMzM)
* [AxeCutAll.zs](http://pastebin.com/Gkrz01N2) ; Allow JEI to show me which axes have been configured with CutAll
* [bones.zs](http://pastebin.com/e0JAtY9m) ; inspired from somewhere
* [stairs.zs](http://pastebin.com/nyPJLDaT) ; ineficient default stair recipe annoys me (especially with metal block stairs)

**Comment by jaredlll08** [comment]
Can I give you a dev version to test with?

**Comment by KurikAmudnil** [comment]
Certainly.  I will be a bit busy until this afternoon though.

**Comment by jaredlll08** [comment]
Try with the version from here
http://51.255.41.90:8081/view/Jared/job/CraftTweaker/11/

**Comment by jaredlll08** [comment]
When I say try, I actually mean, run that version, them give me the minetweaker.log

This will still crash, but it will give some more info

**Comment by KurikAmudnil** [comment]
[minetweaker.log](http://pastebin.com/78AWS7Y6)

**Comment by KurikAmudnil** [comment]
I think this previous [commit](https://github.com/jaredlll08/CraftTweaker/commit/48dd85aa133ef5d35e68f146d508628b04e697ea) may need to be reapplied.

**Comment by jaredlll08** [comment]
Yea that would be useful >_<

**Comment by jaredlll08** [comment]
Just did it: http://51.255.41.90:8081/job/CraftTweaker/

**Comment by KurikAmudnil** [comment]
Build 12+ fixes the issue
