### ISSUE TITLE
Buildcraft is not a member function.

### ISSUE THREAD

**Issue by micheldewit** [jaredlll08/CraftTweaker#200]
#### Issue Description:
As per MineTweaker 1.7.10 and Crafttweaker 1.7.10: 
I am creating CraftTweakers Recipes with the function mods.buildcraft.AssemblyTable.AddRecipe to create AssemblyTable recipes. 
In 1.11.2 however, any and all functions regarding buildcraft fail. 

#### What happens:
I receive an error stating the following: Error executing BuildCraft.zs on line 2: No Such Member: buildcraft

#### What you expected to happen:
That the buildcraft integration would kick in, and allow the recipes to be created. 

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/sJGcgC8h

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/N2LGaF3f

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 2284
- Crafttweaker: 1.11.2-3.0.24

#### Your most recent log file where the issue was present: 
https://drive.google.com/file/d/0B8CbgVsqPN0XLVJXMVdWMUlEbGc

**Comment by jaredlll08** [comment]
We don't add buildcraft support, they added it themselves in 1.7.10, and as far as I know, there is no BC 1.11.2 for me to add support to

**Comment by asiekierka** [comment]
@jaredlll08 FWIW, since April 1st, there is - but the team will probably get to adding support themselves when it becomes stable.
