### ISSUE TITLE
Problem with NEI.addentry

### ISSUE THREAD

**Issue by ToyPower** [jaredlll08/CraftTweaker#201]
#### What happens:
When ever I do /mt reload twice anything I did using NEI.addEntry is now gone with whatever part also contains it.

#### What you expected to happen:
I expected that when I execute this, it generates it in the NEI and stays there without any problem instead of just going away.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/59Ze8gsK

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/a4bPY7Xc

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: 1.7.10 - 10.13.4.1614
- Crafttweaker: 1.7.10-3.0.11

#### Your most recent log file where the issue was present: 

I already put the two logs you wanted in I do not know what to put here

**Comment by ToyPower** [comment]
I also forgot to mention, I also tried the script without NEI.hide in front of NEI.addEntry

**Comment by bookerthegeek** [comment]
@ToyPower 
> ... using NEI.addentry it works ...
> ... I then do /mt reload, it breaks ...

Don't use `/mt reload` as that is only supported for the following vanilla minecraft mechanics:
- Crafting
- Furnace

All other issues with that command are not supported. If you can reproduce the issue without using that command please come back and make a new issue. Thank you for the report.

**Comment by TheWildMind** [comment]
That is unfortunate, given that some mods register their items too late it seems, so in this case I either ignore that, or reload to get that clean but loose the added entries >.<
Is there any way to force CraftTweaker do come in action "at the last minute"?

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.

CraftTweaker already comes into action at the last possible time, if a mod is adding a recipe too late, it is their fault and you should report it to them.
