### ISSUE TITLE
Changing the display name and JEI

### ISSUE THREAD

**Issue by belathus** [jaredlll08/CraftTweaker#202]
#### Issue Description:
Searching JEI for an item that has had its display name changed (via .displayName = "") turns up no results. Searching for the original display name still works, though.

I'm going to also report this to Mezz and JEI.

#### What happens:
I changed the name of the Iron Promise Acceptor from EvilCraft to "Silver Promise Acceptor". If I search for "Silver Promise" in JEI, there are no results, but if I search for "Iron Promise", the silver promise acceptor pops up.

#### What you expected to happen:
The opposite.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/rename.zs

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/belathus/f33e0707cc1a690f793bdf21ce853fbb

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Crafttweaker: 2.3.0.24

#### Your most recent log file where the issue was present: 
https://gist.github.com/belathus/3301cf999f3d320da27eca43e52799c0

**Comment by MentalMouse** [comment]
JEI also does not display an ingredient's name specified with onlyWithTag().

[This script](https://github.com/MentalMouse/CraftTweaker-scripts/blob/master/ma-spawn_eggs-hard.zs) demonstrates the problem; it uses two intermediate spawn eggs (search for "Beast" and "Humanoid"), which are then subjected to other recipes.

**Comment by belathus** [comment]
I find that using both "withTag" and "onlyWithTag" together resolves this. https://github.com/belathus/Wanderlust-Renewed/blob/55f58d37a66a97a9fff27b7c68ed4e4767f68c09/scripts/machines.zs#L10

**Comment by MentalMouse** [comment]
Using withTag() on an input gets me an error on the line:  basically a type mismatch.

**Comment by belathus** [comment]
You have to do it in order of <item>.withTag().onlyWithTag(). Reversing the order gives that error.

**Comment by MentalMouse** [comment]
Hmm.  Another thing for the documentor to note down....  For the record, all withTag()s need to precede all onlyWithTag()s.

**Comment by MentalMouse** [comment]
Since this issue is about finding stuff in JEI, I'll point out that JEI shows both of my intermediate spawn egg's recipes along with _all_ the other spawn egg recipes -- that is, when hitting R on, e.g. the chicken spawn egg, the recipes for my beast and humanoid eggs (which are not used for the chicken) are also shown.
