### ISSUE TITLE
JEI.hide() not hiding

### ISSUE THREAD

**Issue by BigJazzz** [jaredlll08/CraftTweaker#203]
#### Issue Description:
I'm aware this issue has been raised repeatedly, however after looking through the previous tickets I'm unsure if this issue has been fixed yet, or if it has if I'm doing something wrong. I originally thought that the issue was because I was using a wildcard for the item name (as recipe removal didn't work either), however after specifying an item (`<refinedstorage:grid>` in this case) it removed the recipe successfully. It still refuses to hide the item however.

I'm trying to hide `refinedstorage` items in JEI using `JEI.hide()` not hiding items.

#### What happens:
Items still show in JEI

#### What you expected to happen:
Items hidden in JEI

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/7PyZu9pZ

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/b3ZjSS6t
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.10.2-3.0.24

#### Your most recent log file where the issue was present: 

https://pastebin.com/TCk89DEV

**Comment by BigJazzz** [comment]
Related to this issue (and I'm happy to open another ticket if you'd like) wildcards don't seem to be working. When I tried to do `recipe.remove(<refinedstorage:*>);` it threw an error in game: `ERROR: zzzCraftAU_disabled.zs:32: Could not resolve <refinedstorage : *>`. Any thoughts?

**Comment by jaredlll08** [comment]
Wildcards like that have never and will never work, you can't use a
wildcard for any block from a mod...

**Comment by BigJazzz** [comment]
Even doing `<recipe.remove(<refinedstorage:grid:*>);` didn't remove the recipes for all the other grid blocks.

We've used wildcards previously (probably with Minetweaker3) to disable groups of items (first time though we've tried disabling a whole mod like that), and even searching Google brings up results like this: https://www.reddit.com/r/feedthebeast/comments/353970/remove_all_recipes_in_a_single_mod/

If it's not working due CraftTweaker being forked from MineTweaker3, it's JEI now, it's Minecraft 1.10 or any combination thereof, that's fine. Just trying to work out where the problem lies.

**Comment by jaredlll08** [comment]
Yea, that guy was wrong, I worked on Minetweaker3 and looked into this, and
asked Stan the original author, the functionality was never in the mod. As
for meta not working, that is weird, make another issue about that

**Comment by BigJazzz** [comment]
Gah. That's annoying. At the moment we're just renaming the .jar to .jar.dis to disable the mod, but of course it's still showing in JEI, just throwing a tooltip error. Do you have any suggestions for what I want to do? Or are my only two either individually hide each item or leave the jar renamed?

And I will do. Thanks. :)

**Comment by FangedHex** [comment]
Hi, I searched a bit and found that IJeiHelper.getItemBlacklist() is now deprecated since Jei 4.2.1 : 
https://github.com/mezz/JustEnoughItems/blob/1.11/src/api/java/mezz/jei/api/IJeiHelpers.java#L25
Maybe that's the problem ?

I tried myself to update the CraftTweaker Jei related code but it doesn't seems to work and I don't know if I'm doing something wrong or not :/

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/CraftTweaker/commit/4c0fd56e01960f86040e7e9f0de161f9d5c5f877
