### ISSUE TITLE
Wildcards not working as expected

### ISSUE THREAD

**Issue by BigJazzz** [jaredlll08/CraftTweaker#204]
#### Issue Description:
When using the wildcard to remove recipes sub-items aren't being affected

#### What happens:
Script reloads successfully, but only removes the recipe for the base item. Tooltips work as expected

#### What you expected to happen:
The base and sub items have their recipes removed

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/NBgeFHMx

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Ck553NZc
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.10.2-3.0.24

#### Your most recent log file where the issue was present: 

https://pastebin.com/XdEH0UvB

**Comment by BigJazzz** [comment]
I can confirm that even when you specify the meta ID it's not working.

`
# - Refined Storage -
# Hide mod items
#mods.jei.JEI.hide(<refinedstorage:grid:*>);
recipes.remove(<refinedstorage:grid:*>);
recipes.remove(<refinedstorage:upgrade>);
recipes.remove(<refinedstorage:upgrade:1>);
recipes.remove(<refinedstorage:upgrade:2>);
`

**Comment by jaredlll08** [comment]
I just tested this with
```
recipes.remove(<minecraft:wool:*>);
```
and
```
recipes.remove(<minecraft:stone_slab:1>);
```
and both worked perfectly, so I got no idea, it may be an issue with refined storage
