### ISSUE TITLE
Furnace recipes not showing in JEI

### ISSUE THREAD

**Issue by schismatix** [jaredlll08/CraftTweaker#205]
#### Issue Description:
CraftTweaker version: CraftTweaker-1.11.2-3.0.24
Furnace recipes do not show up in JEI. It worked with jei_1.11.2-4.2.11.251.jar but not with jei_1.11.2-4.2.11.252.jar. This has been reported to JEI but stated to report issue here.

#### What happens:
As stated furnace recipes do not show in JEI, crafting recipes do however show properly.

#### What you expected to happen:
When items/blocks shown in jei, expect the recipe for the item/block clicked on to show, this does not happen for CraftTweaker furnace recipes.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/vbHxz9mD

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/pxwJDbEK

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2228 through to forge-1.11.2-13.20.0.2294-installer
- Crafttweaker: 1.11.2-3.0.24 also 1.11.2-3.0.23

#### Your most recent log file where the issue was present: 

https://pastebin.com/LeVG6NVH

**Comment by schismatix** [comment]
Link to issue reported to JEI:

https://github.com/mezz/JustEnoughItems/issues/827

**Comment by jaredlll08** [comment]
Fixed in 1.12
