### ISSUE TITLE
.transformReplace gives ghost item.

### ISSUE THREAD

**Issue by The-Arcanian** [jaredlll08/CraftTweaker#206]
#### Intro:
I am working on a modpack and encountered a bug.

#### Issue Description:
.transformReplace is giving a ghost item.

#### What happens:
When I use .transformReplace to try and return an empty Clay Bucket from the Ceramics mod for crafting a Fresh Water from Harvestcraft, like using a normal Bucket does, it gives a ghost version of the empy Clay Bucket that disappears when I click on it.

#### What you expected to happen:
To receive a real empty Clay Bucket the Ceramics mod.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://gist.github.com/The-Arcanian/0564521bbec8597c5e63dde7ecb6cffa

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://gist.github.com/The-Arcanian/1af260d59e352ff9abde21eece892c71

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Crafttweaker: 3.0.24

#### Your most recent log file where the issue was present: 
https://gist.github.com/The-Arcanian/4bb8540865dc97beb490c002e14e5d52

**Comment by jaredlll08** [comment]
Fixed in later versions (aka 1.12)
