### ISSUE TITLE
[1.11.2]Added recipes not craftable with Tinkers' Construct installed

### ISSUE THREAD

**Issue by billybricker** [jaredlll08/CraftTweaker#207]
#### Intro:
I'm putting together a personal pack in 1.11.2 and I'm having issues with tweaked recipes not working. From my testing it appears to be a bug with the latest version of Tinkers' Construct. I've already reported it to them but was asked to post it here as well.

#### Issue Description:
I've done some testing in the pack I'm putting together and a fresh instance, only CraftTweaker, TiCon, Mantle and JEI, using the Twitch app.
With Tinkers' version 1.11.2-2.7.0.9 any recipes I add show up in JEI but it won't let me craft them. when I downgrade to Tinkers' version 1.11.2-2.7.0.6 the recipes are craftable again with no other changes made to the instance. I've included some screenshots of JEI and and crafting GUIs to show what's going on. 

http://imgur.com/a/iaUaI

#### What happens:
Any recipes I add show up in JEI but it won't let me craft them. 

#### What you expected to happen:
To be able to craft the items with the recipes I've added.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/n73La0vN

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/Gf5QY5Ky

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.0.2294
- Crafttweaker: 1.11.2-3.0.24

#### Your most recent log file where the issue was present: 

https://pastebin.com/G1UQHbMq

**Comment by jaredlll08** [comment]
Ok wait... So this only happens when TIC is installed? If so, it is their
issue, i know they said to talk to me, but I can't do anything here if an
update to their mod breaks crafting...

**Comment by billybricker** [comment]
> Ok wait... So this only happens when TIC is installed?

As far as I've seen? Yes, just the latest version.

> If so, it is their issue, i know they said to talk to me, but I can't do anything here if an update to their mod breaks crafting...

That's why I posted it to their issue tracker first. I'm not sure exactly what they're looking for from you.
https://github.com/SlimeKnights/TinkersConstruct/issues/2889

**Comment by billybricker** [comment]
Closing this because it appears to be fixed in TiC 1.11.2-2.7.0.12.
