### ISSUE TITLE
Recipes incorrectly removed

### ISSUE THREAD

**Issue by jonnygrove** [jaredlll08/CraftTweaker#208]
#### Issue Description:
For some reasons any new recipe I add in my scripts is then removed later in the log. The recipes don't work at all. Even the simplest recipes get stripped out.

Here is my script:
https://pastebin.com/Ja7dQUfn

My log file:
https://pastebin.com/Jsm6djY6

____
#### Affected Versions

- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Crafttweaker: 1.7.10-3.0.13

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.
