### ISSUE TITLE
No such valid member: nei/ ic2 error

### ISSUE THREAD

**Issue by Xireka** [jaredlll08/CraftTweaker#21]
So I updated to the latest 1.7.10 version from curseforge (CraftTweaker-Customized-1.7.10-3.0.7)

Sadly apparently something may have broken between 3.0.1 and 3.0.7 because suddenly I get 202 stuck script modifications, up from 4... and it says "no such valid member: nei" and "no such valid member: ic2" which both worked flawlessly before updating.

I don't know how to fix it and didn't find anything by googling so I thought I'd open a new issue about it.

Thanks in advance for the help.

**Comment by Xireka** [comment]
Got an answer from Jared himself on Reddit, can be closed. :)

**Comment by jaredlll08** [comment]
http://51.255.41.90:8081/view/Jared/job/CraftTweaker/10/ take your pick of game version ;)

**Comment by jaredlll08** [comment]
Just a note, you are NOT allowed to release a public pack with this version, test with it, make sure it works, tell me, and I will release

**Comment by Xireka** [comment]
Hey, I tried that version, it did fix the "no such valid member" errors but for some reason I still get over 200 stuck modifications, weirdly I even get it if normal mode has no scripts whatsoever :/

So I'm guessing something is still broken but this time no idea what it is...

**Comment by jaredlll08** [comment]
Don't reload, that should fix the errors

**Comment by Xireka** [comment]
I don't know if you got my reply but what exactly do you mean by don't reload?

I get the errors when loading into my world so I can't really choose not to reload scripts :/

I'm confused... :(

**Comment by jaredlll08** [comment]
oh wait, you are using FTBTweaks arn't you?

**Comment by Xireka** [comment]
Yes I'm using FTB Tweaks 1.0.1

**Comment by jaredlll08** [comment]
can I see your scripts?

**Comment by Xireka** [comment]
Are we looking for something specific? Cause I got like uhh 72 scripts... :/

**Comment by jaredlll08** [comment]
ok, just give me your minetweaker log file

**Comment by Xireka** [comment]
Here is the minetweaker log file.

I couldn't copy all of it because it exceeds 512kb but I copied a part of the end of it so you can see the error.

Something is weird since it just says "stuck:      "

http://pastebin.com/LmSdZMVz

**Comment by jaredlll08** [comment]
I need the whole log, could you find a place to upload it please

**Comment by Xireka** [comment]
Sure.

Here is the link to the minetweaker log file:

https://www.dropbox.com/s/788ktvgoa4yrcln/minetweaker.log?dl=0

**Comment by jaredlll08** [comment]
I'm really not sure what is going on, but usually Stuck Modifications has to do with modsbeing reloaded that shouldn't be reloaded

**Comment by Xireka** [comment]
Yeah, but it does that on first load when the world loads too, and if I reload then a whole lot get stuck.

But it only does this if I update CraftTweaker, it doesn't on the 3.0.1 version

**Comment by jaredlll08** [comment]
I think I know the issue, gimme a few hours and I'll get you a version to test on

**Comment by Xireka** [comment]
Okay awesome :)

**Comment by jaredlll08** [comment]
Mind testing with this: http://51.255.41.90:8081/job/CraftTweaker/13/
and uploading your log again

**Comment by Xireka** [comment]
Tested it, errors again, here is the new log file:

https://www.dropbox.com/s/deladxehzcogy7i/minetweaker.log?dl=0

**Comment by jaredlll08** [comment]
Ok weird, I added a check to see if it had to do with a recent change I
made to commands, resulting in [info] with no info after, but it seems not
:/

**Comment by Xireka** [comment]
Weird indeed :/

**Comment by jaredlll08** [comment]
Could you run each script separately to see where the issues are please

**Comment by Xireka** [comment]
Uhh yeah, I'll have classes soonish so I might only be able to do it later today.

Should I restart my game 72 times or just do mt reload every time for each single script?


Note: I noticed build#10 has a change which is "disabled Buildcraft", uhh I got scripts modifying buildcraft things is it the culprit maybe?

**Comment by jaredlll08** [comment]
Nope, build craft support was added in buildcraft

**Comment by jaredlll08** [comment]
Maybe do like 3 sets of scripts at a time, but definitely restart the game

**Comment by Xireka** [comment]
Oh okay so the support is built in Buildcraft now okay I see :)

Okay, I'll try 3 scripts at a time then :)

**Comment by Xireka** [comment]
I tried with three scripts, instantly got errors.

Took out all scripts except for 2, errors still happening but the Minetweaker log looks weird with only these two:

http://pastebin.com/DpS0Vafz

This is one script: http://pastebin.com/97SPECa8

This is the second one which is a Minetweaker Recipe Maker script: http://pastebin.com/TAxXF4AG

My guess is on the first one "InfinityWideChanges.zs" since in total I get around 90 stuck modifications and the second script has like 8 maybe.

**Comment by jaredlll08** [comment]
Ok, so another test version, once again, test on a script (those 2 that you tested actually will be perfect for this) and give me the log :)

http://51.255.41.90:8081/job/CraftTweaker/14/

**Comment by KurikAmudnil** [comment]
In case it helps here are a couple of minetweaker logs running with no scripts, with ModTweaker2 + Thaumcraft5 present, and using a reload to make the stuck info show.  I thought I had a time when I got the stuck stuff without a reload but can't seem to duplicate it.

* [minetweaker.log](http://pastebin.com/cj7JjJd2) from CraftTweaker1.8.8-3.0.2 + ModTweaker2 no stuck stuff, for reference
* [minetweaker.log](http://pastebin.com/GQmjLEz5) from CraftTweaker 1.8.9-3.0.7(build 14) + ModTweaker2 (with depency edit)

Note:  I also have Thaumcraft 5 present, which causes ModTweaker to try to add a couple more commands.

I find it interesting that with 3.0.7, when ModTweaker registers command entities and the second time it registers commands (dont know why it does that), the log gets empy info lines instead.

**Comment by jaredlll08** [comment]
Look, at the end of the day, Modtweaker is not meant to be reloaded, thaumcraft specifically, I found out how to block reloads now, but honestly, to go and do that for modtweaker 1.7 will be more of a mission than it is worth, so @KurikAmudnil just don't reload, simple as that.

@Xireka is getting the problem because they use FTBTweaks (one of my, more troublesome mods...), which forces a reload, so I am trying to figure out what specific mods are having trouble reloading and going from there.

**Comment by bookerthegeek** [comment]
Slightly off topic, would exiting and re-entering the world work, or do you advise a full client restart?

**Comment by jaredlll08** [comment]
Full client restart

**Comment by bookerthegeek** [comment]
Ty.

**Comment by jaredlll08** [comment]
That is however if you do not have FTBTweaks, if you have FTBTweaks, you are kinda messed for now :/

**Comment by bookerthegeek** [comment]
What we did is just modify the script locations on our server and removed the mod. Seems to work ok.

**Comment by jaredlll08** [comment]
Yea, if it isn't needed, don't use it

**Comment by Xireka** [comment]
Hey, I tested it with the newest build, build#14 with the two scripts I had and it seems we are slowly getting somewhere.

Still the same amount of stuck modifications but more info:

http://pastebin.com/yBkvhj40

**Comment by jaredlll08** [comment]
Welp I'm an idiot, this one should work, or atleast fix he empty lines completely

**Comment by jaredlll08** [comment]
http://51.255.41.90:8081/job/CraftTweaker/19/

**Comment by jaredlll08** [comment]
so the usual, test, see what happens, the log should be more / less populated now, there will be no more "INFO " or "INFO STUCK " with empty things, but there may be other stuff

**Comment by Xireka** [comment]
Tested and it is looking better and better.

Not a single stuck modification, we had 96 or so before with the two scripts.

Some empty info still.

http://pastebin.com/6MDs9wax

**Comment by jaredlll08** [comment]
Ok, so the only problem is empty lines, I'll fix them tomorrow

**Comment by Xireka** [comment]
Woohoo! \(^.^)/

Thanks for all the help, I'll add all of the other scripts back and check if it still works just as well and if there is anything I'll do the same as always and paste the log :)

**Comment by Xireka** [comment]
Tested it, in total only 4 stuck modifications (so like before) it even fixed showing what's stuck apparently.

I checked a few recipes from scripts, they definitely work.

Here is the latest minetweaker log file with all of my scripts running if you want to take a look at it.

https://www.dropbox.com/s/81navcy2ko01m6j/minetweaker.log?dl=0

**Comment by jaredlll08** [comment]
Ok, so there are still a few empty lines, I fixed those now, so now for the rest of the stuck :/ there is no real good way to do it, I got a few ideas, I'll see what I can do. It may mean another modtweaker 1.7 release

**Comment by Xireka** [comment]
I'm sorry for causing so much work with one error :$, at the same time it's good to fix it I guess for later and everything. (paradoxical feeling)

Oh a new modtweaker version maybe-maybe? Sounds cool, looking forward to it :D

**Comment by jaredlll08** [comment]
Yea don't worry, it is my fault for not testing properly xD

**Comment by Xireka** [comment]
Nah, it's alright, I know how it is, I'm working on my own private modpack but update every mod and tweak things as if it was public (for the case I ever get tempted to release it somehow), so I know how it is, it's hard to not miss an error and I'm glad I could notify you about it even though it gave you so much work :)

**Comment by Xireka** [comment]
Quick heads up. Apparently no need to make a new version of Modtweaker.

I had to create a new world because a mod added world gen and not a single modification is getting stuck and the Minetweaker log is super clean and everything works right now. :)

Thanks again for the awesome mods, for helping me out and work you put into your mods.

**Comment by Dream-Master** [comment]
Jenkins link not working any more.

**Comment by Xireka** [comment]
That's most probably because those were test versions for me to see if they fixed my issue. They aren't released versions, yet at least.

**Comment by Dream-Master** [comment]
sure. I have a jenkins too but this not disappear and I load there test builds up  too.

**Comment by jaredlll08** [comment]
The Jenkins was reset, going to add it all back up tonight

**Comment by Dream-Master** [comment]
@Xireka 
Can you send me the link or file to the lastest Testbuild because i get this error too.
Thanks

**Comment by jaredlll08** [comment]
@Dream-Master, you do not need it, @Xireka helped me solve the problem. also jenkins versions are STRICTLY for testing, NO public or private packs.

**Comment by Dream-Master** [comment]
@jaredlll08 
sure for testing only because I will replace minetweaker in my dev Test Pack with it and test my 1 Million scripts :). When you release a new Version I can change it on the Server too then.

**Comment by Xireka** [comment]
@jaredlll08, I just wanted to ask out of curiosity, since it's working and all, will you actually make a public release for the latest CraftTweaker build #19? I mean when I tested it it worked flawlessly thanks to your hard work.

**Comment by jaredlll08** [comment]
When I get time of course :)

**Comment by Xireka** [comment]
Oh okay awesome :)

**Comment by Dream-Master** [comment]
Any news when jenkins come back online?

**Comment by jaredlll08** [comment]
Jenkins is back online,just under a new IP, crafttweaker is not there as I
have had no time

**Comment by Dream-Master** [comment]
ok np.

**Comment by majix560** [comment]
I would like access to this test build so I can toy around with recipes locally.
Also, when will the fix be sent to the public version?

**Comment by jaredlll08** [comment]
It should already be released.

**Comment by majix560** [comment]
https://github.com/jaredlll08/ModTweaker/issues/330#issuecomment-237027367
It's ModTweaker 2 v2.0.0 for 1.10.2 that I've only ever used and it's the latest/only version for 1.10.2
And I still experience this issue on it.

**Comment by jaredlll08** [comment]
This has nothing to do with that problem. That problem was because I forgot
to uncomment the lines of code this has to do with other stuff.

**Comment by majix560** [comment]
doesn't chant the fact that ModTweaker 2.0.0 is the only version of ModTweaker for 1.10.2 and I experience this issue on it.

**Comment by majix560** [comment]
@jaredlll08 Meaning the fixes for this and the other issue have NOT been released for 1.10.2

**Comment by jaredlll08** [comment]
Ok, first of all, this has nothing to do with modtweaker, and you didn't linked to the other issue, which isn't relevant at all here.

**Comment by jaredlll08** [comment]
Also there isn't NEI OR IC2 support in 1.10.2. Your script is invalid because you are attempting something that isn't supported.

**Comment by majix560** [comment]
Then why wasn't it in the changelog?

**Comment by jaredlll08** [comment]
@majix560 the mod wasn't released! Do you actually want me to write every single change I make, if I add a ";" at the end of a line, do you want that in the changelog?!
If you look, CraftTweaker itself is 8 mods, due to it's submodules, I have to support all of those, I shouldn't be expected to remember every single change I make, also it is pretty obvious that there isn't support for a mod that wasn't released yet! (IC2 wasn't released on 1.10 when I ported CraftTweaker to 1.10)

**Comment by majix560** [comment]
Damn, I so sorry.
I did not mean to pester you like this.

**Comment by majix560** [comment]
I hope this doesn't come off as pestering, but IC2 is on 1.10 now and I thought the IC2 stuff on the wiki would work.
I shouldn't have been so quick to jump on you for it not working.

**Comment by jaredlll08** [comment]
It's not your fault, I'm just super busy, got school assignments, final exams in a few days, about to be moving houses, I am pretty on edge currently.

**Comment by majix560** [comment]
Well then I say it's both that _**and**_ me...though in this case I'm probably just the straw that broke the camels back.
About the fix for the other thing being released, I think with your problems you just forgot the 1.10.2 update when rolling out the new update because 1.7.10 has a new update but not 1.10.2

**Comment by majix560** [comment]
There's someone on fiver I've contacted about updating/fixing your mod (though it would be a one-off update since it's a paid-for job).
The don't feel comfortable enough since you're already working on the fixes.
The don't want to roll out a very similar mod and then the fixes he was hired for be released in the original making the money paid to them a waste.
