### ISSUE TITLE
MT Reload permission

### ISSUE THREAD

**Issue by kaal-1** [jaredlll08/CraftTweaker#211]
Using sponge with LuckPerms permission plugin, that removes the /op and uses just permission nodes.
/mt reload says you don't have permission to use this command. I googled if there is a permission node for this and couldn't find anything. Any suggestion? thank you :)

**Comment by jaredlll08** [comment]
1) use the issue template.
2) if sponge is having trouble using a command that works in vanilla forge, nothing I can do.

**Comment by kaal-1** [comment]
Sorry if I wasn't clear, I just wanted to know what is the permission node for the mt reload command. In 1.7 (when it was still minetweaker) the node was "minetweaker.mc1710.server.MCServer$MCCommand", but I couldn't find it for the updated crafttweaker version.

**Comment by phit** [comment]
sponge permission nodes are always in this structure

[`<modid>.command.<name>`](https://docs.spongepowered.org/stable/en/server/spongineer/commands.html#forge)

so /mt reload would be

`minetweaker.command.mt`

use /lp verbose if you still have trouble

**Comment by kaal-1** [comment]
Thank you very much :)
