### ISSUE TITLE
Recipe with bad name as output gives useless error output

### ISSUE THREAD

**Issue by MentalMouse** [jaredlll08/CraftTweaker#213]
#### Issue Description:

Using an undefined name in a recipe output gives a mess of numbers and punctuation which is not at
all helpful in figuring out what's wrong.

#### What happens:

When the output of a recipe uses a variable that's not defined or is based on an unresolved item,
the "error message" consists of apparently dumping the offending recipe with all items in numeric format.  (Looking at the log, the data appears, described as the "Stackmap Table".)  There seems to be no sign of the offending filename or number. though the amount of input might be scrolling it offscreen.

#### What you expected to happen:

A message to the general effect of 'File ma-v-plants-bugged.zs,  Line 29: Recipe output "flowers" is not a recognized item'.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

[ma-v-plants-bugged.zs](https://pastebin.com/qQxrWfW8)

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

[ma-v-plants-bugged-minetweaker.log](https://pastebin.com/Y5M0yN3r)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:  MC 1.11.2
- Forge:       13.20.0.2298
- Crafttweaker:  3.0.24

#### Your most recent log file where the issue was present: 
Given above

**Comment by jaredlll08** [comment]
Nothing can be done about the logging, the log file tells you what line is messed, you should be able to figure it out from there

**Comment by MentalMouse** [comment]
Actually, I was complaining that the error _in chat_ is useless.  But since you mentioned the logfile, I went back and looked at it again -- and no, the logfile does _not_ even give a line number, nor does it indicate the ID which triggered the error.

**Comment by jaredlll08** [comment]
Line 177
```
[SERVER_ABOUT_TO_START][SERVER][ERROR] ma-v-plants-bugged.zs:29 > No such static member in minetweaker.item.IItemStack: flowers
```
Shows line 29, and then it shows the ID which triggered the error "flowers"

**Comment by MentalMouse** [comment]
OK, I missed that line.  Any reason that line couldn't have gone to chat _instead_ of dumping the whole Stackmap Table to chat?

**Comment by jaredlll08** [comment]
Because it dumps all the errors to chat, you can't just say "dump this line, but not the rest"
