### ISSUE TITLE
Suggestion:  Allow "registering" a mod as optional.

### ISSUE THREAD

**Issue by MentalMouse** [jaredlll08/CraftTweaker#214]
This would be a simple way to allow scripts to survive some changes in mod configuration, without introducing full-fledged "if/else" logic.  (I assume that if you wanted real conditionals, you'd have put them in by now.)

A statement early in the file such as "modoption quark;" would register the mod name as a known mod name, but warn that it might not actually be present.  

The effect of the statement would be that _if_ the mod is _not_ present,  any recipe producing or using an item from that mod would be silently ignored; that is, it would not produce error messages for the declared mod(s) being missing.  However, it would _not_ interfere with the normal errors for statements where the mod name was misspelled, or where a mod which was _expected_ to be present, wasn't.

**Comment by jaredlll08** [comment]
Follow the issue template.

You can use an if/else statement to do this

**Comment by MentalMouse** [comment]
I have read through the tutorials linked by your Wiki -- where is the if/else statement documented?

Would you perhaps be amenable to a ~~Wikia~~ Fandom wiki for CraftTweaker, so that such things could be documented more easily by people who are familiar with the mod's sourcecode?  I'd be happy to start the wiki, if you like.

**Comment by jaredlll08** [comment]
We have a documentor, and the wiki is going to be getting an overhaul pretty soon.

```
if loadedMods.contains("modidhere") {
doStuff();
} else {
doOtherStuff()
}
```

**Comment by bookerthegeek** [comment]
I'll add that tonight to the wiki.

**Comment by MentalMouse** [comment]
While you're at it, can you add "/mt hand"?

Also, is it possible to test the version numbers for MC or a mod?

**Comment by bookerthegeek** [comment]
@MentalMouse Sure, That also can go in. As for the other I have no Idea.

**Comment by MentalMouse** [comment]
Really the wiki should cover all of the CT/MT commands and the /blockdata trick, along with the various code elements.  I hope you'll eventually get to that point, so we aren't guessing at what's been added or didn't get covered in the ancient tutorials.

**Comment by MentalMouse** [comment]
Hmm.  What wiki are you assembling the docs at?  I don't see any change on the Github project wiki.
