### ISSUE TITLE
removing smelting recipes actually duplicates

### ISSUE THREAD

**Issue by redgoblin88** [jaredlll08/CraftTweaker#216]
#### Issue Description:
i am currently attempting to create a modpack, in it, i want things to be "logical" and so glass cannot be meerley smelted in a furnace but instead in another mean which is not relevant to this bug report.
 
in order to remove the vanilla plain uncoloured glass smelting recipe, i saw on the wiki (http://minetweaker3.powerofbytes.com/wiki/Tutorial:Furnace) that "furnace.remove(<minecraft:glass>);" should do the trick.

#### What happens:

upon saving the script file with that only one line in and issuing the "/mt reload" command i go and open the inventory, check the recipes for glass.

upon checking the recipe for glass, the furnace recipe is still there but... is somehow duplicated? meaning instead of one valid recipe to make glass, there are now 2 more. upon thinking this must have been vanilla, and seeing that the reicipe was not removed, i saved the script fle and then reloaded. checking the recipes again the furnace recipe still exists and now there are three furnace recipes for sand into glass

#### What you expected to happen:

i expected the "smelting" for all "<minecraft:glass>" to be removed and only the alternative ways to "create" remain such as chisel and carpenter "unboxing"

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

*worlds biggest pastebin post*

https://pastebin.com/H6zp4gpx

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

sorry for the mess, there are alot of other script files, but the bug for the smelting recipe should ONLYbe in the "smelting.zs"

https://pastebin.com/PEmibrFK

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.1.0.2
- Forge: 12.18.3.2254
- Crafttweaker: 1.1.0.2-3.0.25

#### Your most recent log file where the issue was present: 

unfortunatelly the file is too big for pastebin, if you wish, you can ask for it within discord. (redgoblin88)

**Comment by bookerthegeek** [comment]
1) You can use gist.com for the large file.
2) https://github.com/jaredlll08/CraftTweaker/wiki/MT-Reload
