### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by noobyaran9** [jaredlll08/CraftTweaker#22]
Minecraft crashed when trying to load the world.

[crash-2016-05-07_21.12.18-client.txt](https://github.com/mezz/JustEnoughItems/files/253431/crash-2016-05-07_21.12.18-client.txt)

**Comment by jaredlll08** [comment]
Can I get your scripts please

**Comment by noobyaran9** [comment]
[script.txt](https://github.com/jaredlll08/CraftTweaker/files/254217/script.txt)
I'm using the curse launcher.
After updating the craft tweaker to the latest version (3.0.7) forge couldn't detect it.
So, I have to downgrade it back to 3.0.2 but i don't know why I have both 3.0.2 and 3.0.7 version which might caused the crash.

**Comment by jaredlll08** [comment]
That could cause the crash, do me a favour, remove 3.0.2 and only keep 3.0.7, if it still crashes, tell me, because I can't reproduce it

**Comment by noobyaran9** [comment]
<img width="431" alt="error" src="https://cloud.githubusercontent.com/assets/13598309/15111096/783461fa-1617-11e6-82fa-a27660113390.png">
Forge returned me this error when I kept only the 3.0.7

**Comment by KurikAmudnil** [comment]
CraftTweaker changed its modid from crafttweaker to MineTweaker3 and ModTweaker depends on modid crafttweaker, which is what causes that error.  I recompiled ModTweaker with a change to its modid dependency to get around that, however it has "Stuck Modification" issues with the new CraftTweaker.

**Comment by jaredlll08** [comment]
I know modtweaker is messed, I'm the dev of modtweaker... The stuck
modifications I am sorting out in another issue.

**Comment by jaredlll08** [comment]
Solved by a modtweaker update
