### ISSUE TITLE
Cannot add paintings and torches to fuel list

### ISSUE THREAD

**Issue by vpontin** [jaredlll08/CraftTweaker#221]
#### Issue Description:
Hi! I writing a script adding random fuel items to furnaces, but even with the script i still can't place torches, item frames or paintings in the fuel slot of furnace GUI.

#### What happens:
Basically, some of the items i've added to fuel registry still cant enter the fuel slot of the furnace.

#### What you expected to happen:
To be enable to put the registered items (Torch, Paintings and Item Frames) in the furnace's fuel slot.

#### Script used:
https://gist.github.com/vpontin/243ba3a154e73ae9c661fff7ce479f98

#### Minetweaker.log file:
https://gist.github.com/vpontin/0e54914e9dbb569bdb9c4862bbc11a57

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.0.2310
- Crafttweaker: 3.0.25

#### Your most recent log file where the issue was present: 

https://gist.github.com/vpontin/0e54914e9dbb569bdb9c4862bbc11a57

**Comment by jaredlll08** [comment]
I can't reproduce
http://i.blamejared.com/6gbxY.png

**Comment by vpontin** [comment]
Strange. There is no Fuel tab for painting and i still cant place the painting on the furnace:
![gif](https://user-images.githubusercontent.com/3485505/26948132-a62c11b2-4c6b-11e7-9897-e05d15d78dae.gif)

Did you use the script i've supplied?

**Comment by jaredlll08** [comment]
Yip, I used the exact script, copy pasted it from your thing. You may have another mod messing with the furnace?

**Comment by vpontin** [comment]
Well, i use CubeX2's [CustomStuff 4](https://github.com/cubex2/customstuff4) and [More Furnaces](https://minecraft.curseforge.com/projects/more-furnaces). I dont know if any of these could mess with furnace register thing.

Anyway, i'm leaving here the complete logs for my last test, in hope some clues would emerge...
https://gist.github.com/vpontin/e9d0459f6a0f75d3fd4fed3e6eadb919

**Comment by jaredlll08** [comment]
try updating JEI?

**Comment by vpontin** [comment]
I'm using the [latest bleeding build](https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2430470) of JEI (jei_1.11.2-4.5.0.287), plus the latest release of [Block Drops](https://minecraft.curseforge.com/projects/block-drops-jei-addon/files).

**Comment by vpontin** [comment]
```
[18:59:10] [Server thread/ERROR] [jei/crafttweaker]: Could not determine recipe category for recipe: class mezz.jei.plugins.vanilla.furnace.SmeltingRecipe
[18:59:10] [Server thread/ERROR] [jei/crafttweaker]: Could not determine recipe category for recipe: class mezz.jei.plugins.vanilla.furnace.FuelRecipe
[18:59:10] [Server thread/ERROR] [jei/crafttweaker]: Could not determine recipe category for recipe: class mezz.jei.plugins.vanilla.furnace.FuelRecipe
[18:59:10] [Server thread/ERROR] [jei/crafttweaker]: Could not determine recipe category for recipe: class mezz.jei.plugins.vanilla.furnace.FuelRecipe
[18:59:10] [Server thread/ERROR] [jei/crafttweaker]: Could not determine recipe category for recipe: class mezz.jei.plugins.vanilla.furnace.FuelRecipe
[18:59:10] [Server thread/ERROR] [jei/crafttweaker]: Could not determine recipe category for recipe: class mezz.jei.plugins.vanilla.furnace.FuelRecipe
```
Perharps the newest JEI broke the funcionality?

**Comment by GoryMoon** [comment]
@jaredlll08 this might be fixed by the updated jei addon in CraftTweaker that isn't released yet. 
As the errors is referring to categories and that's the big fix that we made for the recipes to work

**Comment by jaredlll08** [comment]
I spoke with the op in a pm on discord, using the same Forge versions and
everything else, it worked perfectly for me, but not him, and it isn't a
Jei thing

**Comment by GoryMoon** [comment]
Ok, didn't think it through that an jei issue wouldn't allow the actual usage of the recipe, just that I saw the category error that I know is fixed. 

On another note regarding the fuel recipes in the jei plugin, I just saw that the removal of recipes use the wrong category id in the last step so it might not work correctly.

**Comment by vpontin** [comment]
@GoryMoon its a possibility, since this category error throws in my logs (see below)
