### ISSUE TITLE
Cannot add mod block to oregen

### ISSUE THREAD

**Issue by vpontin** [jaredlll08/CraftTweaker#223]
#### Issue Description:
I'm having problems trying to add a [CS4](https://github.com/cubex2/customstuff4)'s submod block into oregen.
Despite appearing to be registred in oredict, everytime CT load the script it throw an error and stop to process the rest of the script (namely recipes placed below the oredict registers).

*Pingging @cubex2 in case it would be CS4's fault.*

#### What happens:
When i load any save i got the error showed on minetweaker.log in my chat window.
BUT when i do ` /mt oredict` they appear to be registred in oredict

#### What you expected to happen:
The recipes lines being reached by the script, and the error being supressed, since they are shown to be added on oredict.

#### Script used:
https://github.com/vicocraft/coopermod/blob/master/scripts/coopermod.zs

#### Minetweaker.log file:
https://gist.github.com/vpontin/0405118a22a7a0391f99abd79a038336

____
#### Affected Versions:

- Minecraft: 1.11.2
- Forge: 13.20.0.2310
- Crafttweaker: 3.0.25
- CustomStuff 4: 0.3.0

**Comment by jaredlll08** [comment]
You can't use oredict for output

**Comment by vpontin** [comment]
lel, i'm a fool and i cant do a simple logic. Sorry about that
