### ISSUE TITLE
Stacked Crafting 

### ISSUE THREAD

**Issue by MainFreak** [jaredlll08/CraftTweaker#224]
#### Issue Description:
I am currently working on a modpack myself and tried the function of using an stack of items in a recipe rather than just a single one (f.e. 2 furnaces in a recipe input slot instead of the usual 1) as I heared that this is recently possible. (attached a screenshot which proves that JEI noticed the recipe as valid as well)
![2017-06-05_19 07 28](https://cloud.githubusercontent.com/assets/20734190/26795068/7b18853a-4a24-11e7-95b0-dc611276821e.png)

#### What happens:
In the process of crafting the Generator the recipe only consumed 1 Furnace instead of both.

#### What you expected to happen:
The recipe should've taken away both furnaces in the process.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/esR5WCfr

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/5uq9MGUc

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: forge-13.20.0.2310
- Crafttweaker: CraftTweaker-1.11.2-3.0.25

#### Your most recent log file where the issue was present: 
https://pastebin.com/AXqY6Htw

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
Stacked crafting isn't supported by vanilla, I'm not sure where you heard that it was possible...

**Comment by MainFreak** [comment]
I heared it from a different mod author. And since the recipe technically only works if 2 furnaces are present (but only consumes 1 of them) I assumed that it's a bug.

**Comment by MainFreak** [comment]
But if you say that it is impossible to make that work I guess I won't touch that again.

Note: The mod author (who btw has working stacked crafting in his mod) was Speiger (IC2 Classics). He said it's not used in vanilla, yet technically possible. So I assumed that CraftTweaker supported it.
