### ISSUE TITLE
Feature Idea/Request

### ISSUE THREAD

**Issue by Xaikii** [jaredlll08/CraftTweaker#225]
#### Issue Description:
Set via Minetweaker that Recipes are only avaible if another Item was crafted before. 
With pressing "Recipe" for the Item it'll show which item is required to craft to be able to craft that Item.

Note: I tried my best to fit it into the template and I didn't know where else I should send a Feature Request.

#### What happens:

e.g.
Crafting a Button requires to have crafted log into wood, only then it will be possible(optional only then shown in NEI/JEI). 
I've been using Progression for that for a while, but Progression is **extremly** buggy in 1.7.10 and I can't use it anymore.

#### What you expected to happen:

Making Progressions in the Modpack much easier to set for Modpack Devs since they can set when the player is able to craft a specific item.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

Possible Look:
recipes.addX.restriction(<output>, [[input, input, input]...], <requirementCraft>);
recipes.addX.hide.restriction(<output>, [[input, input, input]...], <requirementCraft>, <requirementHide>);
recipes.restriction(<output>, <requirmentCraft>);
recipes.hide.restriction(<output>, <requirementCraft>, <requirementHide>);

1. Adding the Recipe and set a Restriction when it will be craftable.
2. Adding the Recipe, set a Restriction when it will be craftable and hide in NEI + hiding the Requirement.
3. Adding a Restriction for an item.
4. Adding a Restriction for an item and hide in NEI + hiding the Requirement.

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.7.10
- Forge: forge-10.13.4.1614
- Crafttweaker: CraftTweaker-1.7.10-3.0.13

Note: Even although I am using 1.7.10 this is a general Request, just would beg to add this to 1.7.10 too.

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
1.7.10 is no longer supported.
This is out of the scope for Crafttweaker
