### ISSUE TITLE
CraftTweaker not reloading scripts that are in subfolders.

### ISSUE THREAD

**Issue by SirWindfield** [jaredlll08/CraftTweaker#226]
#### Issue Description:
Moving scripts into subfolders fails to load them completely (even on startup).

#### What happens:
Typing `/mt reload` after I moved my scripts into subfolders under the `scripts` folder fails to reload them. All recipes are the original ones.
It looks like CraftTweaker loads the scripts (see log) but the recipes do not apply. The scripts named within the log are actually my folder names. Each folder contains one or more files, named `blocks.zs`, `items.zs` and stuff like that. 

#### What you expected to happen:
Modifed recipes should be added.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
Here is a screenshot of the folder structure:
http://prntscr.com/fgqmar

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/zi31YAA5 -> minetweaker-log
https://pastebin.com/mbuMtKNQ -> latest.log (relevant part)
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2297
- Crafttweaker: 1.10.2-3.0.25

**Comment by SirWindfield** [comment]
Looks like just having a folder within the scripts directory will make all scripts fail.

**Comment by darkhax** [comment]
This is definitely an issue, as some of my addons force you to put scripts in a sub folder to work correctly. I've spoken to Jared a few times about this and it should be possible to work this out. Hopefully he doesn't mind me marking this as a bug.

**Comment by kindlich** [comment]
I think this should work, but it needs some testing...

As I don't know how to attach a .jar file here a link...
[Could you test if that one works for you?](https://drive.google.com/file/d/0B7p3DtDkCt6BYXJpblVtV3lXMFk/view?usp=sharing)

This file is only intended for testing!!
If it does work I'll make a PR.
