### ISSUE TITLE
Mekanism Support

### ISSUE THREAD

**Issue by tyler489** [jaredlll08/CraftTweaker#228]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Attempting to add a recipy to mekanism infuser results in an error

#### What you expected to happen:
i expected to work like minetweeker

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
```mekanism.Infuser.addRecipe("OBSIDIAN", 10, <hardcoreore:dust_obsidian>, <mekanism:otherdust:5>);```
Thats the entire script

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/WfYyA9b6
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.11.2
- Forge: 13.20.0.2312 
- Crafttweaker: 3.0.25

#### Your most recent log file where the issue was present: 
Today

**Comment by jaredlll08** [comment]
Mekanism doesn't have 1.10.2 or 1.11.2 support, and even if it did, it would be in modtweaker
