### ISSUE TITLE
Parser bug when declaring value type:(ABCD:XXs|ABCD:XXb)

### ISSUE THREAD

**Issue by AboookhTheMaster** [jaredlll08/CraftTweaker#229]
#### Issue Description:
Adding value type in NBT data of an item (e.i. lvl:1**s** (short)).
Then reloading the script it prints: Parser error in lineXX ] or , expected.

#### What happens:
prints: Parser error in lineXX ] or , expected.

#### What you expected to happen:
It should work the same as if they are not present.
This makes crafting using specific enchanted books impossible, as it will not recognise the in-game enchanted book because the in-game book nbt is: "lvl:1s,id:70s", meanwhile the one in the script is "lvl:1,id:70".

#### Script used:
https://pastebin.com/raw/JpWgu5N0

#### Minetweaker.log:
[minetweaker.txt](https://github.com/jaredlll08/CraftTweaker/files/1062126/minetweaker.txt)

____
#### Affected Versions:

- Minecraft: 1.10.2
- Forge: 12.189.3.2281
- Crafttweaker: 3.0.24

#### Your most recent log file where the issue was present: 
[2017-06-08-2.txt](https://github.com/jaredlll08/CraftTweaker/files/1062128/2017-06-08-2.txt)

**Comment by jaredlll08** [comment]
You are not using /mt hand to get the nbt data.
