### ISSUE TITLE
[Question] remove single NBT items

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/CraftTweaker#23]
My Question is can I remove single items with nbt data in Craft Tweaker? I know in Minetweaker it isn't possible to remove single nbt items it will remove all items with the same id.
Mean if you have maybe 32 trees or woods items with nbt data only on one ID and you want to remove only one recipe not all.

**Comment by jaredlll08** [comment]
I'll look into it

**Comment by Dream-Master** [comment]
Thanks.

**Comment by Dream-Master** [comment]
Any new here ?

**Comment by jaredlll08** [comment]
Sorry, been really preoccupied, I got exams, this will be done when I get free time, I promise :)

**Comment by Dream-Master** [comment]
ok no np take your time and good luck :+1:

**Comment by jaredlll08** [comment]
This works, as confirmed by @Dream-Master
