### ISSUE TITLE
Minecraft crashes during startup with ModTweaker doing something that requires a mod that is not installed.

### ISSUE THREAD

**Issue by Zarepheth** [jaredlll08/CraftTweaker#230]
#### Issue Description:
Minecraft crashes during load.
Stack Trace indicates a dependency on the Forestry mod, shortly after a call to "com.blamejared.ModTweaker...".
The MineTweaker log file's content does not look anything like I would expect from the script I was hoping CraftTweaker/MineTweaker would run. (Note: that is the only script in the "Scripts" directory.)

#### What happens:
Minecraft crashes when starting up.

_A piece of the stack trace:_
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mod Tweaker (modtweaker)
Caused by: java.lang.NoClassDefFoundError: forestry/api/recipes/IFermenterRecipe
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.blamejared.ModTweaker.lambda$preInit$0(ModTweaker.java:27)
	at java.lang.Iterable.forEach(Unknown Source)
	at com.blamejared.ModTweaker.preInit(ModTweaker.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        ...
```

#### What you expected to happen:
Minecraft to finish loading, MineTweaker to generate a log file containing the outputs from my ZenScript "print" statements.

#### Script used:
[IntegrateMods.zs](https://gist.github.com/Zarepheth/0c15f2a661728a6d25248c9ab081ed90)

#### Minetweaker.log file:
[Minetweaker.log](https://gist.github.com/Zarepheth/36848e5c4727eaeb5a43a164b55bc161)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 1.11.2-12.20.0.2315
- Crafttweaker: 1.11.2-3.0.25

#### Your most recent log file where the issue was present: 
[Gist of Log Files](https://gist.github.com/Zarepheth/3115c992f99a4d2e2ea329751ae28e85)

**Comment by Zarepheth** [comment]
This issue probably belongs on the "ModTweaker" project.

**Comment by Rixius** [comment]
@Zarepheth I can confirm that without ModTweaker installed, there is no issue running CraftTweaker one 1.11.2 without Forestry installed.
