### ISSUE TITLE
[1.11.2] JEI hiding problems on server

### ISSUE THREAD

**Issue by EmosewaGamer** [jaredlll08/CraftTweaker#233]
### Issue Description:
 The 1.11.2 version of CraftTweaker it seems that hiding items in JEI doesn't work and cancels the script.

#### What happens:
   #The scripts load up as normal until they reach something that is hidden in JEI. At that point, the scripts fail.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
 https://pastebin.com/9nXG1EVL

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/Jvr1Vc8K

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 13.20.0.2315
- Crafttweaker: 3.0.26

**Comment by jaredlll08** [comment]
I need the server log please

**Comment by EmosewaGamer** [comment]
Actually, I'll first need more information myself from the people playing the pack. I guess I was having some of the problems that they weren't as I was testing it on a local host. I'll reopen the issue when I am completely sure what's happening.

**Comment by EmosewaGamer** [comment]
Ok, I now know what happened, but I may just be dumb.
