### ISSUE TITLE
[1.10.2] Autocraft .reuse()

### ISSUE THREAD

**Issue by DaNeo61** [jaredlll08/CraftTweaker#237]
Autocraft with Applied Energistic 2 is giving following Error,
Other Autocrafter like EnderIO is not accepting the Recipe and the RFTools Crafter is destroying the reuse() function and consume the item.

I even tryed with Damage values, transform back into the same item and giveback 
no chance

#### What happens:
[CHAT] Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.security.InvalidParameterException: World is null.

#### What you expected to happen:
Autocrafting with reuse should work and give no errors or consume the item

#### Script used 
> var T1Unlock = <quadrum:tier1_unlock>.reuse() ;

#### Minetweaker.log
https://gist.github.com/DaNeo61/103233ec46d991a5cce63e7a00fc016a

- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2316
- Crafttweaker: 1.10.2-3.0.26

**Comment by jaredlll08** [comment]
I need the game log.

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore
