### ISSUE TITLE
Recipe not working and crashing when looking it up in JEI

### ISSUE THREAD

**Issue by MCEventHorizon** [jaredlll08/CraftTweaker#24]
My script: http://pastebin.com/6Lpsh1Ar
Crash: http://pastebin.com/CiThmhmF

**Comment by jaredlll08** [comment]
If it crashes when looking at JEI, it is jei, actually try crafting teh recipe, give the minetwaeker.log.
Give more info, how doesn't the recipe work?

**Comment by MCEventHorizon** [comment]
But I tried crafting it without JEI and the recipe isn't there. It should be like this: stone around and glowstone in the center or any type of antiblock around and white dye in the center should give the antiblock with metadata 15(white one).

**Comment by jaredlll08** [comment]
Your recipe is in the wrong format.

Check here: 
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Basic_Recipes

**Comment by MCEventHorizon** [comment]
JEI author explained to me what I did wrong, thanks for both of your help, now it works.
