### ISSUE TITLE
GC Compatibility?

### ISSUE THREAD

**Issue by lightning02** [jaredlll08/CraftTweaker#241]
would you mind to add a compatibility? Galacticraft team would do their part from what I've read
https://github.com/micdoodle8/Galacticraft/issues/2867#issuecomment-312267056

**Comment by jaredlll08** [comment]
This would go into Modtweaker if it was going to happen, so wrong repo.

I'm only focusing on 1.12 right now, so unless they have a 1.12 version, it won't happen, saying this, they can always add the support themselves and I'll happily guide them in where to find examples and things like that
