### ISSUE TITLE
DiscordIntegration compatibility

### ISSUE THREAD

**Issue by kaal-1** [jaredlll08/CraftTweaker#245]
#### Issue Description:
Unable to run discord commands from DiscordIntegration mod, when CraftTweaker is installed on a SpongeForge server.
Maybe related:
https://github.com/SpongePowered/SpongeForge/issues/1035
https://github.com/jaredlll08/CraftTweaker/issues/110

#### What happens:
When I try to use commands in discord via DiscordIntegration mod, a CraftTweaker error is shown on console:
```
[ReadingThread/INFO] [STDOUT]: [minetweaker.mc1102.server.MCServer:getPlayer:42]: Unsupported command sender: chikachi.discord.command.DiscordCommandSender@604b7a3c defaulting to server player!
[ReadingThread/INFO] [STDOUT]: [minetweaker.mc1102.server.MCServer:getPlayer:43]: player name: @Playername
[ReadingThread/INFO] [STDOUT]: [minetweaker.mc1102.server.MCServer:getPlayer:44]: Please report to mod author if this is incorrect!
```

#### What you expected to happen:
The command be executed.

#### Script used: None.
____
#### Affected Versions:

- Minecraft: 1.10.2
- Forge: 2281
- Crafttweaker: 3.0.26

**Comment by jaredlll08** [comment]
It shouldn't stop the command from being sent.

Fixed in 1.12
