### ISSUE TITLE
Forge refuses to detect craftTweaker exists

### ISSUE THREAD

**Issue by Morpheus1101** [jaredlll08/CraftTweaker#25]
Im in the midst of making a 1.8.9 vers of my pack, however when loading, it erros saying it cant find any version of CraftTweaker, when the profile on curse sais its there and it shows in the mods folder.  Ihave removed the mod and re-installed it via curse as well as manually d/l from curse and placed it into the mods folder to which has made no difference.

**Comment by jaredlll08** [comment]
remove modtweaker, the whole modtwaeker mod is broken currently
