### ISSUE TITLE
Ability to target all items from a specific mod

### ISSUE THREAD

**Issue by Thedrummonger** [jaredlll08/CraftTweaker#252]
I was wondering if would be possible to implement the ability to target all items from a specific mod using something like [botania:*]. So for example to remove all furnace recipes for all Botania items you could use something like [furnace.remove(<botania:*>);] This would be extremely helpful in certain cases.
Thanks!

**Comment by jaredlll08** [comment]
Closed by;
https://github.com/jaredlll08/CraftTweaker/commit/e8a3308277b3fa1d9f9c02a798acc92d028c3eb8

you will still need to loop over all the items and do stuff with them from there, like so:
```
for item in loadedMods["botania"].items {
print(item.name);
}
```
