### ISSUE TITLE
Furnace.setfuel Problem

### ISSUE THREAD

**Issue by slebreton79** [jaredlll08/CraftTweaker#254]
#### Issue Description:
furnace.setfuel does not work.

#### What happens:

using furnace.setFuel to use torch as a fuel source does not work

#### What you expected to happen:

torches valid fuel source

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

furnace.setFuel(<minecraft:torch>, 1600);

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/wudVnc35
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2316
- Crafttweaker: 1.10.2-3.0.26

#### Your most recent log file where the issue was present: 

https://pastebin.com/tvwABQC4

**Comment by jaredlll08** [comment]
This is a "feature" of Forge, no burn times for vanilla items can be changed. Nothing I can do about it.

**Comment by slebreton79** [comment]
Okay I misunderstood vanilla items mean all vanilla items.  I tried moded items as well with exact same effect.
