### ISSUE TITLE
[Oversight] Mistake in the new docs

### ISSUE THREAD

**Issue by MysticAura** [jaredlll08/CraftTweaker#258]
I couldn't figure out why my script was saying my IItemStack import was null, so I started digging through your source and figured it out. In the docs it says minetweaker.item but it should say crafttweaker.item

[image for reference](https://i.gyazo.com/963a1be829083e4e509d08b97bb99a3a.png)

For the record, I love the new docs. They're so much nicer than the old ones.

**Comment by jaredlll08** [comment]
doc issues go here:
https://github.com/jaredlll08/CraftTweaker-Documentation/issues
