### ISSUE TITLE
[1.12] Crafttweaker causes The One Probe to not work on SMP

### ISSUE THREAD

**Issue by Morpheus1101** [jaredlll08/CraftTweaker#259]
#### Issue Description:

With Crafttweaker2 loaded TOP dosent work.

#### What happens:

Nothing, the information meant to be displayed by TOP dosent show

#### What you expected to happen:

The information from TOP to show

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: *.2413
- Crafttweaker:  4.0.0b2

 Nothing in log file

**Comment by jaredlll08** [comment]
Can't reproduce with CrT 4.0.1
