### ISSUE TITLE
"JEI is already defined" error in logs

### ISSUE THREAD

**Issue by DefinitelyNotFred** [jaredlll08/CraftTweaker#261]
#### What happens:
I get this error in my log even if I have no scripts in my folder. I haven't noticed any issues that seem related though.

#### What you expected to happen:
To not see an error.

#### Script used:
https://pastebin.com/raw/E7ek5ZEd (None)

#### Minetweaker.log file:
https://pastebin.com/raw/QuEjmBT8 (With no scripts in folder)

____
#### Affected Versions:
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- Crafttweaker: 1.10.2-3.0.26 
- JEI: 1.10.2-3.14.7.417

#### Your most recent log file where the issue was present: 
https://pastebin.com/raw/8QzRGh5x (With scripts)

**Comment by jaredlll08** [comment]
This isn't something you need to worry about, it is just a warning and it is caused by the JEI support being loaded twice, probably some debug code left in
