### ISSUE TITLE
[1.12] Clients cannot connect to servers with a shaped recipe added

### ISSUE THREAD

**Issue by Leonan8995** [jaredlll08/CraftTweaker#262]
#### Issue Description:
When joining a server in which both client and server use CraftTweaker to add a shaped recipe, the client's connection is refused with an error of "Fatally Missing Blocks or Items." This occurs with a system as simple as a forge client and server with only CraftTweaker and a script that adds a single shaped recipe.

#### What happens:
The client's connection to the server is refused. Errors are written in the client's logs but no error is triggered on the server.

#### What you expected to happen:
the client should join and the new recipe should both appear to the client (for instance in JEI) and work when crafted.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/sGBNSwCp

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/aWZY1WN0
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 14.21.1.2413
- Crafttweaker: 1.12-4.0.0

#### Your most recent log file where the issue was present: 
Client: https://pastebin.com/TzNmNuQ5
Server: https://pastebin.com/GALeBZ4T

**Comment by BloodWorkXGaming** [comment]
Can you please send the crafttweaker.log from both the server and the client?

**Comment by Leonan8995** [comment]
For sure!

Server: https://pastebin.com/ewqUHdbf
Client: https://pastebin.com/daMdYinF

**Comment by BloodWorkXGaming** [comment]
Should be fixed by #263

**Comment by Leonan8995** [comment]
Just pulled, built and tested and can confirm the PR works.
