### ISSUE TITLE
[1.12] Server Crash

### ISSUE THREAD

**Issue by EmosewaGamer** [jaredlll08/CraftTweaker#264]
#### What happens:
 When somebody tries to join a server they get a "Fatally missing block and items" error, while in singleplayer everything is fine. It only happens when CraftTweaker is installed.

#### What you expected to happen:
 The player to connect and everything to work fine.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/inM7iSWp
https://pastebin.com/sm73HRfA

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/FPUphB6w - server
https://pastebin.com/X9MjUAZv - client

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 14.12.1.2413
- Crafttweaker: 12-4.0.1

#### Your most recent log file where the issue was present: 

https://pastebin.com/RvxDPfDi

**Comment by BloodWorkXGaming** [comment]
It looks like you don't have exactly the same scripts for the client and the server, this is required for the 1.12 crt

**Comment by EmosewaGamer** [comment]
We do...

**Comment by rckymtnrfc** [comment]
It's a known bug and should be fixed in a future release.  See #262

**Comment by EmosewaGamer** [comment]
Well that's why I reported this. Because I knew that that was fixed today.

**Comment by jaredlll08** [comment]
can I get the server log please (game log, not crafttweaker.log)

**Comment by EmosewaGamer** [comment]
https://pastebin.com/kgBUWNN
Hmm, seems to do with it messing up advancements. Apparently removing the rail recipe caused it. Before, I had problems with the Cauldron, but at least that was adding a recipe, so I simply changed the name to minecraft:cauldron to fix it. Is there no way to fix the advancements problem?

**Comment by jaredlll08** [comment]
Your paste isn't there...

**Comment by EmosewaGamer** [comment]
Forgot a Z at the end.

**Comment by BloodWorkXGaming** [comment]
Advancement errors as safe to ignore, as those check for recipes which don't exist anymore.
I'm not really sure what thing actually it is that is causing problems. 
Can you try to remove the line that is adding/removing the recipe for the xu2 resonator?

**Comment by EmosewaGamer** [comment]
I can remove it, but because of random issue I cannot test it (for some reason no matter what happens my local host always works fine). I need someone else to test it.

**Comment by BloodWorkXGaming** [comment]
Wait? So you can log in but other people can't? Are those logs you provided from you while you were able to join the server or from the other people who weren't?

**Comment by EmosewaGamer** [comment]
Other people tested it on their local hosts multiple times and they got the crash. My local host simply acts like a singleplayer world, so no matter what multiplayer crash there is, caused by any mod to any one else's server, it never happens to me. It's pretty confusing and something that neither I can explain.

**Comment by BloodWorkXGaming** [comment]
You missed the important part of the question. From who are the log files? You or the people where it doesn't work?

**Comment by EmosewaGamer** [comment]
Everyone that tested it technically. I didn't even test it as, as I said, I cannot.

**Comment by BloodWorkXGaming** [comment]
Because that is the only line that is different between client and server in the crafttweaker.log 

Another thing you could try is giving every recipe a name, and not let crt give them names automatically

**Comment by EmosewaGamer** [comment]
What do you mean? I did give every recipe an name. As I know, it wouldn't work othwise.

**Comment by EmosewaGamer** [comment]
Did i really...? Hmm, I forgot to add names to my last minute recipes. Coukd that by itself be the problem?

**Comment by BloodWorkXGaming** [comment]
It can be a problem, but it certainly shouldn't be, as we added code that automatically assigns names based on the ingredients, and those should be exactly the same on the server and the client, so it doesn't really matter whether you add names or not

**Comment by EmosewaGamer** [comment]
Why did you say that the name was so important then?

**Comment by BloodWorkXGaming** [comment]
Because I am not very confident in the way I generate the names. If you add names to everything and that fixes it, then I know my way of creating the names is broken

**Comment by EmosewaGamer** [comment]
Ok, I guess we'll see tomorrow. I guess if it works, that will also be solving another issue.

**Comment by EmosewaGamer** [comment]
Yeah, that did not fix it. I added names to then and removed the resonator recipe and it still does not work.

**Comment by BloodWorkXGaming** [comment]
What happens if you start the game with crt installed but no scripts at all?

**Comment by EmosewaGamer** [comment]
It's all fine then

**Comment by EmosewaGamer** [comment]
We're starting to test how the files do by themselves

**Comment by EmosewaGamer** [comment]
We figured it out. Apparently you shouldn't have a colon in the name

**Comment by BloodWorkXGaming** [comment]
Ye that makes sense, a colon is the separator between modid an recipe name, so having those in there might confuse the game. 

Maybe we should add in a check to prevent it and replace it with some other character?
