### ISSUE TITLE
[1.11] /minetweaker entities - doesn't list entities from mods.

### ISSUE THREAD

**Issue by rinart73** [jaredlll08/CraftTweaker#265]
#### Issue Description:
I installed a few mods. Tinkers Construct, for example, Forestry, e.t.c.
I'm trying to get all entities that are exist in the game. I type "/minetweaker entities".

#### What happens:
In the minetweaker.log file I see only an entities from vanilla.

#### What you expected to happen:
I expected to see all entities from vanilla and mods, because this command refers to an "EntityList" which contains all entities, including mod's entities. I didn't delve in the source code too much, so maybe I'm mistaken.
I just need to know, is this bug or that works like it was intended to.

Actually I don't understand is there even support for an entities from other mods?
In the ZenScript I write
`<entity:cow>`
 And I get cow, that's fine. But how to get an entity from other mod?

#### Script used
I used chat, not script.

#### Minetweaker.log file
https://pastebin.com/kWiXn5QJ

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.1.2386
- Crafttweaker: 1.11.2-3.0.26

#### Your most recent log file where the issue was present: 

Already gave Minetweaker.log file.

**Comment by jaredlll08** [comment]
Just tested it, I can't reproduce.
http://i.blamejared.com/xkZqk.txt

**Comment by rinart73** [comment]
Can you please give your setup information like version of forge an the list of mods?
I tried to delete everything except CraftTweaker and mods that add entities. And still, all that it gives me - vanilla entities.
Can you just to not close everything instantly, please?

**Comment by bookerthegeek** [comment]
@jaredlll08, Found the issue. It is MTLib. Tested with:
- MTLib-2.0.3
- CraftTweaker-1.11.2-3.0.26
- CodeChickenLib-1.11.2-3.0.0.284-universal
- CoFHCore-1.11.2-4.2.7.15-universal
- ThermalExpansion-1.11.2-5.2.6.21-universal
- ThermalFoundation-1.11.2-2.2.5.16-universal
---
If you have MTLib, you only get Vanilla entities. Without MTLib you also get modded entities. Hope that helps.

**Comment by rinart73** [comment]
@bookerthegeek thanks. Unfortunately without MTLib any dependent mods (including ModTweaker) don't work.

**Comment by bookerthegeek** [comment]
True, but do any of those dependances add entities you are worried about?

**Comment by rinart73** [comment]
@bookerthegeek No, but those dependent mods use entities. Anyway, we just need to wait for a fix, because I looked at the MTLib code and can't find anything that can mess with entities.

**Comment by jaredlll08** [comment]
So I'm an idiot... I forgot I had an entity command in mtlib... so I added one to Crafttweaker, so it is a command conflict, Problem is, I'm not really working on 1.11.2 anymore, so you will need to get a list of entities without MTLib and it's deps, run the command save the output, add MTLib back and work with the output

**Comment by jaredlll08** [comment]
The problem is actually modtweaker, not MTLib, so just remove modtweaker, get the entity list, and readd it

**Comment by rinart73** [comment]
@jaredlll08 but I can't remove nor ModTweaker, nor MTLib, because I'm working at ModTweaker. You know, for the pull request to add TConstruct support.
Fine, the only thing that isn't working as it should besides "entities" command is EntityBracket-s. It can be replaced by another method of getting entities.
So if you have time a fix would be really appreciated, but if you don't its fine. I just hope you will accept PR when it will be ready.

**Comment by bookerthegeek** [comment]
@rinart73 what mod requires modtweaker? Could you not remove it just to get the entity list then add it back in?

**Comment by jaredlll08** [comment]
Well I'm focusing on 1.12, and I just released modtweaker 1.12, so yea...
If you are working with modtweaker, you can remove the entity dump command
and that will solve the issue.

**Comment by jaredlll08** [comment]
Also there is another way to get entities, look at some of the Crafttweaker
changelogs, I'm on mobile now, so I can't get them

**Comment by rinart73** [comment]
@jaredlll08 

> you can remove the entity dump command

Can you tell a bit more please? I can't find it.

**Comment by jaredlll08** [comment]
Interesting... It appears that I didn't add the command to 1.11, I have no
idea what is causing this then O_o

**Comment by rinart73** [comment]
@jaredlll08 okay then 😄 . I'll just try to find a way to fix it, if not, for TConstruct there will be entities without <brackets> (it will be a string "modname:entityname")

**Comment by jaredlll08** [comment]
Take note, iirc the entity bracket handler gives an entity definition, not
an entity, so you may need to do some converting there

**Comment by rinart73** [comment]
@jaredlll08 I know, for TConstruct I need an entity class ResourceLocation instance, so yeah, I do some converting in any case, when I'm getting an Entity Definition or just sting in the format that I described.

**Comment by rinart73** [comment]
@jaredlll08 ok, I found the source of the problem on the MTLib's side.
[This line](https://github.com/jaredlll08/MTLib/blob/1.11/src/main/java/com/blamejared/mtlib/MTLib.java#L28)

I think it's because MTLib loads earlier than the most of the mods. And as I see it's a good practice to add Blocks/Entities/Recipes in the `preInit()` method. So, MTLib forces CraftTweaker to reload **before** any other mod is loaded.

In the `MineTweakerImplementationAPI.reload()` we can see a `MineTweakerAPI.game.getEntities()` call. And since `MCGame.ENTITY_DEFINITIONS` is empty at that moment, it takes all entities from `ForgeRegistries.ENTITIES` and 'caches' them.

So, when everything is loaded `MCGame.ENTITY_DEFINITIONS` contains only vanilla Entities. And there is only **one** way to reload it (besides using a workaround - `ReflectionHelper`  to get `ENTITY_DEFINITIONS` list and clear it). Is to call MCGame.getEntity()` with the name of an entity from the mod. Because it refreshes `ENTITY_DEFINITIONS`.

So there is three (four?) ways I can suggest to fix this:
1. Change the behavior of `MCGame.getEntities()` method to always get entities from `ForgeRegistry`.
2. Add a method to refresh `MCGame.ENTITY_DEFINITIONS`.
3. Remove `preInit()` stuff from MTLib.
4. Use `ReflectionHelper` to get `ENTITY_DEFINITIONS` and clear it.
