### ISSUE TITLE
Error with "/crafttweaker recipes" MC 1.12

### ISSUE THREAD

**Issue by tachometer74** [jaredlll08/CraftTweaker#266]
#### Issue Description:
Getting an error when running the '/crafttweaker recipes' command (and my apologies if this is known and/or already reported...I looked around and didn't see it).

#### What happens:
[main/INFO]: [CHAT] Generating recipe list, this could take a while...
[Server thread/WARN]: Couldn't process command: crafttweaker recipes
...
[main/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

#### What you expected to happen:
A list of recipes gets generated

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
No script used

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
N/A (no data generates in the minetweaker.log

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: forge-14.21.1.2413
- Crafttweaker: CraftTweaker2-1.12-4.0.1.jar
- ModTweaker: N/A
- MTLib: N/A

#### Your most recent log file where the issue was present: 

https://pastebin.com/5UDhSc8B

**Comment by jaredlll08** [comment]
Please can you upload your crafttweaker.log anyway (unless it is 100% empty)
Also can I get a list of mods?

**Comment by jaredlll08** [comment]
Please can you upload your crafttweaker.log anyway (unless it is 100% empty)
Also can I get a list of mods?

**Comment by tachometer74** [comment]
crafttweaker.log: https://pastebin.com/uFFLQqes (I had done the /ct biomes and /ct conflicts so all that data is there, /ct recipes only gave me an error)

modlist: https://pastebin.com/ntT1NUc8 (via minecraftinstance.json...I'm working on building a modpack of my own on Curse.  If that formatting is annoying lemmie know and I'll make a cleaner one for you)
