### ISSUE TITLE
[1.10.2] Recipes are craftable but JEI does not display the added recipes

### ISSUE THREAD

**Issue by xTitanium** [jaredlll08/CraftTweaker#268]
#### Issue Description:
Trying to add recipes using various mods, the recipe does get saved and it is craftable, however JEI does not show any added recipes whatsoever, not even vanilla crafting table recipes that have been added. Done the same recipe in another instance without any mods, except Crafttweaker, Modtweaker, JEI and that recipe has worked. Here is the mod list: https://pastebin.com/M3suuDW7
#### What happens:
You can craft the recipe, but JEI does not show any added recipe.

#### What you expected to happen:
You add a recipe, JEI should display that added recipe.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://pastebin.com/WXe9b5rM

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
https://pastebin.com/kRnRw2Vf

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Crafttweaker: 1.10.2-3.0.26
- Modtweaker: 2.0.13
#### Your most recent log file where the issue was present: 

https://gist.github.com/xTitanium/ef1182ae56e1ed7c7cfd5b68decb7d9d

**Comment by jaredlll08** [comment]
I can't reproduce this. Update JEI?
