### ISSUE TITLE
[1.10],[JEI] Recipes changed by C.T. are not visible at the start of the world.

### ISSUE THREAD

**Issue by AboookhTheMaster** [jaredlll08/CraftTweaker#269]
#### Intro:
Recipes changed by C.T. are not visible in jei at the start of the world nor after any edit even after `/mt reload`.
I've already spoken to Mezz about the issue and he said that it is from crafttweaker's side.
--Issue link: https://github.com/mezz/JustEnoughItems/issues/945#issuecomment-316275493

#### Issue Description:
Recipes changed by C.T. are not visible in jei at the start of the world nor after any edit even after `/mt reload`, the default recipes are shown instead
a manual reload of jei is required.

#### What happens:
JEI is not reloaded properly at the loading phase of the game and does not get reloaded after `/mt reload`

#### What you expected to happen:
JEI is reloaded automatically after  `/mt reload`

#### Minetweaker.log file 
https://pastebin.com/raw/Fre6QJrc

____
#### Affected Versions:

- Minecraft: 1.10.2
- Forge: 12.18.3.2281
- Crafttweaker: 3.0.26
- JEI (if needed): 3.14.7.420

**Comment by jaredlll08** [comment]
List of mods?

**Comment by AboookhTheMaster** [comment]
Ok,
https://pastebin.com/raw/mC29LvkG

**Comment by jaredlll08** [comment]
can you reproduce this with only Crafttweaker?

**Comment by AboookhTheMaster** [comment]
I created a new modpack with only crafttweaker and JEI, and it is working as intended.
That's really strange, do you have any idea of what mod may be causing this error.
Thanks for helping anyway.

**Comment by bookerthegeek** [comment]
Do me a favor and drop the scripts in `../modpack/default/scripts` and see if that works please.

**Comment by AboookhTheMaster** [comment]
What do you mean by "drop".

**Comment by jaredlll08** [comment]
copy paste them

**Comment by AboookhTheMaster** [comment]
Still not working...

**Comment by jaredlll08** [comment]
can you take out "LootTweaker" and try again?
if that doesn't work, can you take out "B.A.S.E" and try?
Those should be the only 2 mods that affect how Crafttweaker is loaded

**Comment by jaredlll08** [comment]
1.10.2 isn't supported anymore
