### ISSUE TITLE
minetweaker cannot cast any[] to minetweaker.item.Ingredient

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [jaredlll08/CraftTweaker#27]
This seems to be in contradiction to what MineTweaker 3 claims (and I have used in the past) the correct syntax to be for this. I get this error from the following:

recipes.addShaped(<automation:wireC> * 8, [ [ null, null, null ], [ null, null, null ], [ [<ore:ingotCopper>], [<ore:ingotCopper>], [<ore:ingotCopper>] ] ] );

Or:

import minetweaker.item.IIngredient;
var blankLine = [ ] as IIngredient[];
recipes.addShaped(<automation:wireC> * 8, [ blankLine, blankLine, [ [<ore:ingotCopper>], [<ore:ingotCopper>], [<ore:ingotCopper>] ] ] );

Possibly a bug in the 1.9.4 port?

**Comment by jaredlll08** [comment]
Your syntax is wrong, it should be:
```
recipes.addShaped(automation:wireC * 8, [ [ null, null, null ], [ null, null, null ], [ore:ingotCopper, ore:ingotCopper, ore:ingotCopper] ] );
```

You were putting arrays instead of itemstacks
