### ISSUE TITLE
Error flood log server

### ISSUE THREAD

**Issue by darknat** [jaredlll08/CraftTweaker#270]
Hi, i have a problem with Minetweaker.

Issue Description:
In the server log, flood sentence of minetweaker overload tchat log. I can't write any command :/.

Like this : 

>  [minetweaker.mc1102.server.MCServer:getPlayer:43]: player name: @

> [minetweaker.mc1102.server.MCServer:getPlayer:44]: Please report to mod author if this is incorrect!

Pastebin Log server : https://pastebin.com/ukp9bh0q

Pastebin Log Minetweaker : https://pastebin.com/d1k7wTi5

Script : https://pastebin.com/9aCVmgZT

**Comment by jaredlll08** [comment]
Use the issue template.
