### ISSUE TITLE
[1.12] Documentation contains wrong informations about furnace support

### ISSUE THREAD

**Issue by Skillotic0703** [jaredlll08/CraftTweaker#271]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
I add a script to add a furnace recipe and I get an error! Look at line 7 of the log. I think that I know how to fix the other errors

#### What you expected to happen:
The recipe works.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/GysEusYs

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/xSi8rBj6
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12
- Forge: 1.12-14.21.1.2415
- Crafttweaker: 1.12-4.0.1

#### Your most recent log file where the issue was present: 

https://pastebin.com/64Yjqu6u

[pastebin/gist/etc link here]

**Comment by jaredlll08** [comment]
That isn't your full script, the line numbers the log is linking to are
completely wrong...

**Comment by Skillotic0703** [comment]
Yes I forgot that I deleted the lines with the localization modifications sorry!

**Comment by Skillotic0703** [comment]
But I didn't change the furnace recipe line 26

**Comment by jaredlll08** [comment]
I can't help without the full script

**Comment by Skillotic0703** [comment]
Ok I'll restart the game and give you the full evrything

**Comment by Skillotic0703** [comment]
Script : https://pastebin.com/prTESD7T
CT Log : https://pastebin.com/W87utRVi
Latest log file : https://pastebin.com/HNpH87rg

**Comment by Skillotic0703** [comment]
Is it ok?

**Comment by jaredlll08** [comment]
Yip, just realized that I made a mistake in the docs...
It is meant to be

```
furnace.addRecipe
```
Sorry about that

**Comment by Skillotic0703** [comment]
Ok thx!

**Comment by jaredlll08** [comment]
Fixed it
