### ISSUE TITLE
[Suggestion] Ability to reload JEI in game

### ISSUE THREAD

**Issue by Thedrummonger** [jaredlll08/CraftTweaker#272]
I know your probably sick of hearing about the reload function in 1.12. I know it can't be implemented and I know it's no fault of yours, but I think I have a solution that might work for most people assuming it's possible. Would it be possible to make the /ct reload command only reload JEI to reflect the changed recipes? The recipes still wouldn't work until you restarted the game but with this method you would still be able to see the changes reflected immediately when you made a new script. Feel free to say no and tell me to bugger off and I'll never speak the word reload here again, but as someone who uses crafttweaker quite a bit this would be an ideal solution in my eyes.
Thanks for your time and this awesome mod!

**Comment by jaredlll08** [comment]
Well the recipes can't be added. 

The thing that stops reloading is that the recipe registry is frozen, meaning I can't add or remove anything from it, reloading Jei will do nothing... 

Use /ct syntax

**Comment by Thedrummonger** [comment]
I think I could have worded that better... The recipe registry its self would not be touched, JEI would simple look at crafttweaker scripts and show those recipes instead of the ones in the recipe registry. Now that I think about it I realize a lot of this would be on JEIs side but if this is something feasible I would be happen to open in issue with them as well.

**Comment by jaredlll08** [comment]
It isn't really feasible and will just lead to confusion imo
