### ISSUE TITLE
Description on recipes are not nullsave

### ISSUE THREAD

**Issue by OrdinatorStouff** [jaredlll08/CraftTweaker#273]
#### Issue Description:
From @BloodWorkXGaming: "description on recipes are not nullsave"

#### What happens:
Blood was on mobile and asked me to make this issue for him to track later

#### What you expected to happen:
Blood will come back and add more comments/details/PR for this issue

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
N/A

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
N/A

____
#### Affected Versions (Do *not* use "latest"):
- Minecraft: 1.12 probably

![image](https://user-images.githubusercontent.com/6283913/28494993-07b1a60e-6ef4-11e7-95e1-7db273a14b62.png)

**Comment by BloodWorkXGaming** [comment]
Thanks! Quick explanation, will fix tomorrow, when the bracket handler
returns null it crashes on description call before being able to show
errors in the log or reaching ingame to show wrong handlers.

OrdinatorStouff <notifications@github.com> schrieb am So., 23. Juli 2017,
00:40:
