### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by ulkunderscore** [jaredlll08/CraftTweaker#274]
[Location](http://crafttweaker.readthedocs.io/en/latest/Vanilla/Variable_Types/IItemStack/#functions)

> **Maximum Damage**
> [...]
> //sets grass Hardness to 256
> pick.maxDamage = 256;

**Comment by jaredlll08** [comment]
Is it just the "sets grass hardness" part?

**Comment by ulk-underscore** [comment]
Yes. 
Although there was also 404 with the "view/edit on github" link in the pop-up bar at the bottom.

**Comment by jaredlll08** [comment]
not sure about that 404, but typo is fixed, heads up, this is the docs repo
https://github.com/jaredlll08/CraftTweaker-Documentation
