### ISSUE TITLE
Global Vars 

### ISSUE THREAD

**Issue by johnfg10** [jaredlll08/CraftTweaker#28]
i would like a global variables system in craft tweaker like @techlone has done here https://github.com/Techlone/CraftTweaker/tree/iia-edition      it allows you to have one central area for vars. which allows you to neaten your scripts up and not have to remake vars in each file. which is a lot easier if you have a lot of vars that you are addressing in multiple scripts

**Comment by jaredlll08** [comment]
@techlone want to make a PR?

**Comment by johnfg12** [comment]
it won't merge nicely as its a bit behind your current version

**Comment by jaredlll08** [comment]
@techlone, you good with me copying the changes? I'll credit you somehow

**Comment by kindlich** [comment]
Before that I guess someone needs to resolve that issue here:
https://github.com/Techlone/CraftTweaker/issues/3

**Comment by Techlone** [comment]
Guys can you wait for the weekend? I'm programmer and I can't write code whole days :\
Generally speaking I don't want to do anything else for my fork. As I said I don't like what is happening inside MineTweaker. I will fix simple bugs and no more. Sorry.

**Comment by johnfg12** [comment]
So is it OK for @jaredII08 to put your changes in crafttweaker?

**Comment by Techlone** [comment]
wtf
What is happened with CraftTweaker? Tons of strange commits. Uh. Fine.
I don't know how to resolve it... I won't to make a PR. Just do what you want with iia-edition branch I don't care.

**Comment by Techlone** [comment]
Also you can make a PR by yourself

**Comment by SirStudMuffin** [comment]
chill

**Comment by jaredlll08** [comment]
Forgot to close this when I closed https://github.com/jaredlll08/CraftTweaker/pull/31#issuecomment-313257884
