### ISSUE TITLE
Client-side crash with Crafttweaker on Server and Client

### ISSUE THREAD

**Issue by Redlotus99** [jaredlll08/CraftTweaker#29]
I recently installed Crafttweaker on my server and had no issues with the server. Once I installed Crafttweaker on my client and launched it the client crashes.

The crash log is here: http://pastebin.com/0pXPrhJ4

I am running about 100 mods and all of them work fine without Crafttweaker in. It looks like there is some sort of issue with Enchiridion from what I can tell.

Any help would be greatly appreciated.

**Comment by Voidi** [comment]
You seem to use minetweaker for Minecraft 1.10, while enchiridon compiled for 1.9.4 use specific Non-API functions from minetweaker 1.9.4.
@joshiejack you should only ose the minetweaker API
@jaredlll08 we should improve the API; and have you an idea why stan has different package names for different Minecraft versions (minetweaker.mc19.recipes.ShapedRecipeAdvanced vs. minetweaker.mc110.recipes.ShapedRecipeAdvanced) ?

**Comment by jaredlll08** [comment]
The reason that the package names are different is because it is easier to
identify what version a person is using

**Comment by joshiejack** [comment]
@Voidi I can't.

Guess I forgot to update minetweaker.

**Comment by Redlotus99** [comment]
Thanks for the help. Glad that everyone that needs to be aware of the issue knows about it.

**Comment by joshiejack** [comment]
For reference why I'm doing that, is I need access to the recipe class itself, to add support for the recipes to display in my books. Which I don't think would even be a viable thing in the api. Since that's non version specific. I can easily make mine support the 1.9 and 1.10 versions though so it's not an issue.
