### ISSUE TITLE
Can't rename grassless dirt

### ISSUE THREAD

**Issue by josephcsible** [jaredlll08/CraftTweaker#32]
In 1.7.10, I tried to do the following to make grassless dirt distinguishable from regular dirt:
```
<minecraft:dirt:1>.displayName = "Grassless Dirt";
```
However, when I did this, both regular and grassless dirt got renamed. I note that podzol kept its name, so the problem seems to be related to items with shared names, rather than to metadata handling. Also, NEI.overrideName works right, but its effects are only visible while the inventory screen is open.

**Comment by josephcsible** [comment]
I did some more research on this. The problem is that regular dirt and grassless dirt have the same unlocalized name, and CraftTweaker renames items by editing the translations from unlocalized names to localized names. To fix this, CraftTweaker should instead create a new unlocalized name for the item, then add a translation to the specified localized name.

**Comment by jaredlll08** [comment]
This wouldn't be possible since names are localized based on their unlocalized name, not the metadata, sorry :/

**Comment by josephcsible** [comment]
I think I see a way that I can make this work. Would you accept a pull request if I figure it out?

**Comment by jaredlll08** [comment]
Yip! Just don't make it too hacky please :)
