### ISSUE TITLE
Build fails in brand new fork

### ISSUE THREAD

**Issue by andrewminer** [jaredlll08/CraftTweaker#33]
I'd like to make a contribution to CraftTweaker, but I'm having trouble even getting things to build.  I've forked the repository, cloned a local copy, and installed gradle (Gradle v2.3 on MacOS X Yosemite using Java v1.8.0_31).  However, when I run any of the gradle commands specified in [readme.md](https://github.com/jaredlll08/CraftTweaker/blob/master/readme.md), I wind up with the following error and no build artifacts:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/andrew/Documents/Source/CraftTweaker/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'MineTweaker3'.
> A problem occurred configuring project ':MineTweaker3-MC1102-Mod-JEI'.
   > Failed to notify project evaluation listener.
      > org.gradle.api.artifacts.ResolvedArtifact.getId()Lorg/gradle/api/artifacts/component/ComponentArtifactIdentifier;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

There's nothing obviously wrong that I can tell, and I'm afraid I'm not familiar enough with Gradle to diagnose the problem any further.  Can you provide any assistance?

**Comment by jaredlll08** [comment]
Well that's a new one, honestly no idea, I would suggest running it again,
and seeing, if it is still an issue, I'll look around for an answer.

**Comment by andrewminer** [comment]
Running again with the command `gradle --info` adds a bunch more to the log, and the last line before the error I posted above now reads:
```
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net/mezz/jei/jei_1.10/3.7.0.218/jei_1.10-3.7.0.218.pom]
```

Trying to hit that same URL with `curl` yields:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F873D193F06F8DAD</RequestId><HostId>COHPs3kzHfl7edivU47VJf0td7pmjJL9WIm/M9LTbKHEspUD6ryABJAmP4R4fupGAqKlQtG3Tw4=</HostId></Error>
```

Sounds like I need permissions to pull data from that server?

**Comment by jaredlll08** [comment]
Weird, honestly, when this issue happens, I just try until it works, I know
it sounds stupid but there is really nothing else we can do :/

**Comment by andrewminer** [comment]
Well... I've tried maybe two dozen times over about 20min now, and there's been no change.  Moreover, 403 means that you're not allowed to access the requested resource, and is generally a permanent error.  Do you happen to know anything about the resource it's trying to access?

**Comment by jaredlll08** [comment]
Wow, when I said try again, I meant like 3 more times xD

The file it is trying to access is JEI, by @mezz

Maybe he can shed some light?

**Comment by Voidi** [comment]
There seems to be an error in builing this url, because i don't expect thas a Modjar from Mezz is downloadable from official minecraft servers. Check if version and dependcy repo are correct.

**Comment by mezz** [comment]
This is probably an issue with the build.gradle file. Either the jei repository is not specified correctly or the version requested does not exist. When gradle tries to get stuff from the minecraft url, it's as a fallback attempt.

**Comment by kindlich** [comment]
Ok, as far as I can tell, this error is located at the src/build.gradle file line 12 where it loops through every subproject and does some things...

@andrewminer: Could you try updating your gradle to the newest version? Most likely that line uses some handlers that were introduced later (since they are already at Gradle 2.14) on Gradle 2.13 it runs fine...

**Comment by andrewminer** [comment]
Thanks, @kindlich, that was it!  I'd installed Gradle with `brew install gradle`, and it gave me a very old version (2.3).  Uninstalling that and manually installing Gradle from the [gradle.org](https://gradle.org/release-candidate/) brought me up to 2.14, and everything worked great.  Thanks, everyone!
