### ISSUE TITLE
Recipes don't sync to client until /mt reload is ran

### ISSUE THREAD

**Issue by Nentify** [jaredlll08/CraftTweaker#36]
I'm using 1.10 and Sponge on the server. Removing Sponge fixes the sync issue.

If you put in the old recipe, the item shows up in the output but you can't craft it.

If you put the new recipe in, nothing shows but clicking the output gives you the item.

**Comment by jaredlll08** [comment]
Hey, can you test with a furnace recipe please, we (sponge devs and I) are trying to figure out the exact issue

**Comment by Nentify** [comment]
I added a furnace recipe server-side and it doesn't seem to work even after /mt reload

**Comment by jaredlll08** [comment]
Try smelt the item, and click the output slot after a bit. Also try adding
it client-side as well

**Comment by Nentify** [comment]
```
furnace.addRecipe(<minecraft:bone>, <minecraft:diamond>);
```

This doesn't seem to work in singleplayer either.

**Comment by jaredlll08** [comment]
Can you test that without sponge please

**Comment by Nentify** [comment]
This is in singleplayer without sponge

**Comment by jaredlll08** [comment]
uh, what Crafttweaker version?
What MC version?
other mods installed?

**Comment by Nentify** [comment]
MC 1.10.2
Forge 12.18.1.2014
CraftTweaker 3.0.10
ModTweaker2 2.0.0

Full mod list

```
Better With Mods-0.8.3-1.9.4-hotfix2
BetterBuildersWands-0.6.5-1.10r138+8595fc7
BiomesOPlenty-1.9.4-4.1.0.2052-universal
BlockRenderer-1.0.0
BuildingBricks-1.10.2-2.0.10
Calculator-1.9.4-3.0.8
Chameleon-1.9.4-2.1.6
Charset-0.3.0-pre12
Chisel-MC1.9.4-0.0.6.33
chiselsandbits-11.7
CraftTweaker-1.10.2-3.0.10
cyberware-1.9.4-1.10.2-beta-0.1.10
EnderCore-1.10.2-0.4.1.41-beta
EnderIO-1.10.2-3.0.1.75_beta
FastLeaveDecay-MC1.9.4-1.2.1
Flux-Networks-1.9.4-1.0.1
forestry_1.10.2-5.2.3.213
InventoryTweaks-1.61-58
ironchest-1.10.2-7.0.7.795
jei_1.10.2-3.7.8.234
JustEnoughResources-1.10.2-0.4.6.41
malisiscore-1.9.4-4.0.2
malisisdoors-1.9.4-5.0.1
Mantle-1.10.2-0.10.4
MCMultiPart-1.2.0-universal
ModTweaker2-2.0.0
Neat 1.3-10
notenoughwands-1.9.4-1.3.5
PackingTape-1.9.4-0.5.2
Ping-1.10.X-1.2.2.B7-universal
Quark-beta-49
refinedstorage-0.8.10
SonarCore-1.9.4-3.0.7
Souls-1.10.2-1.0.3
StacksOnStacks2-1.1.4
StorageDrawers-1.9.4-3.2.1
TConstruct-1.10.2-2.4.0.jenkins312
The Basic Elements 1.3.5-1.10.2
theoneprobe-1.10-1.0.13
thutcore-1.9.4-3.2.2
thuttech-3.0.5
topaddons-1.10.2-0.2.0
```

**Comment by jaredlll08** [comment]
This is really weird, since I have tested furnaces and it worked fine.
Is there anything else in your script?
also minetweaker.log?

**Comment by Nentify** [comment]
Oh sorry, I was doing the recipe back to front. Let me try that again.

**Comment by Nentify** [comment]
Yeah, the recipes don't sync with the furnace either. Shift clicking moves it to my hotbar but clicking the stack makes it sync into the furnace and it starts smelting.

Crafting and furnace recipes seem to sync properly without Sponge though.

**Comment by jaredlll08** [comment]
ok, so it isn't a just crafting, also can I get your scripts and the minetweaker.log file please

**Comment by Nentify** [comment]
Scripts on both client/server

```
furnace.addRecipe(<minecraft:bone>, **<minecraft:diamond>);
```

Client

```
INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
```

Server

```
INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
INFO: Adding command minetweaker
INFO: Adding minetweaker command tooltips
INFO:
INFO: Adding furnace recipe for <minecraft:diamond>
INFO:
INFO:
```

**Comment by jaredlll08** [comment]
uh, what is with `**<minecraft:diamond>` try with just `<minecraft:diamond>`

**Comment by Nentify** [comment]
Accidentally pressed Ctrl + B, I fixed it. :)

**Comment by jaredlll08** [comment]
ah ok, do me a favour, try using CraftTweaker 3.0.8, I remember making a change in 3.0.09 or 3.0.10 that may cause this, also both me and @gabizou are stumped :/

**Comment by Nentify** [comment]
Is there a version for 1.10? The 1.9-3.0.8 only works on 1.9

**Comment by jaredlll08** [comment]
oh, it technically works, atleast for a basic recipe it should work :P so just use the 1.9 version xD

**Comment by Nentify** [comment]
```
[13:57:34] [Server thread/ERROR] [FML]: The mod MineTweaker3 does not wish to run in Minecraft version Minecraft 1.10.2. You will have to remove it to play.
[13:57:34] [Server thread/ERROR] [FML]: Wrong Minecraft version for MineTweaker3
[13:57:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for MineTweaker3
Wrong Minecraft Versions!
Mod: MineTweaker3
Location: /home/minecraft/tekkify-5/mods/CraftTweaker-1.9-3.0.8.jar
Expected: [1.9,1.9]
Current: Minecraft 1.10.2


        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:239) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:511) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[13:57:34] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/tekkify-5/./crash-reports/crash-2016-07-31_13.57.34-server.txt
```

**Comment by jaredlll08** [comment]
oh, huh, well then never mind, it should have worked according... anyway, I got no idea, can you try it on a server without sponge? (I know you tried single player)

**Comment by Nentify** [comment]
I did try that and it worked fine/as expected.

**Comment by jaredlll08** [comment]
Yea, I got no idea

**Comment by Nentify** [comment]
I'll post an issue on SpongeForge's issue tracker, thanks for your help!

**Comment by Nentify** [comment]
It seems to be working now. Updated Forge and SpongeForge to 2044. I'm guessing it's either because the versions were mismatched before (2011/2014/whatever was on client) or something changed between 2011 and 2044.

Sorry about this and thanks for all your help!
