### ISSUE TITLE
Minetweaker Log almost empty without reloading the recipes

### ISSUE THREAD

**Issue by Carrots4U** [jaredlll08/CraftTweaker#40]
If you just start and run the game without doing /mt reload the minetweaker log is empty except for these two lines:

INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry

However when you reload the recipes, it actually logs all the changes made in the scripts folder.

**Comment by jaredlll08** [comment]
Can't reproduce, does this still happen?

**Comment by jaredlll08** [comment]
Since this hasn't been replied to, I'm going to assume that it is fixed
