### ISSUE TITLE
Loot changes not working

### ISSUE THREAD

**Issue by Terpo** [jaredlll08/CraftTweaker#42]
Modlist: http://blog.terpo.org/upload/mc/modlist.txt
Minecraft: 1.10.2
Forge: 1.10.2 - 12.18.1.2011
CraftTweaker: CraftTweaker-1.10.2-3.0.10
ModTweaker: ModTweaker2-2.0.0

I tried to add or remove some items to loot chests but it seems that the command and script function does not work in the current version.

_/mt loot_ give me an error 

Adding something to the script file will result in the following error. 

ERROR: executing myScript.zs: null

I followed the tutorial here: http://minetweaker3.powerofbytes.com/wiki/Tutorial:Loot

Changing mob loots too, would be awesome :D

**Comment by jaredlll08** [comment]
Loot isn't implementation in 1.8+, use the vanilla loot tables.

**Comment by Terpo** [comment]
Thanks for the tip. I did not read all the vanilla changelog^^.

**Comment by WesCook** [comment]
As far as I know, vanilla loot tables only allow for customization on a per-world basis.  So unfortunately that isn't a viable option for modpack makers.

If this is outside the scope of CraftTweaker though, perhaps the `/mt loot` command should be removed as it currently throws an error.

**Comment by jaredlll08** [comment]
It is still a planned feature
