### ISSUE TITLE
Crash with Draconic Evolution

### ISSUE THREAD

**Issue by the-creamster** [jaredlll08/CraftTweaker#44]
All i need to say is there; and i've successfuly edited a lot of other recipes already so its not my scripting errors.
https://github.com/brandon3055/Draconic-Evolution/issues/362

recipes.remove(<draconicevolution:toolUpgrade:1>);
recipes.addShaped(<draconicevolution:toolUpgrade:1>,
    [[<ore:gemLapis>, <draconicevolution:draconicCore>, <ore:gemLapis>],
    [<ore:ingotDraconium>, <tconstruct:pick_head>.withTag({Material:"electrum"}), <ore:ingotDraconium>],
    [<ore:gemLapis>, <draconicevolution:draconicCore>, <ore:gemLapis>]]);

Edit:
github doesn't display the angular brackets but they are there in the file.

**Comment by jaredlll08** [comment]
You are missing a comma after the pickaxe head.

**Comment by the-creamster** [comment]
You were too quick; caught me mid edit :)

**Comment by jaredlll08** [comment]
Also I don't recommend reloading. If it works without reloading, like
loading the world first time, then there is nothing I can / will do.

**Comment by the-creamster** [comment]
well i was in-game while writing the scripts and the reload command hasn't failed me yet; only this time.

**Comment by jaredlll08** [comment]
Well look, reloading is never supported with mods. So unless you can
reproduce this without running the reload command, there is nothing I can
do.

**Comment by the-creamster** [comment]
I am currently in the pack changing recipes and it's definitely when commenting out lines(particulary if the commented lines are those that are removing/changing

**Comment by jaredlll08** [comment]
Ok.... Do me a favor, reload the game, close it, open it, if you crash from
that, then it's an issue, if you don't. Then it is a reloading issue.

**Comment by the-creamster** [comment]
Ok reloading the world with the above pasted script segment didn't crash; now to test the pack reload. Will edit this comment with my results.

**Comment by the-creamster** [comment]
It didn't crash up world reload with the pack restarted(recipe commented out); upon un-commenting it and reloading no crash either. So it seems to be a one-off crash as i've already edited approx 45% of PSI's recipes and, a few in ender io and many more across other mods.

**Comment by jaredlll08** [comment]
ok, so that means it is a reload command crash, meaning that I can't and won't do anything to fix it, please be sure to notify the other repo as there is probably nothing they can / will do to fix it
