### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by kojul** [jaredlll08/CraftTweaker#45]
Currently the only mod that has any kind of support in CraftTweaker is JEI, I was wondering if you are going to port the other mod supports or if you are going to put them into ModTweaker. Specifically IC2 at this time, and Mekanism as well.

**Comment by majix560** [comment]
IC2 Support is already in.

**Comment by kojul** [comment]
Yeah, I noticed that... but it wasn't when I reported it, crazy.
