### ISSUE TITLE
transformReplace to "give back" empty bucket is not working

### ISSUE THREAD

**Issue by nigelkennington** [jaredlll08/CraftTweaker#47]
Using the following command:

// Make an ink sac from charcoal + water bucket (return bucket)
recipes.addShapeless(<minecraft:dye:0>, [<minecraft:coal:1>, <minecraft:water_bucket>.transformReplace(<minecraft:bucket>)]);

Causes 2 empty buckets to appear in the crafting window and "zero" charcoals (i.e. the charcoal appears with a red zero on it.

![2016-08-21_12 09 03](https://cloud.githubusercontent.com/assets/14282301/17836855/27c06700-6798-11e6-9182-2b0a41e63f8c.png)

**Comment by jaredlll08** [comment]
Remove the transformReplace on the water bucket and try again.

**Comment by nigelkennington** [comment]
That fixed it yeah. I guess the minetweaker wiki is outdated on that? It clearly states that "However, crafting this will consume the bucket." on the examples.

Thanks!

**Comment by jaredlll08** [comment]
No idea xD I just remember that buckets are always given back

**Comment by Voidi** [comment]
Recipes with buckets _sometimes_ seems to have automatic included the return of empty bucket.

**Comment by jelaw21** [comment]
I know this was closed, but I am using the claybucket mod and when I use transformReplace it behaves as that described above. But, when I remove it, the clay bucket is consumed. Any ideas?

**Comment by jaredlll08** [comment]
Clay bucket mod error, not our problem.
