### ISSUE TITLE
Error 32767

### ISSUE THREAD

**Issue by WenXin20** [jaredlll08/CraftTweaker#49]
I get this error with the ore dictionary when I reload, some of the entries I add will work, but others will not
1.1.10.2 Forge 2075

**Comment by jaredlll08** [comment]
Logs? Scripts?

**Comment by WenXin20** [comment]
Script Used (It's a .txt file so I can copy it to here, but is normally a .zs file)
[Ore Dictionary.txt](https://github.com/jaredlll08/CraftTweaker/files/454384/Ore.Dictionary.txt)
The log just says Error executing Ore Dictionary.zs: 32767

**Comment by jaredlll08** [comment]
I NEED the minetweaker.log file, if you can't provide it, I can't help.

**Comment by WenXin20** [comment]
Ok, sorry, here it is, thought you meant the minecraft log:
http://pastebin.com/ApLGrpqX

**Comment by jaredlll08** [comment]
give me ALL the scripts please

**Comment by WenXin20** [comment]
Ok, here are the other scripts:
[Custom Recipies.txt](https://github.com/jaredlll08/CraftTweaker/files/457357/Custom.Recipies.txt)
[Custom Seeds.txt](https://github.com/jaredlll08/CraftTweaker/files/457356/Custom.Seeds.txt)
[Custom Tinkers Recipies.txt](https://github.com/jaredlll08/CraftTweaker/files/457358/Custom.Tinkers.Recipies.txt)
[Custom Chisel 2 Recipies.txt](https://github.com/jaredlll08/CraftTweaker/files/457359/Custom.Chisel.2.Recipies.txt)
[Custom Furnace Recipies.txt](https://github.com/jaredlll08/CraftTweaker/files/457360/Custom.Furnace.Recipies.txt)

**Comment by jaredlll08** [comment]
ok, your scripts are riddled with errors, for example, there is no chisel minetweaker support, so yea. fix all the error, which are shown in the minetweaker.log and then see if you still have problems with the oredict.

**Comment by WenXin20** [comment]
I still get the error, even after removing the chisel and Tinker's files.

**Comment by jaredlll08** [comment]
post the log after removing the other files?

**Comment by WenXin20** [comment]
Here it is:
http://pastebin.com/Qv1T3gZm

**Comment by jaredlll08** [comment]
You need to fix the other issues in your file as well, look on line 12 of the log you gave me, issues like that, also I need the updated oredict script please

**Comment by WenXin20** [comment]
I fixed those already and still got that.
Here's the updated log and file:
http://pastebin.com/yeaH2WY2
[Ore Dictionary.txt](https://github.com/jaredlll08/CraftTweaker/files/460479/Ore.Dictionary.txt)

**Comment by jaredlll08** [comment]
ok so, whatever mod is "nex" is messed, this is NOT our fault, they are not doing a range check on their metadata items.

**Comment by WenXin20** [comment]
Ok, thanks for the help
