### ISSUE TITLE
In-Game recipe editor [dooable]

### ISSUE THREAD

**Issue by BBoldt** [jaredlll08/CraftTweaker#5]
```
<Jared> So any other bus / suggstions
<BBoldt> make an ingame recipe editor like that third party mod that made one a while back
<BBoldt> that is the key to world domination
<Jared> ugh
<Jared> That means gui's
<BBoldt> you asked for it!
<Jared> dooable though
<Jared> it would be SSP only though
<BBoldt> not a problem
<BBoldt> shall I github that issue?
<Jared> uh yea
<Jared> I guess
```

**Comment by mariodk** [comment]
if we get ingame repice editor
can it also works with repices from Machines (from furnaces/maybe even Mod´s machines that support minetweaker/modtweaker and with fluids and such)

**Comment by bookerthegeek** [comment]
Also nice would be modded crafting support.

**Comment by jaredlll08** [comment]
Yea I'm actually not 100% sure how I will pull this one off.

**Comment by bookerthegeek** [comment]
Add a button that brings up an overlay of the crafting grid, then you can just select each slot. Imagine fuzzy crafting table like selection.

**Comment by JAWSAWN** [comment]
http://minecraft.curseforge.com/projects/minetweaker-recipemaker

Maybe an ""inspiration"" for you

**Comment by johnfg12** [comment]
personly i think this would just be a waste of time since there is already a mod that does this and is just extra work

**Comment by BBoldt** [comment]
@johnfg12 A mod that only works with minetweaker... In 1.7.10...

**Comment by johnfg12** [comment]
you could ask the dev to update to craft tweaker

**Comment by JAWSAWN** [comment]
Also that mod itself has bugs.

**Comment by BBoldt** [comment]
You guys should reread the original suggestion. The suggestion was to add something similar to that mod that is built into Crafttweaker.

**Comment by dries007** [comment]
Just so you are all aware, I am (slowly) working on a 1.9 / 1.10 update/upgrade that will include more then just the vanilla crafting screen. It's taking a long time because I wish the system to be modular and allow people to make config files for other types of GUIs.
@JAWSAWN If you notice any bugs, feel free to let me know!

**Comment by jaredlll08** [comment]
Dries, just so you know, regardless of if you port MTRM to 1.9/1.10, I will
still create a native one, this isn't out of spite, it just makes it easier
when dealing with bugs.

**Comment by dries007** [comment]
Meh, I don't think its a good idea, but I won't resist :smile: 
Mainly because, if it ends up being anything like MTRM, it won't have any bug overlap (as MTRM is just a glorified text editor).

**Comment by jaredlll08** [comment]
I got some plans for it ;)
which is another reason why _needs_ to be native support ;)

**Comment by dries007** [comment]
Oh, alright. Good luck & Have fun. GUIs are a PITA as I'm sure you will find out.

**Comment by jaredlll08** [comment]
GUI's aren't that bad x)

**Comment by BBoldt** [comment]
DOOABLE? 

DONEABLE.

**Comment by aionys** [comment]
What's the command?

**Comment by jaredlll08** [comment]
/CTGUI 1
for crafting table ^
/CTGUI 2
for furnace ^

**Comment by aionys** [comment]
Okay, is it on a released build? I've got 3.0.13 and it says unknown command.

**Comment by jaredlll08** [comment]
Make sure you are typing it correctly, case sensitive

**Comment by aionys** [comment]
I've tried all of:
"/CTGUI"
"/CTGUI 1"
"/CTGUI 2"
"/ctgui"
"/ctgui 1"
"/ctgui 2"
 Same unknown command message.

**Comment by jaredlll08** [comment]
Now would be a good time to mention that it is 1.10.2 only.

**Comment by jaredlll08** [comment]
Now would be a good time to mention it is 1.10 only.

**Comment by aionys** [comment]
Now would be a good time to mention I'm on 1.10.

This is the specific version of the mod I have in my game: CraftTweaker-1.10.2-3.0.13.jar

Unknown command.

**Comment by jaredlll08** [comment]
Weird, look for it in /help
It is definitely there, I have seen other people use it.

**Comment by aionys** [comment]
I can't run help. Apparently one of the mods broke it.

[10:08:54] [Server thread/WARN]: Couldn't process command: 'help'
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeLo(Unknown Source) ~[?:1.8.0_111]

[10:08:54] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by jaredlll08** [comment]
Honestly no idea, are you on a server? This only works in single player

**Comment by aionys** [comment]
That explains it. All good.

**Comment by aionys** [comment]
Is it possible to make this work for admins on a server as well?

**Comment by jaredlll08** [comment]
No.

**Comment by jaredlll08** [comment]
No.
