### ISSUE TITLE
Loop won't work

### ISSUE THREAD

**Issue by drakray** [jaredlll08/CraftTweaker#51]
I got [this code](http://pastebin.com/2fg2qTyN)

which doesn't output error in chat, but in [minetweaker.log](http://pastebin.com/zCsmw15x)

I tried with import minetweaker.item.IItemStack; as stated on the wiki, bt I got a chat error with that

**Comment by jaredlll08** [comment]
I'm not sure on loops, but are you sure it is meant to be `for i,
thedprmlog`? Do me a favor and remove "thedprmlog" from the loop.

**Comment by drakray** [comment]
can try, but I copy/paste from the wiki and adapted my variable to be clear so.
I'll try

**Comment by jaredlll08** [comment]
ok, yea, I found the wiki thing, ok so try make the arrays var instead of val please

**Comment by drakray** [comment]
Tried that at first, retried live, same error

**Comment by jaredlll08** [comment]
ok, yea, weird, could you try the loop with just these lines? 
```
 var theMCLog = listMCLog[i];
  var theMCPlank = listMCPlank[i];
  var theDRPMPlank = listDRPMPlank[i];
print(theMCLog.displayName);
print(theMCPlank .displayName);
print(theDRPMPlank .displayName);
```

**Comment by drakray** [comment]
ERROR: modDRPMedieval.zs22 > any value not yet supported
ERROR: modDRPMedieval.zs23 > any value not yet supported
ERROR: modDRPMedieval.zs24 > any value not yet supported

**Comment by drakray** [comment]
full  .log relevant code
http://pastebin.com/5SNf4SJR

**Comment by jaredlll08** [comment]
uh, is this with
```
import minetweaker.item.IItemStack;
```
?

**Comment by drakray** [comment]
ERROR: Error parsing modDRPMedieval.zs:3 -- Invalid expression, last token: import

**Comment by jaredlll08** [comment]
uh, post your whole script please

**Comment by drakray** [comment]
`
print("---PRINT OUT--- DRPMedieval");
import minetweaker.item.IItemStack;
##Mods Requirement
# - NULL

#------------------------------------------------------------------------------------------------------------------------------------------------------------#

var listDRPMFirewood = [<drpmedieval:Firewood:0>, <drpmedieval:Firewood:1>, <drpmedieval:Firewood:2>, <drpmedieval:Firewood:3>, <drpmedieval:Firewood:4>, <drpmedieval:Firewood:5>] as IItemStack[];
var listMCLog        = [<minecraft:log:0>       , <minecraft:log:1>       , <minecraft:log:2>       , <minecraft:log:3>       , <minecraft:log2:1>      , <minecraft:log2:0>]       as IItemStack[];
var listMCPlank      = [<minecraft:planks:0>    , <minecraft:planks:1>    , <minecraft:planks:2>    , <minecraft:planks:3>    , <minecraft:planks:5>    , <minecraft:planks:4>]     as IItemStack[];
var listDRPMPlank    = [<drpmedieval:Plank:0>   , <drpmedieval:Plank:1>   , <drpmedieval:Plank:2>   , <drpmedieval:Plank:3>   , <drpmedieval:Plank:4>   , <drpmedieval:Plank:5>]    as IItemStack[];
var woodAxe = <minecraft:wooden_axe>.anyDamage().transformDamage();
var stonAxe = <minecraft:stone_axe>.anyDamage().transformDamage();
var ironAxe = <minecraft:iron_axe>.anyDamage().transformDamage();
var goldAxe = <minecraft:golden_axe>.anyDamage().transformDamage();
var diamAxe = <minecraft:diamond_axe>.anyDamage().transformDamage();
for i, theDRPMLog in listDRPMFirewood {
  var theMCLog = listMCLog[i];
  var theMCPlank = listMCPlank[i];
  var theDRPMPlank = listDRPMPlank[i];
  print(theMCLog.displayName);
  print(theMCPlank.displayName);
  print(theDRPMPlank.displayName);
}
`

**Comment by jaredlll08** [comment]
put that import at the beginning of the file please

**Comment by drakray** [comment]
seems to work as intended, at last! :D
should have a disclaimer somewhere to say that IMPORT must ALWAYS be at absolute begining of file, even before PRINTs

Thank you!

**Comment by drakray** [comment]
Final file, al working well, fully optimized
http://pastebin.com/raw/UTBmuw8i
