### ISSUE TITLE
Primitive Configurable Items

### ISSUE THREAD

**Issue by TinkerWorX** [jaredlll08/CraftTweaker#52]
There have been several mods that do this, but they all fall behind or get unused. It would make sense for CraftTweaker to do this, since it's already all about tweaking.

Basic usage would be similar to how things are already tweaked. Register an item, give it a texture and a name. The item wouldn't do anything on it's own, but would be configurable to be used in other things as an intermediary product. Would be great for modpack creators which are already the major users of tweaking mods.

**Comment by jaredlll08** [comment]
Take a look at ContentTweaker, it already does this, albeit I need to update it to 1.10.
Anyway, we load scripts too late to do this, so unfortunately, it won't happen in this mod.

**Comment by TinkerWorX** [comment]
I swear, trying to Google a mod that does this is impossible. Any ETA or status on getting it updated to 1.10?

**Comment by jaredlll08** [comment]
https://minecraft.curseforge.com/projects/contenttweaker
when @AKTheKnight gets his act together :P
