### ISSUE TITLE
Port Immersive Engineering support

### ISSUE THREAD

**Issue by majix560** [jaredlll08/CraftTweaker#54]
Please port Immersive Engineering support over as Immersive Engineering is available for 1.9.4/1.10.2

**Comment by jaredlll08** [comment]
I didn't add Immersion engineering support. Also this is the wrong repo for
mod support. Also like I said, I have never added it, it is upto Blu to add
it.

**Comment by majix560** [comment]
sorry, I didn't realize CraftTweaker switched to a different github.
Because if it still uses this github repo, I posted in the correct place.
Immersive Engineering support was in MineTweaker, not ModTweaker.

**Comment by majix560** [comment]
Okay, sorry.
https://github.com/BluSunrize/ImmersiveEngineering/issues/1395
