### ISSUE TITLE
In-Game recipe maker

### ISSUE THREAD

**Issue by Xiaminou** [jaredlll08/CraftTweaker#55]
Would it be possible to have an in-game GUI to modify recipes similar to [MineTweaker RecipeMaker](https://minecraft.curseforge.com/projects/minetweaker-recipemaker?gameCategorySlug=mc-mods&projectID=226294)?

Writing all the stuff manually is just painful, using this is much faster.

**Comment by jaredlll08** [comment]
This is literally the first issue on crafttweaker. LOOK BEFORE ASKING
