### ISSUE TITLE
[1.10.2] [Bug] Recipes don't work. . . Literally.

### ISSUE THREAD

**Issue by SnowShock35** [jaredlll08/CraftTweaker#56]
Hello,

I believe to have found a bug in CraftTweaker for Minecraft 1.10.2. Here are the details. . . 

### Important Information

* Minecraft 1.10.2
* Minecraft Forge 12.18.1.92
* CraftTweaker 3.0.11
* Additional Mods:
    * Mod Tweaker 2 2.0.3

### Issue Description

Recipes on either `/mt reload` or world load give a error.

### Issue Media

![Issue Screenshot #1](http://ss.snowshock35.com/2016/09/1474482693-857004da.png)

```
recipe.addShaped(<minecraft:diamond>, [[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>]]);
```

**Comment by jaredlll08** [comment]
Where is the error? I can't help without the minetweaker.log file, also why include a picture of your scripts?

**Comment by SnowShock35** [comment]
. . . woops xD

**Comment by SnowShock35** [comment]
Fixed 😛
