### ISSUE TITLE
 better support for Flaxbeard Steam Power Mod?

### ISSUE THREAD

**Issue by trollworkout** [jaredlll08/CraftTweaker#61]
I noticed Flaxbeard Steam Power Mod is been always half supported and at the same time half broken . Some versions have support adding liquids but no melt or drop recipes, other versions support adding melt recipes or drop but not new liquids and other versions don't work at all. 

I am interested in the ability to add new alloy liquids and the ability to add new clay molds and create new items in different shapes .

**Comment by jaredlll08** [comment]
We have removed support for FSP, they add support themselves.

**Comment by trollworkout** [comment]
aight :)
