### ISSUE TITLE
Armor not adjusting properly when using AttributeModifier

### ISSUE THREAD

**Issue by jelaw21** [jaredlll08/CraftTweaker#62]
I have an interesting problem that may be CraftTweaker related.  Here is the script I am running: 

recipes.remove(<minecraft:iron_helmet>);
recipes.addShapeless(<minecraft:iron_helmet>.withTag({AttributeModifiers:[{AttributeName:"generic.armor",Name:"generic.armor",Amount:30,Operation:0,UUIDLeast:176584,UUIDMost:798203,Slot:"head"}]}), [<minecraft:stick>, <minecraft:stick>, <minecraft:stick>]);

So, as you can guess, I am making an iron helmet with 30 armor. Now, it works. It creates the helmet, but when I put it on, I get no shields and a fall test verifies that I am not protected. Any ideas? I used MCStacker to create the attribute modifier command. 

[minetweakerlog.txt](https://github.com/jaredlll08/CraftTweaker/files/498316/minetweakerlog.txt)

**Comment by jaredlll08** [comment]
try make the armor value smaller

**Comment by jelaw21** [comment]
Tried with 20, nada. Also looked at wiki about armor modifications and it
says it supports up to 30.

**Comment by jaredlll08** [comment]
uh, give a link to that wiki post thingy?

also maybe just try something like 5 for the armor thing?

**Comment by jelaw21** [comment]
http://minecraft.gamepedia.com/Attribute

http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/command-blocks/2651625-attribute-tutorial-1-9-1

**Comment by jelaw21** [comment]
And just tried 5, nada.

**Comment by jaredlll08** [comment]
hhm, I got no idea, but I highly doubt this is a minetweaker issue. try spawn the item ingame using the same data tag and see if it works

**Comment by jelaw21** [comment]
How to do that, command is too long?  use command block?

**Comment by jaredlll08** [comment]
try a command block, if that doesn't work, then I'm not sure.

also where is UUIDLeast and UUIDMost gotten from? or are they just a random value?

**Comment by jelaw21** [comment]
Yep, doesn't work that way either.

**Comment by jelaw21** [comment]
I'm not sure, I'm using MCStacker and it seems like a random number. Wiki's
aren't very clear on that part. It has something to do with the way the
armor stacks. One source says if the UUID's are different for the same item
with the same attribute, the higher one is taken. If they are in the same
range, they stack.  Not sure how to even find the UUID of the standard
items.

**Comment by jaredlll08** [comment]
looking at stuff from a wiki, I think the UUID dictates what slot it gets applied in, lower the UUIDLeast to 0 and try?

**Comment by jelaw21** [comment]
That produced an iron helmet with no data tag, but still gave 2 (1 shield)
armor.

**Comment by jaredlll08** [comment]
I honestly got no idea, but considering it didn't work when spawned from a command block, it is not our issue. sorry.
