### ISSUE TITLE
Tinkers' Basin scripts seem to suffer similar fate of casting tables

### ISSUE THREAD

**Issue by Darkosto** [jaredlll08/CraftTweaker#63]
Hey Jared,

I'm having a bit of trouble getting a basin script to work in 1.10.2

It seems to be doing the same thing the casting tables did before your recent fix. Is there a new script syntax? I want to make sure I'm not doing anything wrong. I've tried restarting the client to make sure it wasn't a reloading issue and it still threw the same error.

Craftweaker Version: 3.0.11
Forge: 2094

**Comment by jaredlll08** [comment]
This is a modtweaker issue btw, anyway, could I get the modtweaker version,
scripts and minetweaker.log file please.

**Comment by Darkosto** [comment]
Whoops, I apologize!

Version: 2.0.3 

Here is the script I'm attempting to use: 
mods.tconstruct.Casting.addBasinRecipe(<tconstruct:slime_congealed:1>, <liquid:blueslime> * 500, null, false, 20);

Here is the modtweaker log:
http://pastebin.com/ZJaZ2w6k

Thank you for the help! Let me know if you need anything else, sir :D

**Comment by jaredlll08** [comment]
Its fine :P I get a lot of people with modtweaker issues here, thankfully I maintain both mods >.>
