### ISSUE TITLE
CraftTweaker refuses to load without JEI installed

### ISSUE THREAD

**Issue by jaredlll08** [jaredlll08/CraftTweaker#65]
when loading crafttweaker without JEI this happens:
https://paste.ee/p/hQBkX

the only method I can think of that would fix this is by removing these lines of code:
https://github.com/jaredlll08/CraftTweaker/blob/master/MineTweaker3-MC1102-Mod-JEI/src/main/java/minetweaker/mods/jei/JEI.java#L57-L65

or maybe checking to see if JEI is loaded, then doing that, but that may require reflection.

@tommyTT since you were the one to add the lines, got any input?

**Comment by tommyTT** [comment]
In my opinion, the whole JEI module shouldn't be loaded if JEI is not installed. The same goes for any module that depends on an external mod. Otherwise a crash cannot be avoided.

**Comment by jaredlll08** [comment]
yea, it shouldn't be loaded, I got no idea why it is getting loaded :/
