### ISSUE TITLE
Reloading scripts duplicate harvest_festival offers

### ISSUE THREAD

**Issue by gilfort** [jaredlll08/CraftTweaker#66]
I used the mods.harvestfestival method to implement 2 new items for the general store. 
(mods.harvestfestival.Shops.addPurchasable("harvestfestival:general", <minecraft:egg>, 50);
mods.harvestfestival.Shops.addPurchasable("harvestfestival:general", <minecraft:apple>, 25);)

As soon as i use /mt reload there will be a warning, that these items have been registered again with a different id and after that they will be doubled in the shop. 

latest.log: http://pastebin.com/8t3VZ5zx

**Comment by jaredlll08** [comment]
Not my problem, go speak to harvest craft about fixing their support.
