### ISSUE TITLE
Internal Error when joining without JEI

### ISSUE THREAD

**Issue by Eufranio** [jaredlll08/CraftTweaker#67]
When I try to join a server with MineTweaker, but not JEI, I am disconnected with Internal Serve Error.
Log: http://hastebin.com/hitobubuvu.rb
Minecraft 1.10.2
Forge 12.18.2.2107
CraftTweaker 3.0.12

**Comment by jaredlll08** [comment]
already fixed.

**Comment by Eufranio** [comment]
Thanks! 😄
