### ISSUE TITLE
Errors with Subdirectories in \scripts folder

### ISSUE THREAD

**Issue by Shadows-of-Fire** [jaredlll08/CraftTweaker#68]
It would make a bit more sense to either support or ignore subdirectories, but if one exists in \scripts, this is thrown:
https://gist.github.com/Shadows-of-Fire/bda4b847ee9a1398661308eeb16093f4

**Comment by Cronosus** [comment]
same problem
+ stopped working with chisel
[CHAT] ERROR: ?:1 > No such member: chisel

**Comment by jaredlll08** [comment]
Your issue has nothing to do with his issue.
