### ISSUE TITLE
jei doesn't update after reloading

### ISSUE THREAD

**Issue by jaredlll08** [jaredlll08/CraftTweaker#69]
I'll know what this means when I get to it

**Comment by jaredlll08** [comment]
Try loading in postInit instead of server starting, add "before:JEI"
test it
make jei not reload on the first load

**Comment by mezz** [comment]
Alrgiht I got a bit lost with the build system so I'll hand it off to you...
Found a couple other things:
CraftTweaker should only reload JEI after all the addons get the postReload event, so they can make any changes before JEI reloads.
`minetweaker.mods.jei.JEI`'s `JEIHideItemAction` should always check for `jeiHelpers != null` and either do the action or add it to `apply`. That way it will handle things no matter when JEI is loaded. It should also implement the undo that way.

**Comment by jaredlll08** [comment]
Would that fix the problem though? Of it not reloading the first time

**Comment by mezz** [comment]
No, they're just separate things I ran into.

**Comment by mezz** [comment]
I ended up moving JEI's loading to `FMLLoadCompleteEvent` because it's the last client-side loading event that still shows a progress bar. This should help make it compatible even with mods that do things in postInit.

**Comment by darkphan** [comment]
As it stands now, JEI version 3.12.8.328 is the last one that works with recipes changed via CraftTweaker. Hopefully this gets resolved soon :)

**Comment by mezz** [comment]
JEI now updates after reloading, but CraftTweaker must not reload JEI when it starts up.
This means doing most things before JEI in `FMLLoadCompleteEvent`.
Right now the CraftTweaker reload of JEI is causing some people to disconnect from servers because it takes too long.

**Comment by gdude2002** [comment]
Very excited about the prospect of a fix for this. This issue gets my vote!

**Comment by kaitoyuuki** [comment]
I can't even get on my server. I really hope this is fixed soon.

**Comment by YOYOK9** [comment]
Any news on how the fix is coming?

**Comment by jaredlll08** [comment]
Any news on when people will stop badgering me about this fix?
IT IS COMING! I am working with @mezz to fix it, but he is doing finals, and I'm going away for a week, it will be fixed as soon as possible.

**Comment by gdude2002** [comment]
It had been over a month since the comment before YOYOK's.

---

If the emails are a problem, lock the topic until you're back, maybe? Would also keep your comment about being away visible.

**Comment by jaredlll08** [comment]
I understand it is high priority, but you need to understand, in that month, I had my finals until the 25th of November, half a month of not being able to work on it. After that, I decided to take a week break to relax after those exams, the past week I have been trying to fix it, after many failed attempts, I contacted mezz to find out if we could work something out, and he had his finals, so yea,i understand it is high priority, but so is my mental state.

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/CraftTweaker/commit/7f4e59d9df8b8f70702904d80ee72a179f107a22
