### ISSUE TITLE
[missing feature] remove all recipes.

### ISSUE THREAD

**Issue by meelock** [jaredlll08/CraftTweaker#70]
A feature of MineTweaker appears to not be working as i thought it should, this feature is the feature of removing all the recipes from a single mod, like this:

`recipes.remove(<minecraft:*>);`

I hope this isn't intentional, since it would be nice to be able to remove all the recipes from a mod and re-add them while making heavily tweaked modpacks. (I'm working on [this](https://minecraft.curseforge.com/projects/darkmill/))
- meelock

**Comment by jaredlll08** [comment]
This was never a feature. And most likely never will be, put all of the items in an array, loop through the array removing them.
