### ISSUE TITLE
<item>.displayName = "new name" doesn't rename items

### ISSUE THREAD

**Issue by belathus** [jaredlll08/CraftTweaker#73]
As per http://minetweaker3.powerofbytes.com/wiki/Tutorial:Item_Renaming, it should, but it doesn't. I did not get any error messages when I attempted to do this.

Though, it could be because I'm doing this on the server and not on the client.

**Comment by jaredlll08** [comment]
Renames have to be done on the client,

**Comment by belathus** [comment]
Whelp, putting it on the client and restarting the client didn't work either. Neither is trying to remove something from a misspelled oredictionary entry. Here's the whole script; only the last three lines work:

<morebees:diamondFragment>.displayName = "Diamond Fragment";
<morebees:emeraldFragment>.displayName = "Emerald Fragment";
<ore:nuggetDiamod>.remove(<morebees:diamondFragment>);
<ore:nuggetDiamond>.add(<morebees:diamondFragment>);
recipes.addShapeless(<morebees:diamondFragment>*9,[<ore:gemDiamond>]);
recipes.addShapeless(<morebees:emeraldFragment>*9,[<ore:gemEmerald>]);
