### ISSUE TITLE
NoClassDefFoundError: minetweaker/api/item/IItemStackAny

### ISSUE THREAD

**Issue by flapee** [jaredlll08/CraftTweaker#74]
acording to [MT3 - Control structures](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Control_Structures) this should work
var myIngredients2 = [<minecraft:stick>, <ore:plankWood>] as IIngredient[]; 
but results in NoClassDefFoundError

**Comment by jaredlll08** [comment]
You need to import it.
