### ISSUE TITLE
Renaming things via CraftTweaker's displayName doesn't work on servers

### ISSUE THREAD

**Issue by belathus** [jaredlll08/CraftTweaker#75]
Opening a new issue, since it doesn't work either way.

**Comment by jaredlll08** [comment]
Crafttweaker version?

**Comment by belathus** [comment]
3.0.11, Minecraft version 1.10.2.  I can update to 3.0.13 in a few hours and try again, if you'd like.

**Comment by jaredlll08** [comment]
Always update before reporting issues

**Comment by belathus** [comment]
Naturally.

**Comment by belathus** [comment]
I can't even join a world with the latest version of CraftTweaker.

http://pastebin.com/TFiky3K0

**Comment by belathus** [comment]
Bleh. Okay, updating a few other mods fixed that, and the renaming works. So, this was a non-issue.

**Comment by belathus** [comment]
So, renaming seems to work in SSP, but not on a server, even if I have the script written client-side. I joined SSP, saw it worked, then joined the server and checked, and saw that the item had the original name.

**Comment by frank89722** [comment]
Have same issue.
This only happening on JEI install.
http://pastebin.com/P7z4rzZc

**Comment by jaredlll08** [comment]
@frank89722 how does your issue have anything to do with this issue?

**Comment by jaredlll08** [comment]
@belathus forgot to ask, what JEI version?
Try this version
3.12.8.328

**Comment by belathus** [comment]
Pretty sure I was using 3.13.0.341 when I wrote this. I'll try that version tonight.

**Comment by belathus** [comment]
Yeah, looks like this problem does not exist with JEI version 3.12.8.328.

**Comment by belathus** [comment]
... and it appears to work fine with JEI version 3.13.0.341 and CraftTweaker 3.0.14. I think I can close this.
