### ISSUE TITLE
[1.10.2] Crash when using mod Chisel

### ISSUE THREAD

**Issue by MrBlackswordsman** [jaredlll08/CraftTweaker#76]
I have posted this on Chisels issue tracker and they said it was a Minetweaker problem.

https://github.com/Chisel-Team/Chisel/issues/289

**Comment by jaredlll08** [comment]
Wrong repo.
https://github.com/jaredlll08/ModTweaker

**Comment by MrBlackswordsman** [comment]
Well I'm not using Modtweaker, I'm using Crafttweaker. My Crash Report says MInetweaker, and the list of mods shows Crafttweaker. :(

**Comment by jaredlll08** [comment]
try with this version please
http://blamejared.com:8080/job/CraftTweaker/50/

**Comment by MrBlackswordsman** [comment]
The version you had me download, along with the newest version of Chisel works! Thanks a bunch for getting whatever was causing it figured out.

**Comment by jaredlll08** [comment]
This is fixed now
