### ISSUE TITLE
scripts dont load correctly on Servers..

### ISSUE THREAD

**Issue by Patrick1005de** [jaredlll08/CraftTweaker#78]
my script isn't loading correctly when my player join on my Server.
After a restart with "/mt reload" the script works..

**Comment by jaredlll08** [comment]
What version?

**Comment by Patrick1005de** [comment]
Version: 1.7.10 - 3.0.13

**Comment by jaredlll08** [comment]
other mods?

**Comment by Patrick1005de** [comment]
There are all my mods: http://imgur.com/a/xy3bt

**Comment by jaredlll08** [comment]
It has to do with FTBTweaks / FTBUtils, either way, both those mods, and this mod don't support 1.7.10 anymore, sorry.

**Comment by Patrick1005de** [comment]
But when I uninstall FTBTweaks and FTBUtils, the script also dont load.

**Comment by jaredlll08** [comment]
Yes, because FTBTweaks is loading the scripts from a different directory.

**Comment by Patrick1005de** [comment]
How can i use Minetweaker now ? The script dont load, i must reload the script everytime when a new player join..
