### ISSUE TITLE
Suggestion: Copy inventory listing to clipboard

### ISSUE THREAD

**Issue by mrtopf** [jaredlll08/CraftTweaker#79]
It would be very useful if /mt inventory would also copy the output to the clipboard so I can easier put items into script (without doing 9 /mt hand). Alternatively a hotbar only command would also be helpful or dumping it into the log. 

Besides that thanks for making this happen in 1.10 :-)

**Comment by jaredlll08** [comment]
well /mt inventory already logs everything in the inventory, look in minetweaker.log.

How would copying all of them to the clipboard work? IF it did that, it would just be a long string like
```
<minecraft:stick>, <minecraft:dirt>, <minecraft:diamond>
```
You would still need to copy paste them to get the individual item

**Comment by mrtopf** [comment]
I did look in minetweaker.log and just checked again but there was no inventory listing. I actually outputs it in chat (where I cannot even see it all and I cannot copy/paste it). So far I only see /mt recipes logging to the logfile. Is this a bug? 

As for copying: I would then clear my inventory and only have those items in it which I want to use for that recipe. So that string would actually be helpful (I might still edit it into triplets of course but that's still faster than doing 9 times /mt hand). I don't mind though if it's in clipboard or logfile although clipboard would save one step.
