### ISSUE TITLE
[1.7.10] NEI won't work in the first join

### ISSUE THREAD

**Issue by Eufranio** [jaredlll08/CraftTweaker#82]
In my server, I have scripts doing NEI functions (like hiding from NEI, renaming, etc). But every time a player joins by the first time in the server (first time after open the pack), the NEI scripts aren't loaded. To get this working, I need to workaround, reloading the scripts after the login with /mt reload, or reconnecting to the server. 

I don't know if it's intentional or not, but it's weird having to reload the config every time a player joins the server... I think you could fix this, just adding a 2nd attemt to load NEI scripts right after player login. Thank you, and nice work you do with CraftTweaker!

**Comment by jaredlll08** [comment]
NEI has always been broken.
Also 1.7.10 support has been dropped.
Sorry.

**Comment by Eufranio** [comment]
The fix is simply reloading it client-side :/
