### ISSUE TITLE
[Bug] Recipe removed from JEI but still craftable

### ISSUE THREAD

**Issue by MysticAura** [jaredlll08/CraftTweaker#87]
MC: 1.10.2
Forge: 2121
Mod: CraftTweaker-1.10.2-3.0.14
Relating to: SilentsGems-1.10.2-2.1.2-81

Script Used:
`recipes.removeShaped(<silentgems:Pickaxe>, [[<*>, <*>, <*>], [null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);`
`recipes.removeShaped(<silentgems:Axe>, [[<*>, <*>], [<*>, <ore:stickWood>], [null, <ore:stickWood>]]);`
`recipes.removeShaped(<silentgems:Shovel>, [[<*>], [<ore:stickWood>], [<ore:stickWood>]]);`
`recipes.removeShaped(<silentgems:Sickle>, [[null, <*>], [<*>, <*>], [<ore:stickWood>, null]]);`
`recipes.removeShaped(<silentgems:Sword>, [[<*>], [<*>], [<ore:stickWood>]]);`

Issue: The recipes for the tier 1 tools disappears properly from JEI, however when I try and craft the same recipe it works as if it was never removed.

**Comment by jaredlll08** [comment]
Its a bu with newer versions of JEI.
There is ALREADY an issue regarding this, please look before posting.

**Comment by MysticAura** [comment]
While you and mezz resolving the reload issue may fix my issue, there's no way without reading every issue completely that I would've known it was related to my issue. My game reloads recipes fine.. it's only that Silents doesn't actually get it's altered recipes removed, only hidden. All my other recipes work as intended. A reference to the related issue would've also been helpful.

I hope this issue gets resolved soon. Mezz has made great strides in improving JEI performance lately, so downgrading a pack and server until  this is resolved is not a practical option.
