### ISSUE TITLE
Using /mt hand on dedicated server still throws X11 error

### ISSUE THREAD

**Issue by HanFox** [jaredlll08/CraftTweaker#9]
Using CraftTweaker-Customized-1.7.10-3.0.1.jar.

This issue still occurs: https://github.com/stanhebben/MineTweaker3/issues/146

**Comment by jaredlll08** [comment]
Could you try with the latest crafttweaker on curse please, if it is still there, I'll look into it more

**Comment by HanFox** [comment]
Sadly the error still occurs on a completely clean MC1.8.9 server with Forge 1763 using CTv3.0.2.

**Comment by Tsyklop** [comment]
same problem with MineTweaker 1.7.10-3.0.10B. Can you fix this?

**Comment by PantACRO4life** [comment]
not fixed
