### ISSUE TITLE
[Bug] Removed silents tools recipes still craft-able in updated version

### ISSUE THREAD

**Issue by MysticAura** [jaredlll08/CraftTweaker#90]
Update to 'closed' issue #87 : unresolved in version 3.0.15

MC: 1.10.2
Forge: 2121
Mod: CraftTweaker-1.10.2-3.0.15
Relating to: SilentsGems-1.10.2-2.1.4-83, jei_1.10.2-3.13.3.376

Script Used:
Same as in closed issue #87 

Issue: The removed recipes for the tier 1 tools disappears properly from JEI, however they are still craft-able. When I check the tool recipes (mt recipes hand) The list is correct with the removed recipes not being listed.

Notes: All other recipe alterations working as intended, same as before.

**Comment by jaredlll08** [comment]
SilentGems does weird things with their recipes, I would suggest reporting to them, since I got no idea on this, and they appear to be registering 3 recipes for one item...
