### ISSUE TITLE
[1.10.2] CraftTweaker restarts JEI twice and causes connection timeouts

### ISSUE THREAD

**Issue by b0bst3r** [jaredlll08/CraftTweaker#91]
jei_1.10.2-3.13.3.376 - specially written by Mezz to log what was causing JEI restarts multiple times, see lines 5740 and 6147 which is the built in deliberate crash/log to see what mod was causing this.

http://pastebin.ubuntu.com/23490940/

CraftTweaker-1.10.2-3.0.15

Version of mods aside I can replicate this timeout and multiple reloading with any JEI after build 362 but 374-376 is particularly bad.

**Comment by jaredlll08** [comment]
nothing at 5740, but the 6147 is exactly where it needs to be, I need to restart jei or else recipes won't appear.

**Comment by b0bst3r** [comment]
Twice?

**Comment by jaredlll08** [comment]
where does it reload twice?

**Comment by b0bst3r** [comment]
sorry I meant 5470 not 5740 so that's your twice at 5470 and 6147

**Comment by jaredlll08** [comment]
I honestly have no idea, I'll speak to mezz about it

**Comment by Peach774** [comment]
talk to mezz, mezz can solve all of your problems

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/CraftTweaker/commit/7f4e59d9df8b8f70702904d80ee72a179f107a22
