### ISSUE TITLE
Recipes Still Not Working.

### ISSUE THREAD

**Issue by CurtisLee1994** [jaredlll08/CraftTweaker#92]
Hello Jared.

The recipes are still broken in your newest update for IC2, Extra Utils and some armor plus recipes.

Regards, Curtis

**Comment by jaredlll08** [comment]
Don't open new issues for old issues.

**Comment by CurtisLee1994** [comment]
Sorry im new to the issues thing, Should i add a comment to my old post?

**Comment by jaredlll08** [comment]
Yes.
