### ISSUE TITLE
[1.10.2] Server-Crash on Linux

### ISSUE THREAD

**Issue by UnPure** [jaredlll08/CraftTweaker#93]
Seems like for some reason CraftTweaker has a X11 problem?
Why does it even need X11?

CraftTweaker: 3.0.15
Forge: 12.18.2.2139

OS: Debian 8.6 (64Bit)

Crashlog: http://pastebin.com/VNPAzYc5
fml-server-latest: http://pastebin.com/WZvwRFSv
minetweaker.log is empty.

If you need any other informations, let me know!

**Comment by A-Smith** [comment]
I see that this bug was fixed a month ago. Could we please get a new build? I get the same error with a headless server. 3.0.15 seems to be the latest release, but it looks like the bug was fixed after that.

**Comment by UnPure** [comment]
3.0.13 is the latest version that can be used on a linux server.
For now, use that version and wait for an update, jaredlll08 is realy busy atm.

**Comment by A-Smith** [comment]
Thanks for the info, and the hard work. This is a really useful mod.
