### ISSUE TITLE
CTGUI flaw on removing recipes (Adds removeShaped instead of remove)

### ISSUE THREAD

**Issue by JAWSAWN** [jaredlll08/CraftTweaker#94]
Basically it is impossible to remove a recipe of an item with ctgui. Even if you uncheck the shaped button it adds recipes.removeShaped

instead of just the remove.

**Comment by jaredlll08** [comment]
uh I just tested this, I can't reproduce...
Used this setup: http://www.blamejared.com/content/j3CEN.png

And this was the script file after: http://www.blamejared.com/content/9E9eY.txt

**Comment by jaredlll08** [comment]
Looking at it, there is a flaw the the remove though, not like you described though. It is fixed now
