### ISSUE TITLE
Client crashes when connecting to server (Bungeecord)

### ISSUE THREAD

**Issue by hunter688** [jaredlll08/CraftTweaker#95]
When connect from lobby to modded server, sometimes client crashes.

http://pastebin.com/eHiavr7G

I think problem is similar like in the IC2 Bugtracker:

http://bt.industrial-craft.net/view.php?id=1869

I this ticket points to minetweaker problem. (something with recipes)

**Comment by jaredlll08** [comment]
I know, read what aroma posted, and try that, give logs

**Comment by jaredlll08** [comment]
Closing this as no response was received

**Comment by hunter688** [comment]
I posted i to IC2 BT.

**Comment by jaredlll08** [comment]
And? What did they say?

**Comment by hunter688** [comment]
nothing yet... bug is still open

**Comment by jaredlll08** [comment]
Well did you try the mod that aroma posted?

**Comment by hunter688** [comment]
yes, why you not read the ticket ?

**Comment by jaredlll08** [comment]
Last time I did, there was nothing.

**Comment by hunter688** [comment]
I think IC2 ticket http://bt.industrial-craft.net/view.php?id=1869
