### ISSUE TITLE
[1.7.10] Localizations not reloading on language change

### ISSUE THREAD

**Issue by JasonMcRay** [jaredlll08/CraftTweaker#97]
I do not know if you are still maintaining the 1.7.10 version, but...

Localizations does not retain themselves if I change the minecraft language.

Example:

I have this localization set:
game.setLocalization("tc.research_name.GT_TRANSFIERYSTEEL", "Fiery Steel Transmutation");

When I start game everything is fine. But when I change the language, the thaumonomicon entry does not get localized until I do /mt reload.

**Comment by JasonMcRay** [comment]
Ok it does not happen only with thaumonomicon... It happens also with normal for example block renaming.

**Comment by jaredlll08** [comment]
1.7.10 is not supported. Seriously, it is 4 game versions old now...
